### ISSUE TITLE
Refactor database to be independent of collections

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1015]
The current database is flawed as soon as you want to provide multiple collections. It also couples the database to the concept of a collection, which intereferes with giving the users some freedom how to define collections.

We need to do a refactor of the db to eliminate this dependency. Database should not know about collections at all.

**Comment by b5** [comment]
Rudi has suggested we scope this to be one small change that explicitly doesn't cover abstracting away from the concept of files

**Comment by rklaehn** [comment]
So a part of this is done - we no longer have collections in the database. We also have the read part of the database abstracted, so you can e.g. run a test or a transient node fully in memory.

What we do not have yet is abstracted write. That is a bit of a can of worms, and probably won't land in 0.5.0 in good quality.

Note that I have this on a branch, but it is quite simple. E.g. it does not allow for resuming partial downloads yet. And the current file based stuff is actually pretty sophisticated.
