### ISSUE TITLE
netcheck: Allow functioning without bound stun sockets

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1025]
netcheck should function just fine if there are no bound stun sockets.  Currently it is fatal if either udp or udp6 fail to bind.  It used to be only fatal if udp fails to bind.  But it needs to be changed so that the ping and https probes (and maybe others) keep working and the netcheck actor just keeps functioning.

**Comment by dignifiedquire** [comment]
So tailscale fails if it is unable to bind the IPv4 UDP socket. We could do that for now, just because we can bind it doesn't mean we can communicate with anything over it though, so not sure when this would actually happen.
