### ISSUE TITLE
Fixing `cargo deny` for branch `x-hp`

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1035]
Time dependency: 
- [x] `build-data`: https://gitlab.com/leonhard-llc/ops/-/issues/11 (removed from dependencies)
- [x] `rustls-acme`: https://github.com/FlorianUekermann/rustls-acme/pull/43
- [x] `wmi` should already be fixed, looking at the code

Git dependency:

- [ ] `derive_more`: https://github.com/JelteF/derive_more/issues/259
- [x] `ed25519-dalek`

**Comment by Arqu** [comment]
x-hp is merged, no deny issues.

**Comment by dignifiedquire** [comment]
This is not done yet.  These are followuos that block us from releasing

**Comment by Arqu** [comment]
Whoops, sorry.
