### ISSUE TITLE
CLI get `--single` does not work

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1066]
Both fetching to stdout and fetching to a folder currently assume that the first response is a collection.

Ref #1062

**Comment by rklaehn** [comment]
This was definitely working. I think it must have gotten lost during a refactoring. Will fix.

**Comment by rklaehn** [comment]
WIP PR https://github.com/n0-computer/iroh/pull/1070

**Comment by b5** [comment]
closed by #1070
