### ISSUE TITLE
relay: no support for wildcard certs

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#1108]
The current implementation of derper does not support wildcard certs.
[This](https://letsencrypt.org/docs/challenge-types/) describes the possible challenge methods and which are compatible with `*.domain.tld` certificates.

**Comment by dignifiedquire** [comment]
Manual certificate mode is available as workaround for now.

**Comment by Arqu** [comment]
This is still active, we only do the `TLS-ALPN-01` challenge

**Comment by Arqu** [comment]
Making sure the issue is up to date:
This basically boils down to it not being worth supporting the DNS challenge directly and writing whatever number of integrations with DNS providers. The solution is to write a custom cert resolver that just hot-reloads the cert every day and putting certbot in front with the right DNS config to handle the renewals.
