### ISSUE TITLE
documented example for configuring iroh to use a local derper

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1135]
We need a documented example setup for running a local derper with either self-signed certs or without https. This is a nontrivial thing to do at the moment, and requires careful `derper` flag composition to avoid conflicting configuration.

The example should show the reader how to have all parts of iroh running locally, including the derp server. ~~bonus points if it can be expressed as a rust example~~ nm, can't (reasonably) be done as a rust example

**Comment by dignifiedquire** [comment]
> bonus points if it can be expressed as a rust example

That would make little sense, given the derper needs to be a separate binary/process

**Comment by dignifiedquire** [comment]
> self-signed certs

This won't work, because iroh won't accept self signed certs (on purpose). The `dev` mode just disables TLS. 
For running with TLS, a DNS record is required and then the derper can just generate certificates using letsencrypt automatically.

**Comment by b5** [comment]
> That would make little sense, given the derper needs to be a separate binary/process

I knew it didn't make sense when I wrote it, but I wrote it anyway 🤷? original issue updated :)
