### ISSUE TITLE
lossy node events results in flaky tests

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1139]
The `iroh::node::Node` struct has a `.subscribe()` method which returns a broadcast receiver with 256 slots.  Since events are emitted for every blob it is hard to ensure you receive all events.  Yet for some applications, i.e. our tests, it is required to not miss any events.

We could enable this system to provide backpressure and slow down the provider.  One option is to use an callback to receive events, then it is up to the user to decide how to handle the events and whether they should provide backpressure or be lossy.

**Comment by rklaehn** [comment]
Can we just make the buffer really big and have a test that makes sure that the messages are manageable in size, in the short term? That should solve it for now, and I think we have more urgent things to do than to obsess about a, say 128kb, buffer.

```rust
#[cfg(test)]
fn test_msg_size() {
  assert!(std::mem::size_of::<Msg>() <= 32);
}
```
