### ISSUE TITLE
feat(p2p): add gossipsub

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#115]
Should add gossipsub, and rpc commands & cli commands ideally to interact with it

Ref: https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html

**Comment by ramfox** [comment]
Some of these are obvious (publish/subscribe/unsubscribe), but these seem to be the main ways we want to interact with gossipsub at the start. I've separated them into a list of methods to write rpc commands for now, and commands to punt for later. Although... I can just do them all.

Add rpc commands for:
- [ ] [add_explicit_peer](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.add_explicit_peer)
- [ ] [all_mesh_peers](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.all_mesh_peers)
- [ ] [all_peers](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.all_peers)
- [ ] [mesh_peers](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.mesh_peers)
- [ ] [publish](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.publish)
- [ ] [remove_explicit_peer](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.remove_explicit_peer)
- [ ] [set_topic_params](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.set_topic_params)
- [ ] [subscribe](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.subscribe)
- [ ] [topics](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.topics)
- [ ] [unsubscribe](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.unsubscribe)


Punt:
- [blacklist_peer](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.blacklist_peer)
- [peer_protocol](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.peer_protocol)
- [peer_score](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.peer_score)
- [remove_blacklisted_peer](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.remove_blacklisted_peer)
- [report_message_validation_result](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.report_message_validation_result)
- [set_application_score](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.set_application_score)
- [with_peer_score](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.with_peer_score)
- [with_peer_score_and_message_delivery_time_callback](https://docs.rs/libp2p/latest/libp2p/gossipsub/struct.Gossipsub.html#method.with_peer_score_and_message_delivery_time_callback)

**Comment by dignifiedquire** [comment]
we will need a way to create a topic, other than that, looks good to me for a first pass
