### ISSUE TITLE
derper failing in tests doing tls[manual] handshake

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1153]
https://github.com/n0-computer/iroh/actions/runs/5414588135/jobs/9841863084

open any successful test and search "TLS[manual] accept"

**Comment by dignifiedquire** [comment]
what was the issue here?

**Comment by ramfox** [comment]
For all the `conn` transfer tests, we had the "hostname" for the derper w/ an "http" scheme, when the derper is running w/ tls enabled.
