### ISSUE TITLE
Remove `Ticket` from internal handling

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1163]
See: https://github.com/n0-computer/iroh/pull/1159#discussion_r1252268732 

ticket should be a separate thing that parses into a `GetRequest`, instead of handling both `get` and `get-ticket` as enumerations.

**Comment by b5** [comment]
related, but not the same: #967

**Comment by rklaehn** [comment]
I think with my 2 changes we can consider this done. TIcket is now just another way to produce options for dialing...
