### ISSUE TITLE
Change derpmap to have Arc<DerpNode> as values

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1182]
The derpmap is an expensive struct yet it gets cloned around all the time.  Furthermore especially in netcheck we jump from `DerpNode` to it's name as a string to pass around so it is cheaper.  To only later look up this name and find the `DerpNode` again.  This all would be a lot nicer if we globally made the `DerpMap` contain `Arc<DerpNode>` entries.

**Comment by dignifiedquire** [comment]
Maybe, I thought about this, but there were cases where those values are changed in the past, which would require them having locks, making this quite painful.

**Comment by flub** [comment]
The only write I can find is for the whole `DerpMap`.  AFAIK it only closes existing connections to derpers no longer in the `DerpMap` and otherwise simply replaces it.  This still means that nodes in the `DerpMap` could remain an `Arc<DerpNode>` I think.

**Comment by dignifiedquire** [comment]
Yeah, honestly I think at this point it is purely a config that gets set at the start of the program (baring dynamic config reload)

**Comment by rklaehn** [comment]
If there is a need to change individual DerpNode entries, maybe you can do a cheap in place mutation scheme using https://doc.rust-lang.org/std/sync/struct.Arc.html#method.make_mut ?

Make derpmap something like this:

```
pub struct DerpMap {
    /// A map of the different region IDs to the [`DerpRegion`] information
    pub regions: Arc<HashMap<u16, DerpRegion>>,
}
```

And then use Arc::make_mut on region before modifying something. Usually there should be only one holder of the regions map and make_mut would be very cheap, right?
