### ISSUE TITLE
impl: config structure

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#12]
Most services will need some configuration support. Should get started on having a centralized `~/.iroh` config folder.
dig suggests taking a look at https://github.com/mehcode/config-rs/blob/master/examples/hierarchical-env/settings.rs

**Comment by dignifiedquire** [comment]
We will want to support env variables with prefixes, as well as environment based config files, plus hierarchical, like git (user home dir global, then local to the current folder overwrites these for this specific thing)

We will also want auto reloading as much as possible, or at least detection that the config has changed at some point.

**Comment by dignifiedquire** [comment]
For the different parts, I imagine each crate has its own `Config` struct, that needs to be populated, and is either part of a subsection in `.iroh` config, or its own `.iroh-network`, `.iroh-database`, depending on the deployment.

**Comment by dignifiedquire** [comment]
@ramfox can we close this?

**Comment by ramfox** [comment]
closed by https://github.com/n0-computer/iroh/pull/112
closed by https://github.com/n0-computer/iroh/issues/102
