### ISSUE TITLE
flakey tests

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#1211]
We're battling flakey tests for a while now. This is a quick summary of the ones observed in the past 4-5 days.

Currently active:
- `cli_provide_folder` [seen here](https://github.com/n0-computer/iroh/actions/runs/5516918836/jobs/10058860217)
- `test_mesh_network` [seen here](https://github.com/n0-computer/iroh/actions/runs/5513113037/jobs/10050818388)

Past few days:
- `test_mesh_network` [seen here](https://github.com/n0-computer/iroh/actions/runs/5507072068/jobs/10036549592) [and here](https://github.com/n0-computer/iroh/actions/runs/5484513530/jobs/9992157753)
- `multiple_clients` [here](https://github.com/n0-computer/iroh/actions/runs/5486213912/jobs/9996022409) [and here](https://github.com/n0-computer/iroh/actions/runs/5484888292/jobs/9993005557); this was 4 days ago, haven't seen it since

**Comment by Arqu** [comment]
Fresh ones
`test_mesh_network` [here](https://github.com/n0-computer/iroh/actions/runs/5524404388/jobs/10076663604)
`cli_provide_from_stdin_to_stdout` [here](https://github.com/n0-computer/iroh/actions/runs/5524404388/jobs/10076663286)

**Comment by Arqu** [comment]
`android NDK?` [here](https://github.com/n0-computer/iroh/actions/runs/5524404388/jobs/10076663741)

**Comment by Arqu** [comment]
`test_two_devices_roundtrip_quinn_magic` [😭 < click](https://github.com/n0-computer/iroh/actions/runs/5555969386/jobs/10147856488)

**Comment by dignifiedquire** [comment]
https://github.com/n0-computer/iroh/actions/runs/5578983351/jobs/10193927630

**Comment by rklaehn** [comment]
So tried `while true; do cargo test cli_provide_folder; done;` locally. So far it did not fail for me.

From the CI output it seems like it is starting the provider that fails, not trying to get the data:
```
thread 'cli_provide_folder' panicked at 'Error from reader: command ["/Users/hetzner/actions-runner/_work/iroh/iroh/target/debug/iroh", "provide", "/Users/hetzner/actions-runner/_work/iroh/iroh/target/testdir-1/cli/cli_provide_folder/src", "--addr", "127.0.0.1:0", "--rpc-port", "disabled"] exited with code 1', iroh/tests/cli.rs:627:21
```

So under what circumstances would starting the provider fail?

**Comment by dignifiedquire** [comment]
you should run all cli tests together, I have seen failures especially under contention (parallel test execution) in the past

**Comment by rklaehn** [comment]
Hm, so we don't see flakiness in any other of the cli_provide... tests? That would mean that it can't be something about the network, but must be something about the disk io...

**Comment by rklaehn** [comment]
Now that is interesting. We had a failure in cli_provide_addresses, which does not even run the get side at all...

https://github.com/n0-computer/iroh/actions/runs/5586319462/jobs/10210202367?pr=1266

**Comment by Arqu** [comment]
Another android related one https://github.com/n0-computer/iroh/actions/runs/5678235730/job/15388051589?pr=1304

**Comment by dignifiedquire** [comment]
```
failures:

---- magicsock::tests::test_two_devices_setup_teardown stdout ----
DERP listening on 127.0.0.1:52325
STUN listening on 127.0.0.1:57035
setting up magic stack
waiting for connection
closing endpoints
cleaning up
DERP listening on 127.0.0.1:52331
STUN listening on 127.0.0.1:65324
setting up magic stack
waiting for connection
closing endpoints
cleaning up
DERP listening on 127.0.0.1:52334
STUN listening on 127.0.0.1:62877
setting up magic stack
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `5`', /var/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/default-net-0.16.2/src/gateway/macos.rs:293:9
```

seen in https://github.com/n0-computer/iroh/actions/runs/5860002609/job/15887178827?pr=1350

**Comment by flub** [comment]
`iroh::tests::provide::test_token_passthrough`
https://github.com/n0-computer/iroh/actions/runs/5974544114/job/16208899155?pr=1363

**Comment by dignifiedquire** [comment]
`token_passthrough`: https://github.com/n0-computer/iroh/actions/runs/5977718371/job/16218291259

**Comment by Frando** [comment]
`magicsock::tests::test_two_devices_setup_teardown` https://github.com/n0-computer/iroh/actions/runs/6024954522/job/16344696490

**Comment by Frando** [comment]
`cli_provide_tree_resume` https://github.com/n0-computer/iroh/actions/runs/6047343861/job/16410611550?pr=1439

**Comment by ramfox** [comment]
`sizes` https://github.com/n0-computer/iroh/actions/runs/6344492335/job/17234699173?pr=1504

**Comment by dignifiedquire** [comment]
> malloc_consolidate(): unaligned fastbin chunk detected

https://github.com/n0-computer/iroh/actions/runs/6392480667/job/17349815790?pr=1567

**Comment by divagant-martian** [comment]
could we create individual issues for these tests so that we can track their progress individually? Maybe we can hag a tag `flakey-test` ?

**Comment by dignifiedquire** [comment]
`provide_tree_resume` https://github.com/n0-computer/iroh/actions/runs/6461115175/job/17540144287

**Comment by dignifiedquire** [comment]
cli_provide_from_stdin_to_stdout (windows)
https://github.com/n0-computer/iroh/actions/runs/6545625977/job/17774498427?pr=1647

**Comment by Arqu** [comment]
There's a flake with
```
---- magicsock::tests::test_two_devices_roundtrip_quinn_raw stdout ----
Error: Address already in use (os error 98)
```
Seen it a couple times today

random run here https://github.com/n0-computer/iroh/actions/runs/6586682752/job/17901198803
another one from the merge queue https://github.com/n0-computer/iroh/actions/runs/6587703614/job/17898489983

**Comment by dignifiedquire** [comment]
gc failures

https://github.com/n0-computer/iroh/actions/runs/6616929497/job/17972165628

cc @rklaehn

**Comment by dignifiedquire** [comment]
---- node::tests::test_node_add_tagged_blob_event stdout ----
Error: rebind IPv4 failed

Caused by:
    failed to bind any ports (tried [0])

https://github.com/n0-computer/iroh/actions/runs/6652411203/job/18076335496

**Comment by dignifiedquire** [comment]
cli_provide_folder

https://github.com/n0-computer/iroh/actions/runs/6671699701/job/18134167949?pr=1755

**Comment by Arqu** [comment]
We have still have flakes but have a new flow of managing them. This issue is stale.
