### ISSUE TITLE
netcheck: Implement https probe

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1218]
The https probe is currently included in the probeplan and executed, but it is not implemented either as a probe nor in the derper.  Both need to be implemented.

**Comment by flub** [comment]
https://github.com/n0-computer/iroh/tree/flub/https-probe is a branch where this was implemented fairly fully.  It stalled on something silly, I think tests (which now should be possible - there is testing infra to run an entire relay server in a unittest now).  It probably can't be merged immediately because so much has changed, but hopefully a lot of it can be used.

**Comment by matheus23** [comment]
This is necessary work for #2799

**Comment by matheus23** [comment]
@flub can this be closed now that https://github.com/n0-computer/iroh/pull/2903 landed?

**Comment by flub** [comment]
yes!
