### ISSUE TITLE
Convert tests to in memory

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1229]
There are a large number of tests which use files which are not meant to test file IO.

They can all be replaced with tests that work with an in memory database. Maybe that helps with test execution times.

Look for this:

```rust
Path::new(env!("CARGO_MANIFEST_DIR")).join("README.md");
```

**Comment by rklaehn** [comment]
Implemented in https://github.com/n0-computer/iroh/pull/1232

**Comment by dignifiedquire** [comment]
can we close this?

**Comment by rklaehn** [comment]
I think most tests are now in mem. We don't want them all to be in mem, otherwise we would never test the file io stuff. So I think we can close this.
