### ISSUE TITLE
Allocate and document derper regions

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1246]
Derper regions are used to identify the derpers in configs.  The region IDs are u16 and need some kind of global uniqueness so that people's configurations work out.  Currently we have very few conventions or documentation around this.  We need to:

- Come up with decent classes of derp regions
- Document these clearly

The goal is to make it as easily as possible for independent people to run their own derpers without conflicting.

Some options to start with:

- A range for testing (you want to test inter-region things too!)
- A range reserved for number0
- A range reserved for "private use".
- A range open for allocation to other entities.
- A range with some random allocation so you can do public use without registry

**Comment by dignifiedquire** [comment]
the ranges are meant to indicate geolocation, not ownership

**Comment by flub** [comment]
> the ranges are meant to indicate geolocation, not ownership

Though we want to enable people to not depend on number0 derp servers if they don't want to.  And we'd also like to enable people to do that in a way that does not force them to be incompatible, e.g. someone who wants to connect to private derpers as well as to number0 derpers should be able to do so.  And since the derp region id is used as an index into the derp map it makes it a globally unique index.  A very small one at that, so perhaps it should have more bits available.

**Comment by dignifiedquire** [comment]
But the index is into a locally configurable list of things, where you can have many servers per region.

**Comment by flub** [comment]
Should we then even hardcode the north america and europe regions in the code in that case?  Are region IDs entirely a runtime artefact?  In that case we should make the config to be a list and not expose region IDs to the user at all?  (well, maybe in the debug logs)

**Comment by dignifiedquire** [comment]
> This suggests my earlier understanding of region IDs being a global identifier being not too far off?

They need agreement between parties that want to connect. So nodes need to have a shared configuration over what servers map to what region.

**Comment by dignifiedquire** [comment]
We have stopped using derp_regions and now use direct urls
