### ISSUE TITLE
Prevent multiple iroh daemon processes from using the same IROH_DATA_DIR

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1281]
It just causes a lot of weirdness to have 2 processes with the same private key.

**Comment by ramfox** [comment]
looks like https://github.com/n0-computer/iroh/blob/53b0bb058a2aae635e07d1db7db76a1f9b6189ed/iroh-sync/src/store/fs.rs#L80 from PR https://github.com/n0-computer/iroh/pull/1333 prevents us from running multiple daemon processes using the same `IROH_DATA_DIR` now.
