### ISSUE TITLE
Allow providing single files

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1290]
Currently, providing a single file will wrap it in a collection. Since we got single blob support we don't need to do that anymore...

We should just add it as a blob and generate an appropriate ticket.

**Comment by rklaehn** [comment]
This is easy enough to implement. And I am very convinced that we should do it. However, I am not sure what the implications are regarding reporting events.

I think currently reporting is all in terms of collections, and this would have to change. Can you comment what you would need, @b5?

**Comment by dignifiedquire** [comment]
The big downside of not wrapping in a collection is that you loose the name information of the file though.

**Comment by rklaehn** [comment]
Done. We now got the wrap option to preserve the file name, or not.
