### ISSUE TITLE
Rethink temp file handling in iroh cli

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1291]
Currently this is being done with an invisible temp directory inside the target directory. That causes a fair bit of trouble.

Maybe it should be in IROH_DATA_DIR after all, or at least next to the target dir?

**Comment by dignifiedquire** [comment]
Given that we already have `IROH_DATA_DIR` it seems the simplest one for now.

**Comment by rklaehn** [comment]
> Given that we already have `IROH_DATA_DIR` it seems the simplest one for now.

Yeah, I think this is the way to go for the daemon. The issue is what to do with a quick get without a daemon. I think I will be going with this:

-if you get to STDOUT there is no attempt to resume. We want this to work even on a ro filesystem
-if you get to an out dir, we will try to find a place for a hidden data directory and use that as IROH_DATA_DIR. This will be deleted once the get is complete. Where?

- inside `out`:
  advantage: you know you can write there
  disadvantage: this might cause trouble if the thing you are getting contains a dir of the same name
- next to `out`:
  you might not be able to write there, and it might already exist and cause trouble

**Comment by rklaehn** [comment]
This is done. We now create a dir next to out which is just an IROH_DATA_DIR of a temporary node.
