### ISSUE TITLE
Some kind of deletion for the store

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1336]
We currently have really no way to delete stuff from the blob store. I think we should have it sooner rather than later. Deleting content-addressed data requires some kind of GC concept.

**Comment by dignifiedquire** [comment]
yeah, sync especially expects to deleete old versions on new incoming pieces, as otherwise you can overflow quite quickly

**Comment by rklaehn** [comment]
This is related: https://github.com/n0-computer/iroh/issues/1394

If we have a format integer, collections can conceptually form DAGs. If not, then they are always just flat. It does not matter that much in case of a mark and sweep GC, but I just want to mention it.

**Comment by rklaehn** [comment]
OK, so here is the plan:

the state of the gc is a last_seen table for *blobs*, basically Hash -> SystemTime. This gets updated in regular intervals by a mark method.

In addition there is a second task that just looks at all the things that are sufficiently old and physically deletes them.

**Comment by dignifiedquire** [comment]
we now have a GC
