### ISSUE TITLE
Distinguish between errors in iroh bytes get requests

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1348]
Currently the functions in https://github.com/n0-computer/iroh/blob/main/iroh/src/get.rs all return `anyhow::Error` in the error case. The error case can mean a few things:

* Connection errors (basically everything on the quinn layer) - peer went offline, you went offline, ...
* Protocol errors (peer did not conform to protocol)
* Not found (everything working as intended, but the peer does not have what you're asking for)

When I worked on the downloader, I wanted to treat the "not found" case different to the other "actual error" cases: For the "not found" case, I just want to continue with the next hash to download. For the actual error cases, we'd either want to retry or to drop that peer entirely.

Now, it might be possible already to find out which error case occured by trying to downcast the `anyhow::Error` (I did not try this out yet).

To ease this for users and ourselves, I think we should do one of the following

* Add docs to the `get` module or functions on how to find out what kind of error occured through downcasting (iow, document which error types might be contained in the `anyhow::Error`)
* Return a proper error type, like an `GetError` enum (naming tbd) with at least the cases above
* Return `Ok(None)` for the "not found" case

**Comment by rklaehn** [comment]
Somewhat related issue: https://github.com/n0-computer/iroh/issues/962

We made the decision to not have dedicated error codes on the wire. Basically - if something unexpected goes wrong, the stream will be terminated with an error (basically 500). If we don't have a hash or some requested chunk of a hash, the stream gets closed without an error (400). The latter would I think be an UnexpectedEof, exactly the same as if a file was too short. If there is an issue with the overall connection error, you would either get an explicit connection error or a timeout.

As described in the issue above, we could handle some or all of these cases and return distinct errors. I don't think downcasting from anyhow is something the user should have to do, if we can avoid it.

**Comment by rklaehn** [comment]
It will be hard to distinguish between protocol errors and hash not found. The nature of bao and also our protocol that has been done in the spirit of bao is that there is almost no redundancy. E.g. the type of stuff going over the wire depends on the state you are currently in and is not marked with any type descriptor. So e.g. if the requester sends some data where the provider expects a hash, the provider will interpret the first 32 bytes as a hash, look them up, and then most likely answer that this hash is not found...

**Comment by rklaehn** [comment]
If a hash is not present at all, you will get an io error with error kind UnexpectedEof when reading the header.

If a part of the data that you have asked for is not present, you should get an UnexpectedEof somewhere later.

**Comment by rklaehn** [comment]
implemented in #1362
