### ISSUE TITLE
Iroh-common base library

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1354]
We have a number of things that are common to all libs. E.g. utility functions and reexports. We have to be careful since these "common" crates often get quite fat, but I think it nevertheless be good to have one.

What we could do there would be to reexport crates so that we have a single place to do things like the blake3 -> iroh-blake3 change, and have generic utility functions like all the stuff related to progress.

**Comment by dignifiedquire** [comment]
I like `iroh-shared` as a name, but otherwise yes lets get this done.

**Comment by dignifiedquire** [comment]
Fixed in https://github.com/n0-computer/iroh/pull/1780
