### ISSUE TITLE
Cleanup variable and generic naming

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1355]
After #1216 is merged we should settle the naming of the bao store and the doc store in variables, struct fields and generics. Currently it is very inconsistent because things were not changed to keep rebasing feasible.

Here's a first suggestion:

* BAO store: `blobs`, `blob_store` or `bao_store`? with generic `B`
* Docs store: `docs` or `docs_store`? with generic `D`

**Comment by ramfox** [comment]
@rklaehn @Frando did this get straightened out?

**Comment by dignifiedquire** [comment]
this happened over the last PRs
