### ISSUE TITLE
Check that magicsock via derp works from linux to mac - handling of segment_size

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1357]
When working on some quinn testing infrastructure in quic-rpc, I noticed the following:

- on linux, you will often get transmits with the `segment_size` field set and `contents` larger than a single UDP packet.
- when in derper mode, as far as I can see the contents will just be sent to the derper as single blobs. See https://github.com/n0-computer/iroh/blob/1c3a3f131d2f394f18118a6a153ff8f0f29e9a83/iroh-net/src/magicsock.rs#L1220 .

There are two issues with this:
1. on linux, the receive buffers that you get from quinn in poll_recv are really large, almost 100000 bytes. But on mac they are quite small, something like 1500 bytes. So why can't the place where the receive buffer is filled from whatever we get from derp here https://github.com/n0-computer/iroh/blob/1c3a3f131d2f394f18118a6a153ff8f0f29e9a83/iroh-net/src/magicsock.rs#L749 panic?
2. in my experiments in quic-rpc I found that quinn gets confused if the packet boundaries get mixed up, and you will get errors such as "packet auth failed". E.g. you send 2400 bytes with a segment size of 1200 bytes, that's two packets. But if you now put this into the buffer on the recv side and set the stride to the entire part len, as we do here https://github.com/n0-computer/iroh/blob/1c3a3f131d2f394f18118a6a153ff8f0f29e9a83/iroh-net/src/magicsock.rs#L1159 , the receiver sees some weird single udp packet.

**Comment by rklaehn** [comment]
This is the PR where I could not get a mem quinn socket to work on linux without considering the segment size: https://github.com/n0-computer/quic-rpc/pull/48

The solution was to split packets on send based on segment size.

**Comment by rklaehn** [comment]
@ramfox or @flub can you enlighten me? Why is it ok to completely ignore the segment_size?

**Comment by rklaehn** [comment]
@Arqu how hard would it be to set up tests where we send from linux to mac via the derper and vice versa? GIven how different the calls are I think we really need this.

If we bypass the derper we just pass through the transmits, so we just rely on quinn-udp being correct.

**Comment by flub** [comment]
So we don't correctly handle segmentation offloading in the derper case.  I realised this already while on holiday though I thought we just lost this optimisation, but what you describe makes it ever worse.  I'm happy to take this issue and make sure we handle this correctly and with as much offloading as we can do.

**Comment by Arqu** [comment]
@rklaehn I'm looking at this and want to set up a test. What scenario do you think I should cover. Provide from mac and get on linux or the inverse. I guess both for best results :)

**Comment by flub** [comment]
> @rklaehn I'm looking at this and want to set up a test. What scenario do you think I should cover. Provide from mac and get on linux or the inverse. I guess both for best results :)

for this specific case providing a large blob by linux and get from mac would trigger i think

**Comment by Arqu** [comment]
BTW fair warning, our current derpers are fairly old compared to main. I'll set up a quick test for this and then we can bump the derper and see how that goes. Just to make sure it's not a red herring.

**Comment by Arqu** [comment]
I've bumped the derpers yesterday, behavior slightly shifted but unrelated to the transfers (also due to my slightly behind branch). Now derp stuff seems to be aligned in my testing but I'm having a hard time forcing derp only transmission in my tests, thus still trying to confirm this.

**Comment by rklaehn** [comment]
> > @rklaehn I'm looking at this and want to set up a test. What scenario do you think I should cover. Provide from mac and get on linux or the inverse. I guess both for best results :)
> 
> for this specific case providing a large blob by linux and get from mac would trigger i think

Yeah, this ^.

The problem is when Linux sends buffers that are more than one packet, with `segment_size` set. So sending something much larger than an UDP packet from Linux to Mac should trigger this.

Receiving from Mac on Linux will not be a problem. You get a trickle of individual UDP packets and never hit the complex code paths.

Linux to Linux via the Derper should also trigger this, in case that is easer to set up.
