### ISSUE TITLE
PublicKey & SecretKey bikeshedding

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1388]
# Background

The cryptographic keys and identities have been reduced to just two types right now:

- `PublicKey`
- `SecretKey`

This `PublickKey` type is used for everything: identifying an iroh node (or peer, formerly done by `PeerId`) as well as encrypting messages to the iroh node (formerly done by the node key).  The `SecretKey` is the obvious secret part for the node itself.  This does not require much explanation (which is the point!).

# Issue

However in some places this naming arguably reduces readability a little:

- types like `Event<PublicKey>`
- parameters like `from: PublicKey`

One could argue that the former `PeerId` was more readable in these places.  However `PeerId` was purposefully removed since this was confusing wrt what is a "peer", what is an "iroh node" etc.

# Proposal

One possible suggestion is to name the new types slightly different:

- `NodeId`
- `NodeSecret`

The hope here is that these names make more sense to someone reading code using the public API without much background.  These terms try to convey a little more meaning than the current more generic names.

----

Other suggestions are of course welcome, this is a bikeshedding issue!

**Comment by dignifiedquire** [comment]
Lets add 

```rust
pub type NodeId = PublicKey;
pub type NodeSecret = SecretKey;
```

to `iroh-net `.

Arguments and functions should use `NodeId` if it is in reference to a a node, and `PublicKey` if it is only in reference to cryptographic references.
eg 
- `encrypt(key: PublicKey)`
- but `send_to(node: NodeId)`

**Comment by dignifiedquire** [comment]
A first pass has been done, if you see peers flying around please make sure to rename them to nodes.
