### ISSUE TITLE
What to do with collections?

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1394]
It seems the core concepts of iroh are now

- docs
- blobs
- connections

we also got one more thing: collections. Currently they are generic with all this abstract collection parser trait stuff. This was done in part to accommodate the IPFS community that wants to see any blob that in some way contains links as a collection.

There are two ways to proceed: one is to lean into this and add a format integer. Then we could in principle support all the different dag-cbor, dag-proto, dag-... etc. formats as collections, have collections in collections, have a proper gc that does graph traversal for liveness.

The other way to proceed would be to hardcode just 1 kind of collection: a sequence of blake3 links with nothing else, and remove all the abstraction. That would mean that we can never support nested collections / dags and that we can't support dag-cbor and friends out of the box. On the plus side it would make things much simpler while still retaining the idea of collections as a way to group blobs that somehow belong together.

(All this talk about bindings made me aware that writing a binding that supports implementing something like a custom collection parser would be a pain)

We would need to be able to cover the deltachat use case and also the capyloon use case with a "just links" collection for option 2 to be viable, obviously.

**Comment by rklaehn** [comment]
@b5 WDYT?

**Comment by b5** [comment]
This is a tough one. Given how much work we're putting into documents, I'd almost rather pitch docs as the better point of integration if you need anything beyond a list of links (as we've discussed elsewhere, a list of links can go a long way if the first link is used by convention to contain metadata).

Honestly, I want to defer making this decision for as long as possible. A lot of this is code we have written, but if I had to make a decision right now, I'd err on the side of option 2: hardcoding the sequence of BLAKE3 hashes into iroh. But to your point, we should guide this decision by looking at real world use cases like deltachat & capyloon

**Comment by rklaehn** [comment]
So while writing GC it seems that some sort of format is needed in any case in the roots table. You have at least a flag to distinguish between blobs and collections. And since we already have the collection parser stuff it is not that far of to fully support DAGs. As I mentioned, you have some kind of DAG anyway in content-addressed systems because e.g. 2 documents and 3 collections could have the same child.

**Comment by rklaehn** [comment]
I am happy with the current approach. The GC and the iroh-bytes proto don't have to know about the exact details of collections, just about hashes and sequences of hashes.
