### ISSUE TITLE
CustomGetRequest rename and rethink

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1411]
When writing the docs it occurred to me that the main difference between the custom get request and the normal get request is that in the custom case the **provider** decides what to send, whereas in the normal case the requester decides. So maybe give this a better name?

There are also a few things we might want to rethink about the custom get request. E.g. the response contains an entire GetRequest, which contains an option of a token. Also, I am not sure how well a custom get request would work with non rust language bindings, since they would have to implement a rust trait...

In general I think in the longer term there will be 3 or 4 request types:

GetRequest
QueryRequest
CustomGetRequest
CustomQueryRequest? (we might not need this?)

**Comment by Frando** [comment]
I think `QueryRequest` is good.  With `GetRequest` you say exactly what you want, and get that or nothing. With `QueryRequest` you send whatever byte sequence as a query to the provider, and they decide what to respond with.

**Comment by rklaehn** [comment]
There is still the question (all the way back from from ipfs thing) if the get request should have some more structure.

**Comment by rklaehn** [comment]
@dignifiedquire mentioned the idea of just getting rid of CustomGetRequest and leave it up to the user to do something similar. Basically, user opens a stream under their own ALPN, sends some stuff back and forth, then reuses the same stream for a bao transfer.

This would work. A custom get request for documents would then use the documents alpn, do some stuff to figure out what is missing, transfer the set of missing data and then switch to bao collections mode.

**Comment by rklaehn** [comment]
CustomGetRequest is gone. You just use your ALPN and then switch to bao on a stream with this alpn if useful.
