### ISSUE TITLE
Avoid rounding up to chunk groups when requesting sub chunk group data

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1412]
Currently, when requesting data that is below a chunk group in size, we round the returned data up to the next chunk group. E.g. if you request chunk range 0..1 of a large file, you will get chunk range 0..16 etc.

This has two major downsides

1. it increases the overhead when requesting small ranges.
    The worst case overhead is still perfectly fine for all data request purposes at ~32 KiB. But it is more than what the bao protocol is capable of, and it is inconvenient for two possible use cases:
  - size proofs: the way to prove that some data is indeed as big as it is claimed is to request validated data for the last chunk. With chunk level granularity such a proof would be <= 1 chunk (1024 bytes) plus a path to the root, so ~2 KiB even for very large files. With the current "rounding up to chunk groups" it is 1 chunk group (16 KiB) plus a slightly shorter path to the root.
  - availability checks: if a node claims to have some data, we can do a check that this is actually the case by requesting a single chunk. The same size logic applies as to the size proof.
2. it makes the chunk group size part of the protocol.
    with the current way of rounding up to chunk groups, and the way bao style protocols work, the provider and the requester need to agree on the chunk group size to make sense of the response. So the chunk group size becomes part of the wire protocol specs. If you were to fill the requested range with tree nodes all the way to chunk boundaries, this would not be the case.

Issue 2 is not that big of a deal. We might have to make some kind of chunk group size part of the protocol in any case. It would just be a different purpose. The purpose of the chunk group size would then be the maximum amount of data you are willing to accept until you get validation information (a hash). This could be part of the request or just hardcoded to some sensible value.

But solving issue 1 would be really quite useful for some use cases.

**Comment by b5** [comment]
> availability checks: if a node claims to have some data, we can do a check that this is actually the case by requesting a single chunk. The same size logic applies as to the size proof.

Are we thinking we'll actually do this in practice? If so, this is reason enough to do this. I would frame the rationale slightly differently than you have here:

We need small chunks to be able to treat arbitrary portions of a blob as "header requests", roughly analogous to "HEADER" HTTP requests, which acknowledge the cost of a network round-trip, but mitigate that cost by fixing the response to a small size. Keeping this size small allows us to make more "HAVE requests" for the same amount of bandwidth, which is a network-level efficiency. This is worth pursuing now because it involves a protocol breaking change.

**Comment by rklaehn** [comment]
> Are we thinking we'll actually do this in practice? If so, this is reason enough to do this. I would frame the rationale slightly differently than you have here:

iroh-bytes is a library, so we don't really know what people might do with it. But this is one of the things I personally would like to be able to do if I was to use iroh-bytes as a library.

The header requests is one of the forseen use cases of this as well, yes. E.g. you got a blob and/or collection and want to peek at just the first few bytes of the blob/each blob to get an idea of the file type.

**Comment by rklaehn** [comment]
This is implemented in bao-tree 0.8.0
