### ISSUE TITLE
Investigate mainline DHT for content routing

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1425]
We already have a few things that result in iroh blobs and collections being **_much_** less demanding in terms of content-discovery compared to dag-cbor. Where e.g. a ML dataset on dag-cbor would be millions of blocks, for iroh it is just 1 collection.

So maybe we should try to just do an initial version of content routing using the mainline DHT https://en.wikipedia.org/wiki/Mainline_DHT and see how far we get?

@Nuhvi did some tests, and the Mainline DHT seems to be one of the more robust DHTs out there...
https://twitter.com/ArNazeh/status/1696129728191599029

**Comment by Nuhvi** [comment]
ICYMI https://gist.github.com/Nuhvi/f5d14b769d2561008d7e89d1109bd06c

TLDR:
1. Subsecond resolution of first peer for an infohash.
2. Can only announce a `port` and the `ip` that the request comes from. So the Iroh Peer has to be reachable on the same IP. If that is impossible, then at least it can be used to discover Iroh's `trackers` that have public IP addresses and go from there.

Will post it rewritten in Rust soon ™

**Comment by Nuhvi** [comment]
Rust (with relay):
https://github.com/Nuhvi/pkarr/blob/rust/pkarr/examples/relay-client.rs

[Mainline](https://crates.io/crates/mainline) ... soon™

**Comment by rklaehn** [comment]
Implemented in https://github.com/n0-computer/iroh-examples/tree/main/content-discovery

**Comment by dignifiedquire** [comment]
A version of this is working
