### ISSUE TITLE
Provider should show a few stats

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1431]
Iroh is very useful to ad-hoc transfer of files and directories.  However while the getter has great feedback about what is going on the provider does not.  It would be great if the provider would show:

```
N connected clients
M completed transfers
```
Or maybe even split the second one up by hash

**Comment by Frando** [comment]
The console and cli have a `node stats` command that shows the metrics.

We should look into presenting these or parts in a better readable form.

**Comment by flub** [comment]
obsoleted by sendme
