### ISSUE TITLE
More than two peers in a document do not properly sync

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1432]
This is a known issue surrounding our set-reconciliation mechanisms & implementation. Team is actively working on this one

**Comment by Frando** [comment]
Related PRs:

* #1426 
* #1428 
* #1430

**Comment by Frando** [comment]
With these 3 PRs merged, I think we can consider this issue to be fixed. We still need more tests to validate all edge cases, but let's close this because there's no known issues with multi-author sync anymore.
