### ISSUE TITLE
possible bug? adding a new address to the magic sock will remove connections made to us

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1440]
We only prune endpoints after a call to `set_network_map`. In that method, we overwrite the internal `MagicSock::netmap` & remove any `MagicSock::peer_map` `Endpoints` that are not present in the latest `netmap`.

This removes any connection information about nodes that have connected to us in the wild.

We may very well want to prune these connections in this way.

However, we use `set_network_map` to add new addresses explicitly to the `MagicSock` / `MagicEndpoint` (using `MagicEndpoint::add_known_addr`). This means anytime we add a new address, we are pruning any "natural" connections made. This seems like an unintended side effect, I don't think a user would expect that any time they add an explicit connection, they are potentially closing connections to other (potentially active) nodes.

**Comment by Frando** [comment]
We should change the data flow so that `MagicEndpoint::add_known_addr` sends a message with the peer info to the actor, and does not fully replace the netmap.

**Comment by flub** [comment]
@Frando so can this be closed now or is #1447 not the whole story?

**Comment by Frando** [comment]
I would guess but am not sure, maybe @ramfox can confirm that the situation that triggered this issue does not occur anymore.

**Comment by ramfox** [comment]
closed by #1447 !
