### ISSUE TITLE
what should happen when `iroh doc join` cannot connect to the peer info in the ticket?

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1461]
Right now, if the peer in the ticket is unavailable, it seems to be the "join" is still successful from the console. This can lead to unexpected outcomes when documents are not in fact synced. We should decide if this is an error.

cc @divagant-martian

**Comment by Arqu** [comment]
Just some random commentary from my end.
I'm unsure if the default behavior for iroh should be a serve and response model or if it should be a "torrent" style thing.
For the cURL example with iroh it obviously makes sense to be request and response and hence "get ticket" should error out if unavailable. But in the sync example it should be more in the spirit of "x nodes connected" and then you fetch from some of them and hence no failure in that case. This becomes even more prominent as we approach work on content routing.

**Comment by b5** [comment]
closing as stale. We should split this into a bootstrapping connection error in gossip. not a thing around tickets.
