### ISSUE TITLE
wrong default location for the Data Directory

### ISSUE THREAD

**Issue by eminence** [n0-computer/iroh#1463]
Hello! :wave:

In the [Configuration/Data Directory](https://iroh.computer/docs/reference/config#data-directory) section, it says that default data directory is `$XDG_CONFIG_HOME` or `$HOME/.config/iroh`

However, on my Debian Linux system (which does not have $XDG_CONFIG_HOME set), the data directory ended up being in `$HOME/.local/share/iroh`

**Comment by flub** [comment]
just checked and i think the code is right but the linked doc is wrong.  `$HOME/.local/share/iroh` is the default for `$XDG_DATA_HOME` which is the right value to use for the data directory.  That section should describe `$XDG_DATA_HOME` rather than `$XDG_CONFIG_HOME`.

**Comment by matheus23** [comment]
We've fixed this on the website now:
![image](https://github.com/user-attachments/assets/09ef4cce-223e-497a-80a2-e8bd5cd207c9)
