### ISSUE TITLE
Switching from Wifi to Cellular with a running iroh node breaks connections

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1464]
this issue tracks network interface switching detection. When switching is working properly the magicSocket should transparently handle changes in the underlying connection topology & things should "just work"

**Comment by dignifiedquire** [comment]
I wrote up the handling in tailscale, which we should pretty much just mirror: https://number-zero.notion.site/Network-Change-Monitoring-7ab0ac445c414f158b66df38611a533c?pvs=4

**Comment by b5** [comment]
closed by #1472
