### ISSUE TITLE
iroh-net: purge `PeerMap` entries

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#1483]
While checking out what peer info we have for #1481 I noticed the [`PeerMap`](https://github.com/n0-computer/iroh/blob/a89078f5ede5ee918df1d917337342cc9206dbf2/iroh-net/src/magicsock/endpoint.rs#L1003-L1028) is only growing. No entries are ever removed. The tracked [`Endoint`](https://github.com/n0-computer/iroh/blob/a89078f5ede5ee918df1d917337342cc9206dbf2/iroh-net/src/magicsock/endpoint.rs#L51-L82) has an `expired: bool` field, but it's never set to true. We should figure out under what conditions are peers evicted from this map

**Comment by divagant-martian** [comment]
There is a `last_active` field on the `Endpoint`. An option is to retain at most `n` potentially disconnected peers. We could prune the peers that have been disconnected the longest to stay under limits

**Comment by dignifiedquire** [comment]
This works is happening in #1653

**Comment by divagant-martian** [comment]
closed by #1653
