### ISSUE TITLE
(sync) Prevent document content being lost in case of disconnects

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1489]
Quoted from discord @Frando:

So I'm thinking about downlaod improvements etc. So far we came up with two short-term ideas, implemented in #1480 
* Include the content status (available/missing) for entries sent to a peer during set reconciliation
* When finishing a content download for a document entry, notifiy immediate swarm neighbors about this (through a new scoped-to-neighbors gossip mode)
* With this we'll inform the downloader about these Provider peers for a hash, and start a download immediately. All good and much faster content resolving without delays than what we do atm.

However! Take this scenario:
1) Alice publishes a new entry in a doc. Entry is broadcast to all joined peers.
2) Alice goes offline immediately after publishing, and before any peer has downloaded the content.
Now Bob and Claire have Alices's entry, but not the blob. All as expected.
3) Now Alice comes online again the next day. But! Neither Bob nor Claire would try to download the missing content from Alice, because there would be no news from her (no new entry published, so no gossip message, and no updates in set reconciliation because sets are already synced).

I think we really need to solve this, at least somehow. Otherwise we will easily have bug reports about "lost content" that never gets synced.

Ideas?

**Comment by dignifiedquire** [comment]
Closing as stale
