### ISSUE TITLE
metrics: ability to compile without metrics

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#149]

**Comment by mxinden** [comment]
Would you mind expanding on the rational here @ramfox?

**Comment by dignifiedquire** [comment]
this is mostly for mobile deployments, where we want the option to reduce build size and any form of tracking as much as possible

**Comment by Arqu** [comment]
It's not a 100% match (need to do some voodoo if you want to compile without it) but I call it done for now and will revisit in the future if needed.
