### ISSUE TITLE
Figure out what to do with request tokens and documents/sync

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1519]
I was having a look at the CLI start vs add etc - and re-noticed that we have a concept of `RequestToken` in iroh-bytes, which has 2 issues atm:
1) It is not supported in docs at all (i.e. if you set a request token during node startup, docs cannot exchange content)
2) with the CLI we only support creating a ticket with an embedded token  for data added directly with `iroh start` (i.e. the old `provide` flow), but not for data added later with `iroh add`

Point 2) should be easy enough to solve by exposing ticket creation over the RPC (`iroh.blobs.ticket(hash)` or so). However about 1) I'm unsure. For release we should add to the notes though that sync is incompatible with `--request-token`

**Comment by dignifiedquire** [comment]
Closing as stale
