### ISSUE TITLE
 Audit usage of unwraps

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1528]
`thread 'sync_big' panicked at 'called Result::unwrap() on an Err value: ()', iroh/iroh-net/src/magicsock.rs:1175:28`. This happened at the end of the test, after calling `node.shutdown()`

**Comment by divagant-martian** [comment]
I'm splitting this as they are unrelated and closed by different solutions https://github.com/n0-computer/iroh/issues/1531

**Comment by flub** [comment]
We should still audit other places for this.  But it's painfully manual and error-prone.
