### ISSUE TITLE
Investigate duplicate packets

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1547]
When downloading multiple blobs at the same time, I see a large number of duplicate packets on the provider side.

At the same time there is a reduction in download speed.

This is all on localhost, so I don't really see why there would be duplicate packets.

![image](https://github.com/n0-computer/iroh/assets/248257/40e9377d-7603-47e4-a884-7ae52dfbb341)

**Comment by dignifiedquire** [comment]
are you seeing a continous flow of duplicate packets, or a short burst at the beginning?

**Comment by dignifiedquire** [comment]
> so I don't really see why there would be duplicate packets

At the beginning there are always some duplicate packets, until we have verified that the ip addresses we have (even if localhost) actually work. But this should be only for a very short period of time at the start.

**Comment by rklaehn** [comment]
Whatever duplicate packets we have now are probably different ones than those. So let's close this for now.
