### ISSUE TITLE
PeerAddr relies on local configuration to dial a peer

### ISSUE THREAD

**Issue by dvc94ch** [n0-computer/iroh#1556]
The region id is local configuration information. For iroh-net to work all peers need to use the same derp map configuration.

**Comment by dignifiedquire** [comment]
Yes, this is by design currently, so that nodes can decide which derp servers to use and which not. (Not saying this is optimal, just that the current design is intended to work like this) 

> need to use the same derp map configuration.

Only the regions that are being used have to overlap, not the whole configuration
