### ISSUE TITLE
clean up  output for `node connections`

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1576]
1) because we keep track of peer addresses between sessions, we now show information on peers that we aren't actually connected to
2) relay connections never seem to show any latencies

Also, sometimes one side of the connection will show that there is a direct conn and the other side will believe that there is only a relay connection, need to make sure that if this a bug it's fixed.

**Comment by dignifiedquire** [comment]
> This means we never actually send pings to the derp regions, so we never get a latency for the region.

netcheck does this I believe
