### ISSUE TITLE
Is there a place for general discussions

### ISSUE THREAD

**Issue by ntangldev** [n0-computer/iroh#1605]
The discord link on the website is broken, is there a place other than GitHub for asking general questions?

Q: If iroh is IPFS 2.0 do you see it integrating with FileCoin for long term block storage, or do you envisage the need for a FileCoin 2.0 built on iroh?

**Comment by dignifiedquire** [comment]
For the moment, please use https://github.com/n0-computer/iroh/discussions. We are working on fixing the discord link

**Comment by ntangldev** [comment]
Thanks, moving there
