### ISSUE TITLE
proposed `doc destroy` command & protocol for document owners telling peers to delete their replicas

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1618]
continuing work from #1460, let's explore what it means to not just delete a doc, but to tell others to remove it as well

**Comment by divagant-martian** [comment]
on scenario to think about: what happens if we send a delete and one peer that has the document comes back online afterwards? how should we handle that

**Comment by Winterhuman** [comment]
To add to this, it's probably worth providing a config option, perhaps per doc, so destroy notifications are always ignored. Mainly for archival purposes since having your node delete content that you actually wanted to keep wouldn't be ideal

**Comment by b5** [comment]
closing as stale. We should re-visit this when we re-vamp documents, _after_ shipping the willow protocol on iroh
