### ISSUE TITLE
appending `\0` aka the null byte character to keys to prevent unintended prefix deletion

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1619]
An entry w/ the key `foobar`, will get overridden by an entry with the key `foo`
However an entry w/ the key `foobar` will not get overridden by an entry with the key `foo\0`

to prevent our APIs from doing unexpected and unwanted behaviour we can either append the null byte to a key:
- at the top level API in the iroh cli / console, append the null byte as expected
- one layer down: have all api calls append and remove the null byte so that it is part of the iroh API and it is expected that we take care of this as a library
- at the document level, and append the null byte for all `set`-ing and `get`-ing needs

Regardless of where this gets implemented, we need to add some kind of `prefix` flag on all `set` and `get`-like actions that will inform us that the user *intends* to do batch work on all entries with keys underneath that prefix.

**Comment by rklaehn** [comment]
Hm, what about not doing this and instead telling users about how prefix deletion works?

Prefix deletion/replacement is a *very* useful feature if you know how to use it, and always appending a 0 byte would close this down to the user.

If we do this at all, I would have it **just** as an option of the cli / console that you can opt out of with an extra arg --raw or whatever. So for me option 1 makes most sense.

**Comment by matheus23** [comment]
Personally I think using an enum for rust APIs:
```rust
pub enum Key<'a> {
    Full(&'a [u8]),
    Prefix(&'a [u8]),
}
```

and a `--prefix` flag for CLI commands: `iroh doc set <KEY> --prefix`.

It looks like `iroh doc get` already has a `--prefix` flag, but `set` apparently doesn't.

**Comment by ramfox** [comment]
We have `path_to_key` and `key_to_path` methods that take care of this now on the CLI
