### ISSUE TITLE
Integrate temp tagging with document store

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1620]
The downloader now ensures that stuff being downloaded is not going to be deleted, by creating a temp tag at the beginning of the download and keeping it alive during the download. So the result of a successful download is now a `TempTag`.

What is missing to make things totally safe is to ensure that hashes are in the document store before the temp tag is deleted.

*Maybe this is already the case because the document gets synced before the linked content. Just need to make sure this is safe.*

CC @Frando

**Comment by Frando** [comment]
Yea, the downloads are only triggered when the actor receives insert events from the replica. So, only after entries are inserted. So this should be done already I think.
