### ISSUE TITLE
Allow to retrieve empty entries

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1627]
When you run `doc.del`, this inserts an entry in the document whose content hash is set to the blake3 hash of the empty byte string (`b""`).
When reading from the store, the current API contract is to skip these empty entries (return `None` for `doc.get_one` and skip over them in `get_many`). This is fine, because you wouldn't want to have tombstones in regular calls to `get` stuff.

However at times you will want to inspect these entries, e.g. when doing CRDT-like merges of author subspaces in an app. Therefore, we should add a flag like `include_tombstones: true` to `get_one` and `get_many` to change the behavior to *not* skip over the empty entry.

**Comment by dignifiedquire** [comment]
bikeshed: we should not call these tombstones, but maybe just empty entries

**Comment by dignifiedquire** [comment]
will be done in #1701

**Comment by Frando** [comment]
This is fixed in #1766!
