### ISSUE TITLE
Unable to connect to local magicsock by peer id

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1634]
I am writing a content tracker, using iroh-net as a library as a typical advanced user would do. I got an extremely simple request/response protocol under it's own ALPN.

https://github.com/n0-computer/iroh/pull/1595

There is a "server" mode, in which a magicsock is being created and then an accept loop, and "client" modes where a magicsock is being created and then used to connect to a server.

Here is what happens:

server
```
     Running `target/debug/examples/tracker server`
listening on PeerAddr { peer_id: PublicKey(qt5yvyw2q4garq6s), info: AddrInfo { derp_region: None, direct_addresses: {} } }
peer addr: eccpxcxc3kdqycgd2kahvfhs4lgibg3j4hoct4wf45fyue5x2limoaaa
```

client
```
     Running `target/debug/examples/tracker announce --host eccpxcxc3kdqycgd2kahvfhs4lgibg3j4hoct4wf45fyue5x2limoaaa --ticket ealcoyhcjxyklzee4manl3b5see3k3nwekf6npw5oollcsflrsduiaicaiambkabrxcfoacsjt2xnrcxagni6ibrvsllizo6vajvupelumo6cve6sdzs2ur4kbjmbkl6fpxzcaa`
trying to connect to PeerAddr { peer_id: PublicKey(qt5yvyw2q4garq6s), info: AddrInfo { derp_region: None, direct_addresses: {} } }
Error: failed connecting to provider
```

Shouldn't this always work? Both the server and the client learn at least their **local** address, exchange it via the derper, and then connect to each other? There is no advanced stuff such as hole punching needed, just a magicsock finding out it's own *local* addr and exchanging that via the derper.

Note that when I restart the server it works. The server now is able to figure out it's own local address, puts it in the ticket, and the client can connect directly by ip addr.

server
```
listening on PeerAddr { peer_id: PublicKey(t6r2tzqkrmxgwxsx), info: AddrInfo { derp_region: Some(2), direct_addresses: {82.76.245.118:44204, 192.168.1.141:44204} } }
peer addr: ecp2hkpgbkfs4226k7crgnulowun2ntflc7uxv2svzym3enkelz6qaicaiafethvo2wnsaqaycuaddnm3eba
got connecting
got announce: Announce { peer: PublicKey(cytwbysn6cs6jbhd), content: {HashAndFormat { hash: Hash(9a8f2031ac96b465dea8135a3c8ba31de1549e90f32d523c5052c0a97e2bef91), format: HashSeq }}, kind: Complete }
```

client
```
     Running `target/debug/examples/tracker announce --host ecp2hkpgbkfs4226k7crgnulowun2ntflc7uxv2svzym3enkelz6qaicaiafethvo2wnsaqaycuaddnm3eba --ticket ealcoyhcjxyklzee4manl3b5see3k3nwekf6npw5oollcsflrsduiaicaiambkabrxcfoacsjt2xnrcxagni6ibrvsllizo6vajvupelumo6cve6sdzs2ur4kbjmbkl6fpxzcaa`
trying to connect to PeerAddr { peer_id: PublicKey(t6r2tzqkrmxgwxsx), info: AddrInfo { derp_region: Some(2), direct_addresses: {82.76.245.118:44204, 192.168.1.141:44204} } }
connected to [fd15:70a:510b::]:12345
opened bi stream
sending announce
```

**Comment by rklaehn** [comment]
I thought that maybe it just takes some time to figure out it's own addr. But this is not the case. Even if I let the server sit there for a long time before attempting to connect, connecting by peer just does not work:

server
```
listening on PeerAddr { peer_id: PublicKey(v766dtdr4jkcbmeo), info: AddrInfo { derp_region: None, direct_addresses: {} } }
peer addr: ecx73yomohrfiifqryda5ocan5wxcmf5bdx6ozf2toebaxxpybafwaaa
```

client (after 5 minutes)
```
     Running `target/debug/examples/tracker announce --host ecx73yomohrfiifqryda5ocan5wxcmf5bdx6ozf2toebaxxpybafwaaa --ticket ealcoyhcjxyklzee4manl3b5see3k3nwekf6npw5oollcsflrsduiaicaiambkabrxcfoacsjt2xnrcxagni6ibrvsllizo6vajvupelumo6cve6sdzs2ur4kbjmbkl6fpxzcaa`
trying to connect to PeerAddr { peer_id: PublicKey(v766dtdr4jkcbmeo), info: AddrInfo { derp_region: None, direct_addresses: {} } }
Error: failed connecting to provider

Caused by:
    timed out
```

it's as if the server either figures out it's addr before the first accept call, or not at all.

**Comment by rklaehn** [comment]
I did a slight modification. The server has a 10s delay before the first call to accept. It seems that this way it will know it's own addr at that time most of the time. But the ticket does *not* contain the addrs, but just peer id (and I am using a hardcoded region id). Then it works.

One explanation would be that if I don't have the delay the server has not figured out it's own derp region. The ticket does not contain a derp region, and the client can't do anything to dial (no derp region -> no derp, no addrs -> no direct dial attempts).

So maybe we need a reliable way for a node to wait until it has figured out it's own derp region. But what we really want is the ability to dial by peer.

The derp region is just an integer. We can keep track of the derp region of 10 000 000 users for about 0.50 EUR of AWS costs, or alternatively with a Pi4 running in my attic. But the user should not have to deal with this...

**Comment by rklaehn** [comment]
See https://github.com/n0-computer/iroh/issues/1248

**Comment by dignifiedquire** [comment]
The latest version on `main` has fixed most observable issues here. Please reopen or open a new issue if it persists.
