### ISSUE TITLE
Persistent identity on the level of magicsock

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1637]
There is almost nothing that p2p systems hate more than constantly changing peer ids. They spam DHTs and peer tables, waste a lot of resources, and in general create havoc.

Unfortunately the easiest way to write a little test program or a short lived node is to generate a random peer id. What if we make it convenient to work with persistent peer ids even at the magicsock level, by having a fn to get or create a secret key from the file system, and then use that in every example?

**Comment by dignifiedquire** [comment]
like https://github.com/n0-computer/iroh/blob/14c4497309b084c06f7be185b3297fd99dfc1f90/iroh/src/util/fs.rs#L139 ?

**Comment by rklaehn** [comment]
Yeah, I did not know this one. Maybe it should be directly on SecretKey and do the entire load or create dance.

```rust

    /// Load a [`SecretKey`] from a file, or generate a new one if the file does not exist.
    pub fn load_or_generate(path: impl AsRef<Path>) -> anyhow::Result<Self> {
        let path = path.as_ref();
        if path.exists() {
            let mut file = std::fs::File::open(path)?;
            let mut buf = Vec::new();
            file.read_to_end(&mut buf)?;
            let key = SecretKey::try_from(&buf[..])?;
            Ok(key)
        } else {
            let key = SecretKey::generate();
            std::fs::write(path, &key.to_bytes())?;
            Ok(key)
        }
    }
```

**Comment by rklaehn** [comment]
Ah, yes, that is exactly what I was after on closer look.

**Comment by rklaehn** [comment]
Maybe this should be directly on SecretKey to make it more discoverable?

**Comment by dignifiedquire** [comment]
sure
