### ISSUE TITLE
Do not eat memory when using documents

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1643]
The current code seems to load `values` in documents entirely into memory, even when the content is only added and read in a streaming fashion.

**Comment by Frando** [comment]
This is a known issue to me with `client.docs.set_bytes`, but wouldn't know of other places where this happens?

**Comment by dignifiedquire** [comment]
if you look #1645 I made a tests that does not use any of the buffering APIs, and that still blows up to almost 1GiB memory usage (adding a value of 512MiB)

**Comment by dignifiedquire** [comment]
Closing as stale
