### ISSUE TITLE
ignored gc tests are not executed in CI and do not compile

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1644]
https://github.com/n0-computer/iroh/blob/main/iroh/tests/gc.rs#L474-L477

is broken and breaks compiling when building tests in release mode

**Comment by rklaehn** [comment]
I will fix this. But why are tests not run in release mode at all in CI?

**Comment by rklaehn** [comment]
https://github.com/n0-computer/iroh/pull/1649 fix
