### ISSUE TITLE
console: `blob download --ticket <ticket for a collection>` shows transfer size as 0

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#1655]
on 53b0bb0

`blob download` for a collection shows a transfer size of 0. 
This prevents progress bars from updating correctly, as well and remaining time

**Comment by rklaehn** [comment]
This works for get to file, but not for get to dir and blob download (which is using the same code I think)

**Comment by rklaehn** [comment]
https://github.com/n0-computer/iroh/pull/1658
