### ISSUE TITLE
Proposal: Document Views

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1667]
I've had time to play with iroh a bunch now that prefix-based deletion is in, and I must say, it's been very fun learning how iroh works 😜. With that said, I think prefix deletion _and_ author ID's as key prefixes are too much for a user to get their head around on first go. As a user when I hear "key value store", I expect all keys to be unique _based solely on the key I provide_.

We have some new UI that at least illustrates the problem:

<img width="990" alt="Screenshot 2023-10-18 at 12 30 43 PM" src="https://github.com/n0-computer/iroh/assets/1154390/66dc5559-ef0b-4ccb-86e0-59d6de858c7b">

In this example there are two `foo` keys in the same document, because they have different authors. What's more, because I am neither of these authors, I cannot edit these keys, which is super confusing. As someone who works at n0, I fully understand why I can't edit stuff in someone else's subspace, so I'm not advocating we change anything about the way iroh works, instead I want a new "views" feature that gives me a "merged" view of the document, which is a union of all known replica keys, using timestamps to break ties.

Iroh is missing a true "shared" view of a document. I need this ASAP because it's too hard to introduce users to both the author-replica thing _and_ the prefix thing at the same time. I think the right answer is to start with teaching prefix deletion, but have the default display be this merged view that will feel like a true key-value store. That shared view will naturally invite the "but wait, just anyone can edit the db!?" question, which will open us up to talk about how there are ways to change the view to match individual authors, or the full-blast "all" view.

## Views
The term view here means "view" in the classical database sense:

> a [view](https://en.wikipedia.org/wiki/View_(database)) is a virtual [table](https://en.wikipedia.org/wiki/Table_(database)) representing the result of a [database](https://en.wikipedia.org/wiki/Database) [query](https://en.wikipedia.org/wiki/Information_retrieval).

We already have the concept of _filters_ which perform largely the same function, but co-mingle querying with views:

https://github.com/n0-computer/iroh/blob/8169053a0605f848ac3bade7b09833b4636333a6/iroh-sync/src/store.rs#L141-L155

I think the `All` and `Author` are views, with `Key` being an implicit query on the `All` view, `AuthorAndPrefix` is an implict query on the `Author` view.

## Merged View
A merged view takes the following steps:

1. construct the union of all entries across all authors, sorting by `key` field
2. construct the union of entries based on the `key` field. last-writer wins for conflicts on the key field, lexographic sort of `author_id` wins in the event of equal `key` & `timestamp` fields.
3. apply prefix deletion to the remaining keys, again using timestamps to break ties.

I'm sure the algorithm could be better. This is just how my dumb brain expresses "I want unique key fields, last-writer-wins, regardless of author"

## Proposal:
* remove the concept of `filters`, split them into `queries` and `views`
* There are three views: `all` (all keys from all authors), `author` (only keys from one author), and `merged` (all keys in one space)
* "merged" becomes the new default view
* APIs are updated with a `--view` flag

**Comment by dignifiedquire** [comment]
My first pass at how I think this can look for the first round: https://gist.github.com/rust-play/0cda7cc7eee6787ce9904742d154d89e
