### ISSUE TITLE
console:  start node in background

### ISSUE THREAD

**Issue by eminence** [n0-computer/iroh#1671]
This is a small feature request:  It would be useful if the `console` command could optionally start a node in the background.   It would save me from having to run `iroh start` in another terminal :)

**Comment by b5** [comment]
That would be very nice indeed 😄. Off the top of my head, we could add a `--start` flag to `iroh console` that starts a node if one isn't already running.

We're trying to strike a careful balance of slowing folks down _just enough_ to make them aware that iroh needs a long running process for most things, so I don't think we'd want to make the start flag default to being on. We could also include the short flag so it'll be a quick

```
$ iroh console -s
```

Feels right to me. Others want to weigh in?

**Comment by eminence** [comment]
An off-by-default flag sounds perfectly fine to me.   In order to remind people that a background server is started, you could print a loud "Starting temporary node" / "Stopping temporary node" when the console is started/stopped

**Comment by dignifiedquire** [comment]
Yeah I think having a `--start` flag makes sense.

**Comment by dignifiedquire** [comment]
This was added in https://github.com/n0-computer/iroh/pull/1802
