### ISSUE TITLE
iroh-bytes: listing operations need pagination arguments

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#1676]
hey @rklaehn, can I haz `offset` and `limit` args on all these plz? my frontend UI is choking b/c my node has 40k+ blobs
https://github.com/n0-computer/iroh/blob/a93e89e9c84e757823bfec089dc92110a46aa33d/iroh/src/client.rs#L342-L364

cc @ramfox, this will affect FFI args.

**Comment by b5** [comment]
update: these should be done as queries after we figure out #1667

**Comment by dignifiedquire** [comment]
this is part of #1766

**Comment by dignifiedquire** [comment]
this was not part of #1766, but can be done using stream modifiers `skip` and `take`.
