### ISSUE TITLE
Why derp regions instead of derper urls?

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1681]
One thing I don't like very much about the whole derper concept is that the derp regions are identified by ids, where the exact meaning is defined in a local config file.

Derp region ids are not self contained.

So I can have a situation where two peers can't talk to each other because they have a different mapping from derp region id to derper url.

And you have to do weird things like defining a derp region 65k for the test derper.

I am not that familiar with the code, but looking at it it seems that using an url would not make things fundamentally slower. The messages flowing over the derper don't even contain region ids.

One downside would be that the discovery records would become a bit larger, but really nothing out of the ordinary.

Discovery is one of the reasons I am raising this issue. It seems weird to put ids instead of urls into a global dht, and then rely on the mapping to be the same on each participating node.

**Comment by ramfox** [comment]
There can be many derpers per region, all of which have the same region id.

Each iroh node needs to only be connected to a single derper per region, in order to have a way to relay packets to any other iroh node that is also connected to some derper in the region. 

All of the derpers in a single region are meshed, and can act as packet forwarders for each other. Two nodes do not need to be connected to the same derper to connect, they just each need to be connected to nodes in the same region.

We currently only have a single derper per region right now, so it makes all the indirection confusing!

**Comment by rklaehn** [comment]
But couldn't you accomplish the same with a region url? Basically you have an url that has multiple servers behind it, like basically any big site.

Here is my concern: Currently a discovery record would look like this:

```javascript
{
   peer_id: DEADBEEF1234...,
   region_id: 5
   direct_addresses: [
     67.31.84.123:12345,
     96.45.111.356:12345,
   ]
}
```

The problem with this is that discovery records only work for nodes that have the exact same derpmap config.

Now imagine there is a peer that does not want to use n0 derpers for some reason. Maybe legal reasons, maybe performance reasons, maybe they are just on a separate derper network. They can not publish a discovery record that makes them discoverable.

If a discovery record would look like this, all the problems would be solved:

```javascript
{
   peer_id: DEADBEEF1234...,
   derper: "https://eu1.derp.iroh.network",
   direct_addresses: [
     67.31.84.123:12345,
     96.45.111.356:12345,
   ]
}
```

Then somebody else could publish a record like this, and it would become dialable from a node that uses our derpers:

```javascript
{
   peer_id: FADEBABE1235478...,
   derper: "https://derp.somecompany.com",
   direct_addresses: [
     33.31.84.123:12345,
     44.45.111.356:12345,
   ]
}
```

**Comment by rklaehn** [comment]
If I understand it correctly, the meshing between multiple derpers is purely to be able to handle a large load. It is meant to be a single entity, so it can easily be hidden between a single url that resolves to multiple ip addresses.

**Comment by flub** [comment]
I agree that a URL would solve a lot of problems with the region IDs.  Region IDs make it difficult to be a fully federated network.

**Comment by dignifiedquire** [comment]
> I agree that a URL would solve a lot of problems with the region IDs.

They also introduce the issue,  that a single region now can't be served by multiple hosts, eg two different datacenters, because you have to proxy them through the same URL.

There is also a practical concern, the region ids are short `u16`s, and they are sent around in many places, if we move to URLs this gets quite painful and much larger in many places.

**Comment by dignifiedquire** [comment]
It is also simpliy not true that you need the same configuration of derpers to be able to connect, you only need to match on the derpers you actually use. Which is no different than what you are proposing. You could simply make your records look like this

```
{
   peer_id: DEADBEEF1234...,
   region_id: 5,
   url: "https://eu1.derp.iroh.network",
   direct_addresses: [
     67.31.84.123:12345,
     96.45.111.356:12345,
   ]
}
```

Which would allow nodes to continue to use the region_id but also check if they have a matching url to this and choose if they want to use this one for the region.

**Comment by Frando** [comment]
> They also introduce the issue, that a single region now can't be served by multiple hosts, eg two different datacenters, because you have to proxy them through the same URL.

This can be solved through DNS, can't it? We can add multiple A or SRV records, and then the client round-robins or randomly choses one.

> There is also a practical concern, the region ids are short u16s, and they are sent around in many places, if we move to URLs this gets quite painful and much larger in many places.

This is true. We might want to do something similar to #1673, to have a global cache to map URLs to integers.

The single downside of URLs is IMO that tickets that include the full peer info get longer. I think the best solution for this is to add something like PKARR to iroh, so that peers can be adressed by peer id only.

**Comment by b5** [comment]
A few questions:

Just so I’m clear on the impact of this decision, we need region identifiers (and maybe these proposed region URLs) on _every new peer dial_, correct?

Am I also correct in understanding that the primary propose of the `u16` is to map areas of lower latency that roughly match geographies on planet earth? Would we benefit from predefining what those regions are?

it seems to me we have two cross-cutting concerns. Federation & “latency hinting”

**Comment by rklaehn** [comment]
> They also introduce the issue, that a single region now can't be served by multiple hosts, eg two different datacenters, because you have to proxy them through the same URL.

Can't you have multiple IP addresses for a single domain? Or alternatively hide multiple servers behind a single ip address? Whenever I talk to some large website that has a single hostname I am not talking to a single machine but to an entire datacenter, or even multiple data centers depending on location.

> There is also a practical concern, the region ids are short u16s, and they are sent around in many places, if we move to URLs this gets quite painful and much larger in many places.

I don't think the region id is sent around in that many places. It is not part of the derp protocol itself. The only place where it would make an user visible difference is the ticket. Other than that, internally you would have something like an `Option<Arc<String>>` (8 bytes) instead of an Option<u16> (4 bytes). Most of the time you treat the string as an opaque identifier, so other than that it is no longer Copy it won't make a difference.

**Comment by rklaehn** [comment]
> in regards to sth like pkarr, while that is a cool project, I think it is not a good idea to ship iroh by default with a dependency on bittorrent
> this is politically just too complicated
> it's also sth that is regularly blocked in networks by default

I don't want to require a bittorrent dependency. The way it would work is that n0 would operate a discovery service that is centralized but conceptually easy to decentralize. Basically like https://github.com/n0-computer/iroh-discovery-cloudflare-worker or something more efficient. HTTP PUT and GET.

People could then decide with a one line code change or a feature flag to use the mainline DHT, but it would never be the default.

Operating the discovery service would be a tiny fraction of the effort of operating the relay network in terms of traffic. Maybe it could even be integrated.

**Comment by rklaehn** [comment]
Two more things:

1. I really care a lot about dial by peer. If I have to provide *any* extra information, I might as well have to provide an ip address, which makes it lose a lot of the simplicity. Every line of code that is written by iroh-net users to deal with region ids is complexity that really should be our job to handle.

2. We don't have to decide this right now. I can do dial by peer using region id for now. The records in the discovery system have a TTL, so if we change the format it would just mean that old versions of iroh would no longer understand the new records and everybody would have to upgrade.
