### ISSUE TITLE
`PeerMap` invariants don't hold 

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1703]
This `debug_assert` in `Endpoint::receive_ip`  triggers reliably for me on tests with many nodes:

```rust
 // the peer map maintains consistency
        let Some(state) = endpoint.direct_addr_state.get_mut(&ip_port) else {
            debug_assert!(false, "peer map inconsistency by_ip_port <-> direct addr");
            return None;
        };
```
https://github.com/n0-computer/iroh/blob/main/iroh-net/src/magicsock/endpoint.rs#L1417

**Comment by matheus23** [comment]
This issue seems stale. I can't find the original code, it got reworked.
Should someone still find a similar issue, they should open another one :v:
