### ISSUE TITLE
`iroh tag list` doesn't check if you have a running iroh node

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1727]
we should check each command to ensure we have the proper checks!

**Comment by divagant-martian** [comment]
I gave this a try and I got:
```
Error: Iroh node is not running

Caused by:
    deadline has elapsed
```
what are you seeing/ how are you getting it?

**Comment by ramfox** [comment]
this happened during a dogfooding, the command just hung. Could have been some other interaction, or maybe it was fixed already!
