### ISSUE TITLE
`iroh tag` API design review

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1728]
we need to look at the `iroh tag` api and see what else should be added or adjusted to make it useful

**Comment by dignifiedquire** [comment]
Proposal for operations (per tag type)

- `list()` (list all tags available
- `get(tag)` get the thing that the tag points to
- `delete(tag)` delete the mapping (not the thing that is pointed at
- `set(tag, value)` store a new mapping (this does not require `value` to already exist locally

**Comment by rklaehn** [comment]
I am very much in favour of allowing arbitrary byte sequences for tags.

For CLI use you will almost always want this to be utf8 strings. But for programmatic use making things utf8 is very limiting in some cases. E.g. you got something like a u64 id, a composite key, or a blob as your "name". Then you would have to somehow stringify the key to be able to use it as a name.

I think we can make things very convenient in the CLI under the assumption that tags will be utf8 strings most of the time while still allowing non uft8 keys for programmatic use.

**Comment by dignifiedquire** [comment]
Should there be a length limit on the the tag name? If so, what should it be?

**Comment by b5** [comment]
I'm always a fan to defaulting to the (effective) maximum length of a URL: https://stackoverflow.com/a/417184, which the most conservative one is ~2048 _characters_

**Comment by ramfox** [comment]
closing as stale
