### ISSUE TITLE
ticket versioning

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#1732]
couple of us have mentioned versioning recently. This has been discussed in the context of tickets mainly. 
Some notes to start:
Tickets are transferred in two ways: human representation and bytes representation. The bytes representation could be considered part of the rpc protocol

Questions to answer:
-  [ ] do we version the human representation? how do we version it?
-  [ ] do we version the bytes representation? how do we version it?
-  [ ] what's the relationship between the human representation version and the bytes representation version (note that currently human repr depends on bytes repr)
- [ ] what's the relationship of the bytes repr version with versioning the rpc protocol itself
- [ ] what do versions actually look like? single increasing major? semver? answering this needs to take into account the previous questions

**Comment by rklaehn** [comment]
I would only version the human representation. The bytes representation of a ticket only appears as a part of a larger protocol, and in that case we will just version the overall protocol using the ALPN.

**Comment by rklaehn** [comment]
I added a versioning, or rather variant, approach now.

Variant because you might have different variants that are equally valid.
