### ISSUE TITLE
ffi bindings panic on `DocInner::drop`

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1747]
After creating a `Doc` in the ffi bindings, the code panics on `Drop`:

```
thread 'node::tests::test_doc_new' panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/iroh-0.8.0/src/client.rs:535:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

running the iroh-ffi tests narrow it down the issue to the Drop impl on `DocInner`, specifically where we spawn a tokio task:

https://github.com/n0-computer/iroh/blob/2d292e30b41e557c03ddbab9f2bd73942af82e78/iroh/src/client.rs#L528C1-L539C2

I tried adjusting this by getting the `tokio::runtime::Handle` and spawning off of that, but it gave the same error.

**Comment by dignifiedquire** [comment]
fixed in https://github.com/n0-computer/iroh/pull/1758
