### ISSUE TITLE
Usability issue with new tickets in terminal

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1748]
So, the new tickets have a prefix. But that prefix is separated by the main part by a non letter or digit character. So now you can't click on it anymore to copy and paste it into another terminal.

Remember when these were base64 and we had lots of issues with the non letter or digit chars? This is not quite as bad, since at least there aren't symbols that will completely irritate a shell (except maybe windows where : is the drive letter separator `C:\Program Files\...`).

So, can we make the separator a char that is accepted by the terminal? `_` would work I guess, or just no separator at all?

**Comment by rklaehn** [comment]
@b5 comments?

**Comment by rklaehn** [comment]
selection just a char seq:
![selecting_before](https://github.com/n0-computer/iroh/assets/248257/f34db75c-e452-4d43-aa4b-f0410d9be9cb)

selecting including the prefix:
![selecting_after](https://github.com/n0-computer/iroh/assets/248257/a2b11626-b500-4d62-9b16-01617be60cc9)

**Comment by b5** [comment]
I brought this up in review: https://github.com/n0-computer/iroh/pull/1711#discussion_r1372079744, but was overruled in chat by other for what I understand are two reasons:

1. aesthetics.
2 the belief that this prefix makes tickets in to URIs.

I'm very much the type to prefer pretty things wherever possible, but in this case the usability is indeed quite frustrating. As for the URI issue, imho regardless of weather something is technically a URI, it isn't a URI unless is starts with a scheme (eg `iroh://`).

I think we should change form `:` to `_`, and would like to hold off on a release until we do
