### ISSUE TITLE
feat: allow adding content that is not fully materialized

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1759]
For example when generating a backup.
The whole file never exists outside of iroh, but rather it should be streamed into iroh, piece by piece and at the end be stored by iroh (on disk or in memory) but without the user having to fully have it in memory or on disk at any point in time.

**Comment by rklaehn** [comment]
I don't quite understand this. How can it be neither on disk nor on memory?

Currently you can write into a file, then add this file either by reference or by reflink (on a FS that supports it), which is 0 overhead. What more do you want?

**Comment by rklaehn** [comment]
Looking at the store api, there is import_bytes to import a single `Bytes`, import_stream to import a stream of `Bytes`, and import_reader which is implemented in terms of the former usually.

They don't really do anything incrementally right now, but just create the file as a temp file and then compute an outboard and change it to a permanent file. But in principle they could.

I see that in the API there is this:

- https://docs.rs/iroh/latest/iroh/client/struct.BlobsClient.html#method.add_from_path
- https://docs.rs/iroh/latest/iroh/client/struct.BlobsClient.html#method.add_reader
- https://docs.rs/iroh/latest/iroh/client/struct.BlobsClient.html#method.add_bytes

In the store API there are these 3 but also

- https://docs.rs/iroh-bytes/0.9.0/iroh_bytes/store/trait.Store.html#tymethod.import_stream

Should we just expose the one below as well and be done with it?

**Comment by dignifiedquire** [comment]
Sounds good, lets just have parity 👍 and yes seems that the basic functionality I was looking for is already there
