### ISSUE TITLE
`BlobAddOutcome` always returns with `size == 0` for `store::flat::import_stream`

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1768]
The higher order accumulators that do the translation between `ImportProgress` and `AddProgress` expect `ImportProgress::Size` to be sent in order to calculate the size for `BlobAddOutcome`, but the `store::flat::import_stream` never sends `ImportProgress::Size`

The `mem` version seems to do this correctly.

**Comment by dignifiedquire** [comment]
I suspect this is fixed with #1778 @ramfox can you please retest/describe how you tested this?

**Comment by ramfox** [comment]
This has been fixed!
