### ISSUE TITLE
when starting check for other instances

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#177]
UX wise people might experience odd behavior if they try to run multiple instances of `iroh` or already have `kubo` running. Should make sure we are either compatible with that setup or error out gracefully.

**Comment by b5** [comment]
we're hammering out that issue in https://github.com/n0-computer/iroh/issues/274#issuecomment-1267166971

**Comment by b5** [comment]
Also related: https://github.com/n0-computer/iroh/pull/231
