### ISSUE TITLE
add content-addressed data endpoint to iroh.network

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1777]
See discussion in https://discord.com/channels/949724860232392765/1119027107201286214/1171415290492489818 etc.

```
Yep. I vote we do this. Endpoint should be GET /api/blobs/:hash 
```

**Comment by rklaehn** [comment]
We now got the gateway in https://github.com/n0-computer/iroh-examples/tree/main/iroh-gateway , see https://github.com/n0-computer/iroh/issues/1776

All that would have to be done is to copy over the code. It is also using axum.

**Comment by dignifiedquire** [comment]
We won't be expanding the scope of iroh.network for now
