### ISSUE TITLE
Import & export files and directories directly into docs

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1781]
## High-level feature

We want to support exporting and importing files and directories into documents. This should be directly from the `Doc` client, e.g. `doc.import_from_path()` and `doc.export_to_path()`.

### Exporting from docs

What we miss (and will want anyway) is `blobs.export_to_path` in client, rpc and node - this should be straightforward to add though. Exporting a "path tree" from a document can then simply be done on the client level in a `export_to_path` function that runs a query and exports each entry's content hash.

### Importing into docs

We already support importing files and directories recursively directly into the `iroh_bytes` blobs store through `client.blobs.add_from_path()`.  

We also already support setting document entries directly to hashes. However this is not enough, because all blobs added through `client.blobs` are tagged (either with a manual tag or an auto tag) and this is not wanted for blobs added to documents, as it will prevent garbage collection to delete blobs once their document entry is deleted or overwritten.

I see two ways to solve this:

**Exposing tempt tags to the client** - `blobs.add_from_path` iterates over a file tree and imports each file and gives them a temporary tag. At the end the collection itself is tagged and the temporary tags are deleted. What we could do is to add an option to omit the final step and instead keep the temp tags and return the tags over the RPC. The client could then return a stream of temp tags to drop once the hashes are added to the document. The node should drop the temp tags by itself maybe after a timeout if the RPC client did not return them (e.g. because it died) so that those blobs would be deleted and not lie around dangling (unreferenced).

The upside is that this mechanism might be useful for other usecases as well - I can imagine people wanting to add blobs incrementally over some time, and then add something that references them once the operation finishes (doc or collection) - not necessarily only blobs in a single directory tree. The downside is that it will likely involve some work to keep track of the temp tags. @rklaehn can likely tell more. 

**Add `DocImportFromPath` to the RPC** - this would be the alternative, basically copy the BlobAddFromPath rpc methods to to `DocAddFromPath` and implement likewise. Then the question of temp tags can be handled in the node, in the same way as we already do for blob trees.

### The magic last byte

Because we employ Willow's model of prefix deletion, path-like usecases of docs need to terminate leaf (non-directory) entries with a character that is otherwise invalid in the path, so that importing `somef` does not delete `somefile`. A simple way might be to just add a nul byte to the path. However, apps might have different needs (e.g. use these suffix for more info - append the mime type? add some id?). So I was thinking that maybe we should support passing a callback that converts from file path to key for import, and from key to file path for export.

### API

... could e.g. look like this

```rust
impl DocClient {
    fn import_from_path(&self, author: AuthorId, path: Path, path_to_key: impl Fn(Path) -> Bytes) -> impl Stream<Item = Progress>{}
    fn export_from_prefix(&self, query: Query, key_to_path:  impl Fn(&[u8)) -> PathBuf)  -> impl Stream<Item = Progress> {}
}
``

**Comment by ramfox** [comment]
In a convo with dig this morning he mentioned wanting to limit the import and export to a single file right now, to side step having to deal with usecase specific directory handling:

```
impl DocClient {
    fn import_file(&self, author: AuthorId, path: Path, path_to_key: impl Fn(Path) -> Bytes) -> impl Stream<Item = Progress>{}
    fn export_file(&self, key: impl AsRef[u8], key_to_path:  impl Fn(&[u8)) -> PathBuf)  -> impl Stream<Item = Progress> {}
}

// helper functions
fn path_to_key(path: Path) -> Bytes
fn key_to_path(impl AsRef<[u8]>) -> PathBuf
```

**Comment by ramfox** [comment]
Unless there is some objection, I'll be implementing this by adding `DocImportFromPath` to the RPC.

**Comment by rklaehn** [comment]
On the subject of exposing temp tags: I think they are a bit difficult to work with over a RPC boundary. They rely on refcounting, so you would have to have some kind of cross process refcounting scheme. These things always end up being a bit of a pain.

I think temp tags as they exist now are best kept for when you are in the same process. We definitely don't want to make normal temp tags more complex, so you would end up having 2 different kinds of temp tags, the private ones and the API ones...
