### ISSUE TITLE
Range request helper fns

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1784]
Currently the only way to take advantage of the advanced features of bao-tree such as range requests or multi range requests is to
use iroh-bytes directly, specifically the get state machine.

This is nice and powerful, but really not very convenient.

- [ ] provide async helper fns in get that drive the state machine and produce some kind of result, without having to manually drive the fsm
- [ ] provide API for range requests that works via the iroh bytes client

Number 1 is pretty straightforward. Number 2 requires some thinking, since there are a lot of different scenarios, and we don't want to completely bloat the iroh bytes client.

For 1 there is even some stuff in tests that can just be upgraded to public API.

**Comment by dignifiedquire** [comment]
@rklaehn this is superceeded by #2014, right?
