### ISSUE TITLE
Long tests with panics

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#1785]
Observed here https://github.com/n0-computer/iroh/actions/runs/6810483845/job/18518873627?pr=1783 for `tests (default features). 
The batch for `  Running unittests src/lib.rs (target/debug/deps/iroh_net-c06f3d135f6f57bb)` takes 5 min alone and spits a bunch of logs and traces along the way.

**Comment by dignifiedquire** [comment]
```
 39: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/runtime.rs:348:47
  40: iroh_net::derp::http::tests::test_http_clients_and_server
             at ./src/derp/http.rs:137:9
  41: iroh_net::derp::http::tests::test_http_clients_and_server::{{closure}}
             at ./src/derp/http.rs:56:48
```

**Comment by dignifiedquire** [comment]
we have other issues tracking test failures, so closing this for now
