### ISSUE TITLE
bug: `BlobListCollectionsResponse.total_blobs_size` is always `None`

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1791]
seems we always set it to `None` rather than try to calculate the size:
https://github.com/n0-computer/iroh/blob/53f1b616c75bcc81c1b7493a4365c22340989a5d/iroh/src/node.rs#L894

We should either attempt to calculate it, or remove the field entirely.

**Comment by dignifiedquire** [comment]
@rklaehn what's the plan here?

**Comment by dignifiedquire** [comment]
ping @rklaehn
