### ISSUE TITLE
When will the deficiencies in the api documentation be completed and when will methods that can be used in the console but not in the programming language be available?

### ISSUE THREAD

**Issue by unicornlox** [n0-computer/iroh#1815]
There is no blob example with go and rust in the api documentation, and when will new author creation and author switching methods be available for go and rust?

**Comment by ramfox** [comment]
Hi hi!

Glad to hear you are interested in working with iroh! I've been grinding away at exactly this for the last few weeks.

All actions that can be taken by the console can now also be done programmatically in rust, python, golang, and swift!

For rust, we have a (`0.11.0` release)[https://github.com/n0-computer/iroh/releases]

For python, we currently have a (`0.11.0-alpha` release)[https://pypi.org/project/iroh/#history]

For golang and swift, you would currently need to build from source [here](https://github.com/n0-computer/iroh-ffi]

My priority over the next two weeks is to get official releases for python, go, and swift up, as well as fixing up the documentation site.

To answer your specific question about author creation, though, take a (look at this golang code)[https://github.com/n0-computer/iroh-ffi/blob/main/go/main.go] to see how to create a node, doc, and author.

**Comment by unicornlox** [comment]
@ramfox  Thank you very much for your reply, I follow the developments with interest.

**Comment by ramfox** [comment]
Hi there! Sorry that I missed this. Hopefully you found this much earlier, but our docs now show how the console commands are done in rust.

https://www.iroh.computer/docs/api

Thanks!
