### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#1823]
make `ControlMsg` public

We had previously had "doc.open" and "doc.close" mimicking a file descriptor: "opening" won't open any network connections. 

`DocsClient::import` should become `DocsClient::join`

`Entry` -> becomes an "entry client", that can get data from the entry, rather than having to go back to the doc

**Comment by dignifiedquire** [comment]
@ramfox what's the status here?

**Comment by ramfox** [comment]
closed as stale
