### ISSUE TITLE
listening on ipv6

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#1836]
While removing the start `addr` option I noticed there is actually no way to have an ipv6 listening endpoint since the default address is ipv4, without option to change it. Before removing it it was ignored so also not working by then. At some point we should decide if we care about listening on ipv6 and enable options to configure this. At time of writting, this is probably not the time tho.

Related #1830

**Comment by dignifiedquire** [comment]
we bind to both ipv4 and ipv6 if we can: https://github.com/n0-computer/iroh/blob/main/iroh-net/src/magicsock.rs#L2378-L2393
