### ISSUE TITLE
iroh-bytes should have an upper limit for number of downloads it accepts 

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1838]
If too many downloads are already in progress new requests should fail with a loadshed response.

**Comment by rklaehn** [comment]
This is reasonably easy to implement in the server - just a counter. But any idea what this limit should be? A server that serves a lot of slow clients might want to have a very high number.

**Comment by dignifiedquire** [comment]
should this be handled by integrating the downloader from iroh?

**Comment by rklaehn** [comment]
> should this be handled by integrating the downloader from iroh?

Probably good idea.

**Comment by flub** [comment]
Is this still an independent issue or can it be closed as iroh-sync now handles all sorts of sophisticated downloading ways?
