### ISSUE TITLE
Publish iroh 0.4.2 to crates.io

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#1849]
I am currently using maint-0.4 branch, would be nice to switch to crates.io: https://github.com/deltachat/deltachat-core-rust/commit/9e7e172a7ba47aa7e6dc4d17645234989f0ce0b5

Related merged PR: https://github.com/n0-computer/iroh/pull/1821

**Comment by dignifiedquire** [comment]
@flub is that ready for publishing?

**Comment by flub** [comment]
Oh, yes we can publish this.  I got confused and thought we wanted to land a new version of iroh-blake3 in here as well, but this only depends on the upstream blake3.

**Comment by dignifiedquire** [comment]
will publish tonight or tomorrow

**Comment by dignifiedquire** [comment]
published
