### ISSUE TITLE
Upgrade all dependencies to hyper 1.0

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1863]
Since https://github.com/n0-computer/iroh/pull/1858 we use hyper 1.0.  Which means we currently have hyper duplicates in our dependency.

This is a tracking issue to get all our dependencies upgraded:

- https://github.com/dariusc93/rust-igd/issues/4
- https://github.com/seanmonstar/reqwest/issues/2039
- https://github.com/hyperium/tonic/issues/1579

**Comment by flub** [comment]
This can be finished now, igd-next has a new release depending on hyper

**Comment by dignifiedquire** [comment]
missing https://github.com/n0-computer/quic-rpc/issues/79

**Comment by flub** [comment]
> missing [n0-computer/quic-rpc#79](https://github.com/n0-computer/quic-rpc/issues/79)

Not really, that feature is not used in iroh...
