### ISSUE TITLE
gc_flat_partial test is flaky

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1875]
I'm not sure if the code itself is flaky or whether this is a race introduced in the filesystem use.

https://github.com/n0-computer/iroh/actions/runs/7167046091/job/19512351881?pr=1874

**Comment by dignifiedquire** [comment]
https://github.com/n0-computer/iroh/actions/runs/7182264909/job/19558377720

**Comment by flub** [comment]
Seems like all the gc tests are affected: https://github.com/n0-computer/iroh/actions/runs/7182264909/job/19558377720

**Comment by dignifiedquire** [comment]
using `cargo nextest` it is much easier to reproduce, had it almost always fail on CI boxes

**Comment by flub** [comment]
test no longer exists?
