### ISSUE TITLE
unresponsive console on doc watch

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#1876]
Running on 0d9ebea18af62bcf83ffb87fbb8b97cfcd7301a4

Steps that most likely will reproduce the issue are:
```
# console 1
cargo run console --start
doc new --switch
doc share write
doc watch
```
complete all steps in console 1 before going to console 2
```
# console 2
env IROH_DATA_DIR=/tmp/console2 cargo run console --start
doc join --switch <ticket>
doc set a b
doc set aa bb
```

go back to console 1 and hit `ctrl-c` or `ctrl-d`. unresponsive and needs to be killed

**Comment by dignifiedquire** [comment]
Tried multiple times, unable to reproduce. This might be specific to the shell being used

**Comment by divagant-martian** [comment]
fixed in https://github.com/n0-computer/iroh/pull/1909
