### ISSUE TITLE
Test failure while running ProtonVPN on OSX

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1891]
It seems that the test suite does not work when in a VPN. E.g.

```
test net::interfaces::tests::test_default_route ... FAILED

failures:

---- net::interfaces::tests::test_default_route stdout ----
thread 'net::interfaces::tests::test_default_route' panicked at iroh-net/src/net/interfaces.rs:392:14:
missing default route
```

That might not be the end of the world, I can disable the VPN for running tests. But it would not be great if running a VPN would prevent iroh-net in general from working.

**Comment by dignifiedquire** [comment]
Interesting, I guess in a vpn setting there is no default route available. 

@rklaehn can you see if regular usage of things still work with the VPN running?

**Comment by dignifiedquire** [comment]
Tests of iroh on a VPN indicate that things work as expected. That test specifically is fine to fail when connected to a VPN, as it is just testing an optional thing.
