### ISSUE TITLE
Proposal: handling flaky tests

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1919]
# Objective

Ensure flaky tests do not slow down PRs and take up too many CI resources while not neglecting them entirely.

# Background

Despite our best efforts we regularly have flaky tests.  This is problematic because we use a merge queue normally, which means after a PR has all tests passing the tests are run once again when in the merge queue.  If a test then suddenly fails in the merge queue it is removed from the merge queue and needs to be manually put in the merge queue to try again.  Given enough flaky tests PRs can go through several rounds of this before they manage to be merged, clogging up CI resources.

# Proposal

## Ruthlessly removing flaky tests

To keep the merge queue flowing we **must** remove every single instance of a flaky tests.  Each failure of tests in the merge queue should result in either:

* Fixing the test if it was caused by the PR itself.
* Marking the test as `#[ignore = "flaky"]`
  * Creating an issue to resolve this flaky test, labelled `flaky-test`

Simply re-scheduling the PR in the merge queue without doing either of these must never occur.

## Fixing flaky tests

The flaky test was also written for a reason, we can not simply forget about it.  We also have to accept that it needs running in CI to show up.  We should create a new github actions workflow for flaky tests:

* This "flaky workflow" must run the entire test suite, including normal and flaky tests to create the most realistic environment for it to remain flaky.
  * The `--ignored` argument to the test runner allows doing this.
* This "flaky workflow" should run on a cron job, failures should nag us somewhere.
  * Maybe nag us in a discord channel if possible?
  * The cronjob must not take up too many CI resources but still be regular.  Daily is probably a good start.
* It should be possible to manually trigger this flaky workflow.
  * Some issues can only be debugged on CI.  We must allow doing so.
* PRs should be able to target the flaky workfow.
  * When working on flaky tests a PR would waste CI resources if it needs to both run the normal CI workflow and the flaky workflow.
  * Maybe a label on the PR could be used to disable the normal CI workflow and enable the flaky workflow.

**Comment by Arqu** [comment]
👏 like the proposal very much.

**Comment by ramfox** [comment]
Sounds good to me!

**Comment by flub** [comment]
The only thing missing now is some notification for the flaky workflow failures.

**Comment by dignifiedquire** [comment]
@flub where are we with the notifications/reruns?

**Comment by flub** [comment]
reruns are happening: https://github.com/n0-computer/iroh/actions/workflows/flaky.yaml (some are even passing!)

Now that we have a github channel in discord for reporing rust beta compiler failures we could also use that for reporting these scheduled runs.  Maybe add it on the 0.14 milestone for that?  Shouldn't be loads of work

**Comment by dignifiedquire** [comment]
> Maybe add it on the 0.14 milestone for that? Shouldn't be loads of work

sounds good

**Comment by flub** [comment]
Indeed, thanks for spotting.  It was left over because we did not yet have the notifications.  But now we do.
