### ISSUE TITLE
cli and provide tests are largely flaky

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1935]
There are a whole bunch of flaky integration tests in the following files:

- `iroh/tests/cli.rs`
- `iroh/tests/provide.rs`

I suspect all of these are related to filesystem latencies.  We probably need a reliable way to run `sync(1)`/`fsync(2)` on the filesystem to fix all of these.

**Comment by flub** [comment]
https://github.com/n0-computer/iroh/actions/runs/7829002247/job/21360042881?pr=2009

**Comment by flub** [comment]
Maybe we should just sprinkle shelling out to the `sync(1)` command around to see if this helps quickly.  As ugly as it may be, we'd get these tests back.  If there's an equivalent for this on Windows.

**Comment by matheus23** [comment]
> https://github.com/n0-computer/iroh/actions/runs/7829002247/job/21360042881?pr=2009

The next time we should download the logs & upload them here.
They've expired since, and they'd be really valuable actually.

**Comment by divagant-martian** [comment]
most of these tests are no longer flaky, and grouping them all together gives us a poor view of our understanding of what's wrong with each. That being said, I'll close this and open new issue for the two remaining cli flaky tests
