### ISSUE TITLE
Slow boot time with a large repo size

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1942]
Iroh has a very slow boot time, like more than 1 hour, when the node has a very large repo size.

This is likely due to disk access.  We should evaluate what happens at startup and see if we can make this faster.

**Comment by dignifiedquire** [comment]
In https://github.com/n0-computer/iroh/blob/main/iroh-bytes/src/store/flat.rs#L1205 there is a full scan of all partial and full entries on startup. This should be likely avoided, as this means a linear increase in boot time. I wonder if at this point having a DB or some more structure (to reference the metadata at least) makes sense, given this clearly does not scale anymore .

**Comment by dignifiedquire** [comment]
I started a version here that stores the overall entries in a redb DB: https://github.com/n0-computer/iroh/tree/perf-startup
