### ISSUE TITLE
UX consitency swap console -d to -c

### ISSUE THREAD

**Issue by s2dd** [n0-computer/iroh#1944]
for UX consitency swap console -d to -c

i suggest when in console -d for escape / return and -c for exit as would be consistent with exit in iroh and elsewhere.

**Comment by dignifiedquire** [comment]
I assume you mean `Ctrl+C` and `Ctrl+D` keyboard shortcuts. This was done on purpose, to allow cancellation of commands in the console using `Ctrl+C`. This mirrors how the `python` repl and many other repls work.

**Comment by ramfox** [comment]
closing this issue
