### ISSUE TITLE
`blob_download` unnecessarily tries to connect to a peer even if the requested blob is found locally.

### ISSUE THREAD

**Issue by expenses** [n0-computer/iroh#1947]
I ran into this issue when testing the RPC interface, by taking a `BlobTicket`, deconstructing it, constructing a `BlobDownloadRequest` and calling  `BlobsClient::download`. It's trivial to work around, simply call `BlobsClient::read` or `BlobsClient::read_to_bytes` first and use that result if you don't get an error. Perhaps this behaviour is intended, but it's a little unintuitive.

**Comment by dignifiedquire** [comment]
Yes, we should avoid creating network connections if we don't actually need them

**Comment by dignifiedquire** [comment]
This is fixed in #1962
