### ISSUE TITLE
Losing messages

### ISSUE THREAD

**Issue by zrus** [n0-computer/iroh#1961]
Hi,

Currently I am implementing my own service using iroh to create connection between nodes with most is uni-direction streams.
Let's call them `sender` and `receiver` in my simple workaround just to send and received messages.

When those two nodes have connection, I started to send 5.000 **unique** messages (each message contains current timestamp in nanoseconds) in a row with 3 case:

* Without any sleep: the `receiver` node only received ~10% of total messages (about 5x messages).
* With **1 ms** `tokio::sleep`: `receiver` node received ~20 - 25% of total messages (about 5xx - 7xx messages).
* With **5 ms** `tokio::sleep`:  `receiver` now can receive all the messages.

My question is, how to prevent losing messages? I made messages unique one by one to prevent them are marked as spam. Is there anything else I should configure like rate limit or throttle?

Thanks in advance.

**Comment by xraid** [comment]
maybe try use a local derper set to `stun_only = true`

**Comment by dignifiedquire** [comment]
how are you sending & receiving these messages?

**Comment by flub** [comment]
The QUIC streams provided by iroh are reliable and this kind of packet loss would be surprising.  You provide very little detail of what you're testing, but from your description I can produce code like this which does not lose any message:

```
use anyhow::{Context, Result};
use iroh_net::{MagicEndpoint, NodeAddr};

#[tokio::main]
async fn main() -> Result<()> {
    println!("Hello, world!");
    let server_ep = MagicEndpoint::builder()
        .alpns(vec![b"tmp".into()])
        .bind(1230)
        .await
        .context("server bind")?;
    let server_addr = server_ep.my_addr().await?;
    let server = tokio::spawn(accept_connections(server_ep));
    let client = tokio::spawn(async move {
        if let Err(err) = create_connections(server_addr).await {
            println!("create_connections: {err:#}");
        }
    });
    client.await.context("client")?;
    server.await.context("server")?;
    Ok(())
}

async fn accept_connections(ep: MagicEndpoint) {
    match ep.accept().await {
        Some(connecting) => {
            if let Err(err) = handle_connection(connecting).await {
                println!("connection error: {err:#}");
            }
        }
        None => {
            println!("Accepting endpoint closed");
        }
    };
}

async fn handle_connection(connecting: quinn::Connecting) -> Result<()> {
    let connection = connecting.await.context("connecting")?;
    let mut stream = connection.accept_uni().await.context("accept_uni")?;
    for i in 0..500 {
        let mut buf = [0u8; 4];
        stream.read_exact(&mut buf).await.context("read_exact")?;
        let n = u32::from_be_bytes(buf);
        assert_eq!(n, i);
    }
    println!("received all messages");
    Ok(())
}

async fn create_connections(addr: NodeAddr) -> Result<()> {
    let ep = MagicEndpoint::builder()
        .bind(1240)
        .await
        .context("client bind")?;
    let conn = ep.connect(addr, &b"tmp"[..]).await.context("connect")?;
    let mut stream = conn.open_uni().await.context("open_uni")?;
    for i in 0..500u32 {
        let buf = i.to_be_bytes();
        stream.write_all(&buf).await.context("write")?;
    }
    stream.finish().await.context("finish")?;
    println!("sent all messages");
    Ok(())
}
```

Maybe if you provide some more detail we can help you understand the problem.  The QUIC API is powerful but also relatively low-level and has some sharp edges.  E.g. if you remove the `stream.finish()` call from the above example things will no longer be reliable since the sender destroys it's local QUIC state before all packets have been sent over the wire.

**Comment by zrus** [comment]
> maybe try use a local derper set to `stun_only = true`

I only use 2 local nodes, know each other via my mdns service discovery.

**Comment by zrus** [comment]
> how are you sending & receiving these messages?

I use my mDNS discovery service to find each other, then they are connecting to each other. After that I just send messages.

**Comment by zrus** [comment]
Additionally, each node is running below an actor which has a message queue. Those messages in message queue will be handled sequentially. So there is no way that many calls of `send_message` happen at the same time.

**Comment by flub** [comment]
> > how are you sending & receiving these messages?
> 
> I use my mDNS discovery service to find each other, then they are connecting to each other. After that I just send messages.

If you could provide some code this would be very helpful.  If the streams connect only a connection failure could result in undelivered messages when used correctly, but if there is no connection failure QUIC does guarantee delivery.

**Comment by zrus** [comment]
> Maybe if you provide some more detail we can help you understand the problem. The QUIC API is powerful but also relatively low-level and has some sharp edges. E.g. if you remove the `stream.finish()` call from the above example things will no longer be reliable since the sender would destroy it's local QUIC state before all packets have been sent over the wire.

Well, let me list out my flow. Hope that you can help me.

1. I use my mDNS service to find others from a local network and share there `NodeAddr`. Let say `sender` as node `A` and `receiver` as node `B`. After `A` or `B` found the other, it will add that node by calling `MagicEndpoint.add_node_addr`.
2. There is a common topic that `A` and `B` subscribe to by calling `Gossip.join` (`Gossip` instance obtained by `Gossip::from_endpoint`).
3. I use `tokio::spawn` to spawn a `subscribe_loop` that will handle `GossipEvent` from stream obtained by calling `Gossip.subscribe`.
(Note: those `Gossip` and `MagicEndpoint` are properties of struct call State which would be used as state of an actor)

Any idea that I missed in this flow? Thanks in advance.

**Comment by zrus** [comment]
> If you could provide some code this would be very helpful. If the streams connect only a connection failure could result in undelivered messages when used correctly, but if there is no connection failure QUIC does guarantee delivery.

Certainly, I describe more at above reply. Ping me anytime. Thanks

**Comment by xraid** [comment]
when using MagicEndpoint it defaults with "*-derp.iroh.network" relay servers from 
`DerpMode::Default => default_derp_map()` in `MagicEndpoint.rs:225 bind()`

unless `Disabled` or `Custom` is set, 

by adding `println!("derp {:?}", server_ep.my_derp());` to above code will show the  "*-derp.iroh.network" relay

that also begs the Q :
https://github.com/n0-computer/iroh/issues/1955#issuecomment-1898520031
?

when running above code with a local derper --config,  log shows relay unless i set `enable_derp = false`in derper --config

and when run local derper with `enable_derp = true` = relay enabled it gives : 
```
2024-01-20T05:36:01.023821Z  WARN derp.server{me=hzky2gulfd7yvqzr}:conn_io: iroh_net::derp::client_conn: connection manager for PublicKey(pimit5sfzgs7nui7) 3: writer closed in error read stream ended
2024-01-20T05:36:01.023821Z  WARN derp.server{me=hzky2gulfd7yvqzr}:conn_io: iroh_net::derp::client_conn: connection manager for PublicKey(zdd6hxqtssz55jhv) 4: writer closed in error read stream ended
2024-01-20T05:36:01.023924Z  WARN derp.server{me=hzky2gulfd7yvqzr}: iroh_net::derp::clients: Can no longer write to client PublicKey(zdd6hxqtssz55jhv), dropping message and pruning connection
2024-01-20T05:36:01.023955Z  WARN derp.server{me=hzky2gulfd7yvqzr}: iroh_net::derp::clients: Could not find client for PublicKey(pimit5sfzgs7nui7), dropping peer gone packet
2024-01-20T05:36:01.023971Z  WARN derp.server{me=hzky2gulfd7yvqzr}: iroh_net::derp::clients: pruning connection PublicKey(zdd6hxqtssz55jhv)
2024-01-20T05:36:01.023997Z  WARN derp.server{me=hzky2gulfd7yvqzr}: iroh_net::derp::clients: pruning connection PublicKey(pimit5sfzgs7nui7)
```

maybe @zrus can try `DerpMode::Disabled` when init  MagicEndpoint ?

**Comment by zrus** [comment]
Okay I might find out the problem.

When I call `Gossip.subscribe`, it returns a `tokio::sync::broadcast::Receiver` with channel capacity is 2048.

https://github.com/n0-computer/iroh/blob/main/iroh-gossip/src/net.rs#L33

And the error say it is lagged behind and crash my loop handler. Perhaps that why I could not receive any messages further.

**Comment by zrus** [comment]
Sure. I will note that. Thanks for your support.
