### ISSUE TITLE
unexpected argument '--rpc-port' found

### ISSUE THREAD

**Issue by antontranelis** [n0-computer/iroh#1963]
When I do the [Quickstart](https://iroh.computer/docs/quickstart) and running `iroh start --rpc-port 1111` there is this error: 

```
error: unexpected argument '--rpc-port' found
Usage: iroh start [OPTIONS]
For more information, try '--help'.
```

Also the `-c` flag on the `doc get` command is not accepted resulting in 

```
> doc get foo -c
error: unexpected argument '-c' found
```

is the Quickstart up to date?

iroh is version 0.12.0

**Comment by xraid** [comment]
i think the [Quickstart](https://iroh.computer/docs/quickstart) is referencing Version 0.6.0 of iroh, and the main repo is now at 0.12.0

to follow the [Quickstart](https://iroh.computer/docs/quickstart)  a documentation use downloaded binary or `cargo run` from a  `git checkout v0.6.0`

**Comment by dignifiedquire** [comment]
The quickstart was just updated to the latest version, sorry about that https://github.com/n0-computer/iroh.computer/pull/103

**Comment by xraid** [comment]
maybe also mention the command  ` iroh console --start `where node and console is in same invocation

**Comment by david-potgieter** [comment]
Reference to `--rpc-port` was missed in the configuration documentation. Added [PR-139](https://github.com/n0-computer/iroh.computer/pull/139) to align.
