### ISSUE TITLE
Install script install unverified binary

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#1980]
The install script downloads a binary over plain HTTP and does not do any verifying that the right binary is fetched.

Since the install script itself is served over HTTPS I would expect some level of verification that the correct binary arrives.  Either by making sure all requests are over HTTPS and curl verifies the certificates, or by checking the checksum after downloading the binary.

**Comment by Arqu** [comment]
Yikes, good catch. Should be fixed now. Feel free to reopen if I'm mistaken.
