### ISSUE TITLE
Improve downloader

### ISSUE THREAD

**Issue by Frando** [n0-computer/iroh#1992]
Currently the `iroh::downloader` module is only used for iroh sync. Regular downloads (for `blob download`) are using the iroh bytes API directly. What we want to do is:

* [x] Move the downloader iroh-bytes
* [x] Improve downloader and enable use in iroh node for blob downloads
  * #2085 
  * #2165 
* [x] Improve content downloading in docs:
  * #2127  
* [ ] Support content discovery and announcements in the downloader

**Comment by dignifiedquire** [comment]
Most of the originally planned work here was done, closing this
