### ISSUE TITLE
Netcheck does not query AAAA records for the derp server

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2006]
When resolving the derp URL netcheck seems to query only A records, even on a machine which has a full public IPv6 address.

**Comment by dignifiedquire** [comment]
according to [`lookup_ip`](https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/struct.AsyncResolver.html#method.lookup_ip) it should do a dual stack lookup, why do you think we do not resolve `AAAA` records?

**Comment by dignifiedquire** [comment]
likely this is the current behaviour: 

https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/config/enum.LookupIpStrategy.html#variant.Ipv4thenIpv6

**Comment by flub** [comment]
> according to [`lookup_ip`](https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/struct.AsyncResolver.html#method.lookup_ip) it should do a dual stack lookup, why do you think we do not resolve `AAAA` records?

Yes, I was also surprised it didn't.  But didn't dig deeper and created this issue instead.  You can tell when having debug logging as the resolver library logs the full query.

> likely this is the current behaviour:
> 
> https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/config/enum.LookupIpStrategy.html#variant.Ipv4thenIpv6

Good find, rather possible.

**Comment by flub** [comment]
Eh, good point about the lack of streaming API and this delaying the IPv4 result.  This could delay netcheck further for us.

**Comment by dignifiedquire** [comment]
ugh, that is bad, we should probably manually issue ipv4 and ipv6 queries then..

**Comment by flub** [comment]
Fixed in #2026
