### ISSUE TITLE
netcheck report does not finish early enough

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2021]
I have a netcheck report where we have established connectivity to the derper and figured out our IPv4 STUN addresses very quickly, yet keep waiting for all probes much, much to long.  In fact it logs `Have enough probe reports, aborting further probes soon` and yet it waits forever for to actually abort.  This wreaks havoc with good connection establishment.

Splitting this off to keep #1984 somewhat limited in scope.

Relevant log: https://gist.github.com/flub/1d503f757bc1e275e417d0d918b66604

**Comment by dignifiedquire** [comment]
I suspected this behaviour as well when reading logs for a while, but could never quite nail it.
