### ISSUE TITLE
bug: in the console `author new --switch` hangs

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#2024]
To repro:

`iroh console --start`

then in the console:

`author new --switch`

The new author id is printed to the console, but the console never returns to a state to receive more input. You can't even `Ctrl-C` to interrupt the command nor can you `Ctrl-D` to close the console.

**Comment by divagant-martian** [comment]
`git bisect` tracked this down to #2013
I'll work tomorrow on a fix
