### ISSUE TITLE
magicsock: do not block on netcheck when connecting to a node

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2040]
Currently the magicsock blocks on completing a first netcheck at startup.  However we should be able to start using a relay serve immediately, resulting in bytes starting to flow faster.  Even if that means you are initially on the wrong relay server.

Being on the wrong relay server is not really important if you are connecting as you use the relay server of the other node anyway.  If you are accepting connections this is more trouble if you already gave out a ticket with the relay server before you switched.

**Comment by divagant-martian** [comment]
@flub can you expand more? after doing some testing, I realized that, at least, the creation of an iroh node is blocked by the result of the first `netcheck::Report` [here](https://github.com/n0-computer/iroh/blob/26d718f324293ea1e428ce7b28a631e676d51279/iroh/src/node/builder.rs#L415). This on itself seems reasonable since netcheck contains as well information about our local endpoints.

On a related note, the `magicsock::Actor` itself does not seem to be blocked by this. From the description I assume you mean.. blocking sending? Given the need to get information of local endpoints, which comes from netcheck right now, how do you think we could work around this?

**Comment by flub** [comment]
I was thinking of the `MagicEndpoint::connect` flow:
```rust
let ep = MagicEndpoint::builder().bind().await?;
let conn = ep.connect(node_addr_containing_a_relay_url, &b"my-alpn"[..]).await?;
let send_stream = conn.open_uni().await?;
send_stream.write_all(&b"hello"[..]).await?;
```
I *thought* at the time of writing that this blocks somewhere waiting for a netcheck result, even though it may not need one.  Though looking through the code-path now I'm not sure if this does really wait.  But this is the path that the issue had in mind that had to not block on netcheck.

When doing a `MagicEndpoint::accept` call I guess it is unavoidable to wait because you kind of need to know the home relay.  But maybe it is possible to start accepting before the relay is known - your NodeAddr would only contain your direct bind addresses and later get the STUN and RelayUrl addresses added as they become available.  But this is the other path that could be optimised.  (again not sure on the current details)

**Comment by divagant-martian** [comment]
Based on your last comment I updated the issue tittle. However, after more testing, if I delay the sending of the `netcheck::Report` then tests do fail. But then on a closer look, using deterministic public keys/ node ids, if I delay sending the report even for long periods of time (10, seconds) only on the sending side (the node performing the `connect`) no tests fail. 

My conclusion is that we do not block sending before we get a netcheck report. This of course comes after not only testing but just like you mentioned, perusing the code trying to find any way this could happen and also finding nothing.

Should we close this issue? Other optimization paths are deserving of their own issue description

**Comment by divagant-martian** [comment]
Closing this issue, as I've verified this is not happening. On the connecting side it's not an issue regardless of what kind of address we use to connect with the peer (udp, relay, both).

On the accept side, this only occurs in the relay only case, which makes total sense. As long as there is a udp address, accept works just fine even in the absence of a first netcheck

**Comment by flub** [comment]
Great!  Thanks for the testing and finding out how our code actually behaves!
