### ISSUE TITLE
Iroh Sync Speed

### ISSUE THREAD

**Issue by DAOCUONG** [n0-computer/iroh#2133]
Iroh should be the fastest most advantage sync file ever because written in rust, use quinn, bao tree. With AI and LLM iroh can help us to share dataset and weight file easily and faster
I have tested sync 140 MB file take 3 min with local wifi its seem too slow for me. 
Do we have any test cases that measure sync performance. Can any one point me how i can help with improve the sync speed
We should have the fastest sync speed

**Comment by dignifiedquire** [comment]
We have performance measurements in CI up here: https://perf.iroh.computer/

To your specific problems
- can you check if you are getting a direct connection or a relayed one? 
- can you check using `iroh doctor` the speed and connection type?
- what is your performance between these two devices when measured using `iperf3` with udp?

**Comment by DAOCUONG** [comment]
@dignifiedquire  Thanks for information im reading documents and do experiments to answer your questions

**Comment by dignifiedquire** [comment]
Closing for now, please do let us now if you have more questions
