### ISSUE TITLE
Add file logger

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#2139]
For debugging help, let's add the default ability to log to a file. This should be a rolling file, and we should only keep a certain MB of recent data.

This needs to be easily disabled and configured.

https://crates.io/crates/tracing-rolling-file

**Comment by divagant-martian** [comment]
[tracing-rolling-file](https://crates.io/crates/tracing-rolling-file) is not used by [any project in crates.io](https://crates.io/crates/tracing-rolling-file/reverse_dependencies) and it looks like it't not even a choice for projects [in github](https://github.com/search?q=%2Ftracing-rolling-file%2F&type=code). Perhaps the one that was meant to be referenced is [rolling-file](https://crates.io/crates/rolling-file)?

Taking into account that log subscribing should not be done by libraries but binaries, this should not be added to iroh itself. But iroh-cli, perhaps fog as well?

**Comment by dignifiedquire** [comment]
> this should not be added to iroh itself. But `iroh-cli`, perhaps `iroh-fog` as well?

Yes, lets add it to `iroh-cli` only for now
