### ISSUE TITLE
iroh-net: wait until home derper is known

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#2162]
In many examples I have code like this:

```rust
/// Wait until the endpoint has figured out it's own DERP region.
async fn await_derp_region(endpoint: &MagicEndpoint) -> anyhow::Result<()> {
    let t0 = Instant::now();
    loop {
        let addr = endpoint.my_addr().await?;
        if addr.relay_url().is_some() {
            break;
        }
        if t0.elapsed() > Duration::from_secs(10) {
            anyhow::bail!("timeout waiting for DERP region");
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    Ok(())
}
```

This is not very nice. It would be better to have something like this built in.

**Comment by rklaehn** [comment]
I want to make sure the ticket contains useful information when I print it. E.g. in sendme and dumbpipe: https://github.com/n0-computer/sendme/blob/main/src/main.rs#L471
https://github.com/n0-computer/dumbpipe/blob/main/src/main.rs#L263

Or just show some info about the node in the tracker.
https://github.com/n0-computer/iroh-examples/blob/main/content-discovery/iroh-mainline-tracker/src/main.rs#L142

**Comment by rklaehn** [comment]
Some sort of broadcast stream of events whenever the endpoint changes state might also do. In any case this is not the end of the world. Just was reminded of this by the PR https://github.com/n0-computer/iroh/pull/2161

**Comment by flub** [comment]
You can use `MagicEndpoint::local_endpoints` as the indicator for when all the things like `MagicEndpoint::local_addr` and `MagicEndpoint::my_relay` and `MagicEndpoint::my_addr` are available.  I agree this is all pretty ugly and we should think about this API.
