### ISSUE TITLE
gateway: pass in custom resolver

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#217]
@fabricedesre:
> @Arqu & @dignifiedquire I'm looking at adding back http gateway racing to the resolving code but I'm not sure how to do it without touching iroh-gateway itself since the resolver is created in iroh-gateway/src/client.src
> One way would be to turn the client's State in iroh-gateway/src/core.rs to a trait instead, and pass it in make_state() like we do for the configuration.

**Comment by Arqu** [comment]
Think we can simplify that. The resolver is created when the Client is instantiated which is on `Core::new`. Maybe we can simply make an `Optional<Resolver>` arg on the `make_with_state` function and simply set a custom resolver on the client if present? @dignifiedquire any input on this. Might be worthwhile to convert the Core to follow a builder pattern so you can do `Core::builder().with_state(state).with_resolver(resolver)....`

**Comment by fabricedesre** [comment]
Fixed by #220
