### ISSUE TITLE
iroh-relay: make it possible to disable captive portal

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2178]
There is an option `captive_portal_port` but in my case HTTP port is already taken by `acmetool redirector` service:
 https://github.com/n0-computer/iroh/blob/b07547b68eb771e789474ad4f1344e02b2223f95/iroh-net/src/bin/iroh-relay.rs#L228

Having captive portal on any port other than 80 does not really make sense if I understand correctly its purpose (maybe to put it behind reverse proxy, but then I can configure nginx or whatever reverse proxy to respond however I want myself), so would be better if there was an option to just disable it. As a workaround I have moved it to an arbitrary port.

**Comment by flub** [comment]
Fixed by https://github.com/n0-computer/iroh/pull/2341. If not feel free to reopen
