### ISSUE TITLE
iroh-relay: run behind reverse proxy

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2179]
Is it possible to run iroh-relay behind reverse proxy such as nginx?

I am currently getting certificates using `acmetool` and run iroh-relay with manual certificate mode:
https://github.com/n0-computer/iroh/blob/b07547b68eb771e789474ad4f1344e02b2223f95/iroh-net/src/bin/iroh-relay.rs#L209

But to give iroh-relay access to the key I have to run it as root. To avoid this I would like to run iroh-relay as HTTP and STUN node and have nginx which has access to TLS key proxy all requests to iroh-relay. For STUN server it is also possible by defining a `stream` section in nginx config: https://github.com/coturn/coturn/issues/702

**Comment by flub** [comment]
Why can't you make the certificates readable by the user that runs the relay?

**Comment by dignifiedquire** [comment]
@link2xt what's the difference here between this issue and #2177 ?

**Comment by flub** [comment]
Fixed by #2341.  If not feel free to reopen
