### ISSUE TITLE
`iroh blob add` uses absolute paths instead of the relative directory

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#2210]
Building collections from the root of the filesystem isn't great UX 😵‍💫. I'd expect blob add to use the input argument as the root of the collection structure.

**Comment by cameronfyfe** [comment]
Looking at this further I realized the collections themselves use the relative paths, it was just the cli stdout that shows the absolute paths for everything.

**Comment by cameronfyfe** [comment]
Seems the code that sends the progress message that prints that out is in the Store impl and at that point only has the path, it doesn't know the blob is for a collection and has a pet name in that context.

**Comment by b5** [comment]
closing as stale
