### ISSUE TITLE
Symbol collisions when building with both `iroh` and `ssi` crates as dependencies

### ISSUE THREAD

**Issue by cameronfyfe** [n0-computer/iroh#2217]
When I build a project that use crates from https://github.com/spruceid/ssi that bring in their own `blake3` crate I get symbol collision errors at link time on some platforms.

I haven't had issues on `x86-linux` or `aarch64-macos` but `aarch64-linux` builds fail due to the multiple blake3 libraries.

My work-around for now is that I forked `iroh-blake3` and changed the package name back to `blake3` which lets me do a cargo patch to override the `blake3` crates brought in by the SSI crates. (cargo only lets you apply patches to crates with the same package name name).

**Comment by flub** [comment]
Guess this shouldn't be closed yet.  This can only be closed once a new iroh-blake3 release is made and we use that in iroh.

**Comment by flub** [comment]
I'm not able to push this any further.  iroh-blake3 is owned by @rklaehn on crates.io so it's in his hands.

**Comment by dignifiedquire** [comment]
`iroh-blake3@1.4.5` fixes this
