### ISSUE TITLE
upgrade to quinn@0.11 & rustls@0.23

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2273]
WIP branch: https://github.com/n0-computer/iroh/tree/dig/quinn11

- [x] The `dig/quinn11` branch needs to work and pass all tests
  - [x] On patched dependencies
  - [x] On released dependencies
- [x] We need an **iroh-quinn** version released for 0.11
- [x] We need a new **quic-rpc** version released
- [x] We need a new **axum-server** version released
- [x] We need a new **tokio-rustls-acme** release
- [x] We should upgrade **request** @0.12.5 so it uses rustls@0.23

Once the basics work, we need to make it good:
- [x] get net performance numbers
  - we have declared per to be ok

Nice to have:
- [x] hickory-resolver upgrade to rustls@0.23
  - We are using `=0.25.0-alpha.2` 
  - https://github.com/hickory-dns/hickory-dns/issues/2206

Outstanding issues:
- [ ] When sending to the relay all packets are copied.
  - AsyncUdpSocket @0.10 gave us `Bytes`, but @0.11 gives us a `&[u8]` and we end up copying this to send it along channels to the relay actors.  That's a severe performance regression
- [x] Review all newly added TODO items

**Comment by matheus23** [comment]
Can I help move this along somehow?
For browser work, it'd be great to have `rustls` upgraded to version 0.22 or above, because at that version it doesn't depend on `std::time::Instant::now` anymore, which panics in Wasm.

**Comment by flub** [comment]
> Can I help move this along somehow? For browser work, it'd be great to have `rustls` upgraded to version 0.22 or above, because at that version it doesn't depend on `std::time::Instant::now` anymore, which panics in Wasm.

It's currently in the mode of making the test suite pass.  All "changes" should be done and it is "just" debugging.  So the work right now is: run test suite, pick most promising failing test, debug it, push fix, run test suite again to see if more failures are magically fixed, pick next test.

But most test failures have just been fixes in the test suite, so progress has been slow.

**Comment by ramfox** [comment]
Closed by #2595
