### ISSUE TITLE
Clarify expected cache headers

### ISSUE THREAD

**Issue by fabricedesre** [n0-computer/iroh#230]
From discord:

```
[10:46 AM] fabrice:
why is "no-cache" used for the default cache header value? 
[10:59 AM] Arqu:
Lots of those bits are still not fully fleshed out
[10:59 AM] Arqu:
Technically we cache everything if the store is present
[11:00 AM] Arqu:
But we dont handle the etags and cache headers fully so it doesnt make sense we advertise anything else
[11:00 AM] Arqu:
The blessing with content addressed storage is you can cache a cid indefinitely technically as the contents wont change
[11:01 AM] Arqu:
And you never cache ipns type reqs
```

I'm not sure if it's worth exposing cache headers as configurable. As @Arqu says, behavior needs to different between `/ipfs` and `/ipns`. For `raw` and `car` response, we should return `Cache-Control: immutable`.

Thoughts?

**Comment by fabricedesre** [comment]
The IPFS gateway spec section for the `Cache-Control` response header is at https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#cache-control-response-header

There are no differences in https://github.com/ipfs/specs/blob/main/http-gateways/TRUSTLESS_GATEWAY.md

**Comment by Arqu** [comment]
Spec is already being followed, in the next update the misleading flags will be removed. The only exception is that for the IPNS based `Last-Modified` date we follow what kubo does instead of taking the spec recommendation to either do dns ttl based dates or not at all.
