### ISSUE TITLE
feat: make iroh-gossip message size configurable

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2312]
There is a TODO here:
https://github.com/n0-computer/iroh/blob/370075c6d5689ad4349664eb9b51ec0a5e7e4e81/iroh-gossip/src/net.rs#L30-L31

I ran into this problem, after trying to send a large message over gossip it stops working (in Delta Chat). Maybe it is our error handling that is wrong, have not investigated further yet.

I wanted to send PCM audio, in 4096 bytes with a single channel of 32-bit floats at 8kHz I can only encode 128ms of audio (8 * 4096 / 32 /  8000) per message. Will split into chunks of 3k bytes now just to make sure, but would be nice to have less overhead and just avoid the problem of the channel silently failing because the message is too large.

**Comment by dignifiedquire** [comment]
seems like this should be just configurable
