### ISSUE TITLE
Add support for DNS resolution on non-port 53 to DnsDiscovery

### ISSUE THREAD

**Issue by zh522130** [n0-computer/iroh#2342]
I do have this need because my port 53 is required for other DNS services. Currently, I have modified the code locally and validated it. If others have a similar need, I can submit a PR.

**Comment by zh522130** [comment]
This is not an issue; I just want to confirm whether I should submit this PR.

**Comment by dignifiedquire** [comment]
which part of the code are you talking about, `iroh-dns-server`?

**Comment by zh522130** [comment]
> which part of the code are you talking about, `iroh-dns-server`?

yes

**Comment by dignifiedquire** [comment]
sure, a PR would be appreciated

**Comment by zh522130** [comment]
There was an issue with my previous description. The actual situation is that the `iroh-dns-server` can run on non-port 53, but `DnsDiscovery` does not support resolution on non-port 53.

**Comment by flub** [comment]
I think this is already possible with `iroh_net::endpoint::Builder::dns_resolver`: it allows you to construct your own resolver client that the endpoint will use, including the DnsDiscovery feature.   You'd use something like `hickory_resolver::config::ResolverConfig::add_name_server` to set custom connection details for your DNS server.

**Comment by zh522130** [comment]
> I think this is already possible with `iroh_net::endpoint::Builder::dns_resolver`: it allows you to construct your own resolver client that the endpoint will use, including the DnsDiscovery feature. You'd use something like `hickory_resolver::config::ResolverConfig::add_name_server` to set custom connection details for your DNS server.

I have previously tested the `dns_resolver,` and the main issue is that the relay also uses `dns_resolver,` which cannot resolve the relay address. It's possible that I'm using it incorrectly, I will continue to research this. Once the tests pass, I'll close this issue.

**Comment by zh522130** [comment]
@flub Thank you. I've implemented custom port resolution through `dns_resolver`. 

Should anyone need it, you can refer to the `create_default_resolver` function in `dns.rs`. You simply need to add a DNS service with a custom port using `config.add_name_server()`.
