### ISSUE TITLE
Add optional LAN discovery service

### ISSUE THREAD

**Issue by zh522130** [n0-computer/iroh#2354]
The current discovery service lacks a Local Area Network (LAN) discovery mechanism. I would like an optional LAN discovery feature that, if enabled, would allow the system to fall back on LAN discovery whenever it is unable to connect to the discovery server.

It should be noted that not all LANs support broadcast or multicast, hence mDNS might not be entirely reliable. Previously, I addressed this issue by performing parallel IP scans via a specified UDP port, but there might be a better solution.

**Comment by flub** [comment]
We do plan on adding mDNS as an option.  IIRC there have even been prototypes already, I'm not sure where they are though.

Could you describe a bit more in which situations mDNS had the issues with broadcast you mention?

**Comment by zh522130** [comment]
> We do plan on adding mDNS as an option. IIRC there have even been prototypes already, I'm not sure where they are though.
> 
Looking forward to it.
> Could you describe a bit more in which situations mDNS had the issues with broadcast you mention?

So far, in actual local area networks, I haven't encountered scenarios where broadcasting or multicasting has been disabled. However, I have faced this when proxy software is used to connect different subnets into a single large LAN. The proxy software supports UDP but lacks support for broadcasting or multicasting. Previously, GPT informed me that administrators might disable broadcasting or multicasting for security reasons, yet I am not sure if this situation truly exists.（Perhaps we should consider the majority of cases first.）

**Comment by zh522130** [comment]
I have found several relevant issues at https://github.com/n0-computer/iroh/issues/990, https://github.com/n0-computer/iroh/pull/817, and https://github.com/n0-computer/iroh/pull/1914
