### ISSUE TITLE
Does iroh-gossip guarantee that messages sent by the same sender are received by everyone in the same order?

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#2360]
I'm almost positive it doesn't, but either way, we need to document an answer on what the current behavior is

**Comment by divagant-martian** [comment]
There is no notion of order in gossip at all, and a perceived reordering is expected simply given the existence of lazy peers, which might be eager peers of our eager peers. This is a known not-guarantee and I doubt we should try to make it one even in the simple cases

**Comment by dignifiedquire** [comment]
Thanks, closing, please let us know if you find an issue with iroh
