### ISSUE TITLE
Move relay HTTP handler to be served on /relay

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2378]
Currently the relay HTTP handler is served on `/derp`.  We should transition that to `/relay` before we stabilise the wire protocol. But we want to coordinate this as it is a breaking wire-level change.

**Comment by matheus23** [comment]
We can start supporting both options and use `/relay` in the client immediately and then later coordinate the breaking change.

**Comment by DAOCUONG** [comment]
Can you explain why we remove derp option we are facing problem today our peer can not connect because iroh server is shutting down

**Comment by flub** [comment]
> Can you explain why we remove derp option we are facing problem today our peer can not connect because iroh server is shutting down

Could you please open a new issue for your problem and describe exactly what happened and maybe provide logs to show how it looked as well?

We're not removing anything in this issue, we are renaming things from "derp" to "relay" and the URL endpoint is one of the things we want to rename.
