### ISSUE TITLE
Dropping a Doc Handle Closes the Connection on Other Doc Handles That Have Been Independently Opened

### ISSUE THREAD

**Issue by zicklag** [n0-computer/iroh#2381]
When you open a document it creates a new document handle that, when dropped, closes the document.

This becomes a problem when you open the same document multiple times, because dropping one will try to close the document, while it's still needed by the other handle. Here's an example of failing code:

```rust
use iroh::node::Node;

#[tokio::test]
async fn creating_and_dropping_iroh_docs() -> anyhow::Result<()> {
    let node = Node::memory().spawn().await?;
    let id = node.docs.create().await?.id();

    // First we open a document
    let doc1 = node.docs.open(id).await?.unwrap();

    {
        // Then we open the same document again
        let doc2 = node.docs.open(id).await?.unwrap();

        // Let's put some data in it just so we have something to try to read later
        doc2.set_bytes(node.authors.default().await?, "hello", "world")
            .await?;

        // This line seems to be necessary to cause the problem in this minimal example,
        // but I think it is just because of timing.
        doc2.close().await?;

        // I'm pretty sure that when doc2 goes out of scope here, it spawns a task to close
        // the document, like the line above does explicitly.
    }

    // Now when I try to read the data using the doc1 handle, it will error with a 
    // "Replica not open" error.
    let value = doc1
        .get_exact(node.authors.default().await.unwrap(), "hello", true)
        .await
        .unwrap();
    assert_eq!(
        dbg!(value.unwrap().content_bytes(&doc1).await.unwrap()),
        "world"
    );

    Ok(())
}
```

The problem is that an `Arc<DocInner>` is use to refcount the handle, but instead of `node.docs.open()` returning a clone of an existing `Arc<DocInner>`, it creates a new one. So now we've got _two_ ref counters, and and when the refcount drops to zero on either of them, it closes the document.

----

Related Code:

https://github.com/n0-computer/iroh/blob/d37a4a4f3c7944200b902dcd822f4c33eb1787a0/iroh/src/client/docs.rs#L155-L162

https://github.com/n0-computer/iroh/blob/d37a4a4f3c7944200b902dcd822f4c33eb1787a0/iroh/src/client/docs.rs#L138-L149

**Comment by Frando** [comment]
You found a bug indeed! #2383 should fix it!
