### ISSUE TITLE
Make logging directory configurable

### ISSUE THREAD

**Issue by crimeminister** [n0-computer/iroh#2388]
In the process of configuring systemd to run `iroh`, I am attempting to use a "dynamic user" to run the service. This effectively sandboxes the service by making the full filesystem read-only except for a specific "state directory" (`/var/lib/iroh` in my configuration). When attempting to run the service with this configuration I see the error:

```
Error: failed to create log directory: Read-only file system (os error 30)
```

I would like to configure iroh to write logs to `/var/log/iroh`, which I will make writable by the systemd "dynamic user" that ends up running the service. Would it be possible to expose the log output directory as a configuration knob?

**Comment by divagant-martian** [comment]
@crimeminister please give https://github.com/n0-computer/iroh/pull/2391 a go if you have the bandwidth to do so

**Comment by matheus23** [comment]
Do we know if there's other files read/written from iroh with non-configurable locations? We'd need to make sure everything is configurable to solve OP's use-case IIUC.

**Comment by dignifiedquire** [comment]
> Do we know if there's other files read/written from iroh with non-configurable locations?

All other files should be written into the main `iroh` folder, which is a single configurable place. I am surprised our logs don't go in there by default

**Comment by divagant-martian** [comment]
our logs go in the `iroh` folder. The use case here is that he wants logs to go somewhere else instead, different to the `iroh` folder

**Comment by crimeminister** [comment]
Thanks for this, everyone! I appreciate the quick and helpful response.
