### ISSUE TITLE
Example feature need to be enabled to run examples

### ISSUE THREAD

**Issue by azzamsa** [n0-computer/iroh#2431]
Hi,

I get this error following the instruction in [/iroh/examples/client.rs#L7](https://github.com/n0-computer/iroh/blob/17c654e59cc2069522a66b87355f52342b837b8c/iroh/examples/client.rs#L7)

```rust
//! run this example from the project root:
//!     $ cargo run --example client
```

Should we change every instruction to include the `--features=examples`?

```diff
//! run this example from the project root:
-//!    $ cargo run --example client
+//!    $ cargo run --features=examples --example client
```

I am ready with a PR.

**Comment by matheus23** [comment]
Yes, that'd be great :)
