### ISSUE TITLE
Make websocket/not websocket choice client-based instead of advertising `wss://` `RelayUrl`s

### ISSUE THREAD

**Issue by matheus23** [n0-computer/iroh#2442]
@flub correctly pointed out [on discord](https://discord.com/channels/949724860232392765/960896793195974708/1257613031609729024):
- Websocket transport is selected based on `wss://` vs. `https://` scheme in the `RelayUrl`
- This means clients would advertise whether they want to use websockets or not in their tickets, even though clients should decide that for themselves only!
- We achieve better compatibility if we announce a single URL
- It's weird to have the `wss://` prefix, given there's also other endpoints like `https://relay.example.org/generate_204`

I think the fix is:
- Make wss or https selection based on a client-side flag (probably in the `ClientBuilder`)
- Always advertise http(s) relay urls.

**Comment by dignifiedquire** [comment]
I think the proposed solution is the right one

**Comment by matheus23** [comment]
I'll put up a fix today, so it'll hopefully make it in before the release on Monday.

**Comment by dignifiedquire** [comment]
Fixed in #2446
