### ISSUE TITLE
bug: "The default author is missing from the docs store, to recover delete the file [...]"

### ISSUE THREAD

**Issue by matheus23** [n0-computer/iroh#2462]
We get this bug in a bunch of places.
Here's a report from @azzamsa in discord:

> Hi, 👋🏻 
>
> 
> If I run this code over and over, I don't get any errors.
> 
> ```rust
>     let storage_path = Path::new(env!("HOME"))
>         .join(".local")
>         .join("share")
>         .join("todos-iroh");
>     let config_path = storage_path.join("todos.cfg");
> 
>     // Initialize node
>     let node = Node::persistent(&storage_path).await?.spawn().await?;
>     let author = node.authors().default().await?;
>     dbg!(&author);
> ```
> 
> but the time I add a logic to load previously created document, I always get `Error: The default author is missing from the docs store. To recover, delete the file /home/user/.local/share/todos-iroh/default-author. Then iroh will create a new default author.`
> 
> ```rust
> async fn init_repo() -> Result<(), crate::Error> {
>     let storage_path = Path::new(env!("HOME"))
>         .join(".local")
>         .join("share")
>         .join("todos-iroh");
>     let config_path = storage_path.join("todos.cfg");
> 
>     // Initialize node
>     let node = Node::persistent(&storage_path).await?.spawn().await?;
>     let author = node.authors().default().await?;
>     dbg!(&author);
> 
>     // Get previous document id
>     let document = match config_path.exists() {
>         true => {
>             println!("Using previous config.");
>             let document_id = fs::read_to_string(config_path)?;
>             let document = node
>                 .client()
>                 .docs()
>                 .open(NamespaceId::from_str(&document_id)?)
>                 .await?;
>             document.expect("can't find document")
>         }
>         false => {
>             println!("Creating new config.");
>             let document = node.client().docs().create().await?;
>             let document_id = document.id().to_string();
>             fs::write(config_path, document_id)?;
>             document
>         }
>     };
> 
>     Ok(())
> }
> ```

There are a bunch of failures in our [Flaky CI tests](https://github.com/n0-computer/iroh/actions/runs/9804155922/job/27071450440) that reproduce this:

> ```
> --- STDOUT:              iroh-cli::cli cli_rpc_lock_restart ---
> 
> running 1 test
> start
> |Iroh is running
> |Node ID: soubiinn7jdejlljcmled4i3s4n7znm4krpgoztjzo3hy4l7jb5q
> killing process
> restart
> |Error: The default author is missing from the docs store. To recover, delete the file `/root/actions-runner/_work/iroh/iroh/target/testdir-0/cli/cli_rpc_lock_restart/data-dir/default-author`. Then iroh will create a new default author.
> Expected 1 matches for regex: Iroh is running
> test cli_rpc_lock_restart ... FAILED
> 
> failures:
> 
> failures:
>     cli_rpc_lock_restart
> 
> test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out; finished in 4.67s
> ```

**Comment by azzamsa** [comment]
Thank you for this 🍰

**Comment by matheus23** [comment]
@azzamsa let me know how it goes :)

**Comment by azzamsa** [comment]
> @azzamsa let me know how it goes :)

So far, I haven't encountered the error message: `Error: The default author is missing from the docs store. To recover, delete the file .../default-author. Then iroh will create a new default author.` I'll report here if it happens again.

Thank you so much for the fix 🍰
