### ISSUE TITLE
iroh-net: When guessing at a direct address we do not always send to the same one

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2480]
When we have a relay connection and some direct addresses, but have not yet figured out any information about those direct addresses - like whether they work- we try to pick a random direct address from the list and send to relay + this guess at the same time.

The idea is that maybe we picked a usable address and it just works and we figure this out and start using this path for real.

However we do not stably select the direct address path, so each time we send a packet a new direct address path is being selected.  That's rather useless.

This is the bug: https://github.com/n0-computer/iroh/blob/4640f4d0049e582cc89d81e976b59961043efb3f/iroh-net/src/magicsock/node_map/node_state.rs#L295

**Comment by flub** [comment]
This is on the hot-path of `.poll_send()`, an RNG is too much overhead for this.

**Comment by zh522130** [comment]
This has led to another issue: when my server has multiple IP addresses, only one of them can successfully punch through (in my tests, it's the IPV6 address), with most being LAN addresses. Due to the random selection of direct connection addresses currently, the probability of the correct IP address for successful punching being chosen is very low, relying entirely on luck. Sometimes, it takes a long time before my IPV6 is used for testing (I even began to wonder if the protocol dislikes IPV6, haha). I have attached a complete log. In my opinion, for early punching, LAN IPs might need a higher priority, but since LAN success rates are already high, if a LAN connection is not successful within a certain time (as soon as possible), more opportunities for punching through with public IPs should be given. This is also related to the  https://github.com/n0-computer/iroh/issues/2317

**Comment by zh522130** [comment]
> This has led to another issue: when my server has multiple IP addresses, only one of them can successfully punch through (in my tests, it's the IPV6 address), with most being LAN addresses. Due to the random selection of direct connection addresses currently, the probability of the correct IP address for successful punching being chosen is very low, relying entirely on luck. Sometimes, it takes a long time before my IPV6 is used for testing (I even began to wonder if the protocol dislikes IPV6, haha). I have attached a complete log. In my opinion, for early punching, LAN IPs might need a higher priority, but since LAN success rates are already high, if a LAN connection is not successful within a certain time (as soon as possible), more opportunities for punching through with public IPs should be given. This is also related to the #2317这就导致了另一个问题：当我的服务器有多个IP地址时，只有其中一个能够成功打通（在我的测试中是IPV6地址），而且大多数都是LAN地址。由于目前直连地址的选择是随机的，选择正确的打卡成功IP地址的概率很低，完全靠运气。有时，我的IPV6需要很长时间才能用于测试（我什至开始怀疑该协议是否不喜欢IPV6，哈哈）。我附上了完整的日志。我认为，对于早期打卡，局域网IP可能需要更高的优先级，但由于局域网成功率已经很高，如果在一定时间内（尽快）局域网连接不成功，与公众打通的机会更多应该给出IP。这也与 #2317 有关
> 
> [logs_1720497577.log 日志_1720497577.log](https://github.com/user-attachments/files/16137952/logs_1720497577.log)

I'm not sure if this is related to the issue, but my thought is that the address selection strategy might need to be optimized.

**Comment by flub** [comment]
> This has led to another issue: when my server has multiple IP addresses, only one of them can successfully punch through (in my tests, it's the IPV6 address), with most being LAN addresses. Due to the random selection of direct connection addresses currently, the probability of the correct IP address for successful punching being chosen is very low, relying entirely on luck. Sometimes, it takes a long time before my IPV6 is used for testing (I even began to wonder if the protocol dislikes IPV6, haha). I have attached a complete log. In my opinion, for early punching, LAN IPs might need a higher priority, but since LAN success rates are already high, if a LAN connection is not successful within a certain time (as soon as possible), more opportunities for punching through with public IPs should be given. This is also related to the #2317
> 
> [logs_1720497577.log](https://github.com/user-attachments/files/16137952/logs_1720497577.log)

I think this is a misunderstanding, for **holepunching** it does not guess a random address.  It uses all the addresses for holepunching.  It does take a long time to holepunch in this log and I need need check it out more to fully understand.  But let's move this part back to #2317.
