### ISSUE TITLE
Documentation for `Endpoint.accept` is unclear: why can it return None?

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2488]
[`Endpoint.accept()`](https://docs.rs/iroh-net/0.20.0/iroh_net/endpoint/struct.Endpoint.html#method.accept) returns an [`Accept` future](https://docs.rs/iroh-net/0.20.0/iroh_net/endpoint/struct.Accept.html) which has `Option<Connecting>` as output. I have seen that it is used like `while Some(conn) = endpoint.accept().await`, but I don't see any documentation on when it is possible that `None` is returned. Does it only happen if `Endpoint.close()` was called?

**Comment by flub** [comment]
Yes, `None` is returned if the endpoint is closed.

Thanks for pointing out this is not well documented, I'll improve it.
