### ISSUE TITLE
feat: public Iroh API

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#250]
A well-documented and well-reasoned API, that documents where it splits from any ingrained IPFS expectations.

* [x] merge #240, which establishes our first pass of the public API
* [ ] document public API (https://blog.guillaume-gomez.fr/articles/2020-03-12+Guide+on+how+to+write+documentation+for+a+Rust+crate)
* [ ] establish `iroh-ctl` cli api
* [ ] use `iroh` api to power `iroh-ctl` and `iroh-one` command line tools

**Comment by b5** [comment]
This issue has fallen out of date. We have our v0.1.0 CLI API documented: #291, and an issue to track how `iroh` and `iroh-api` crates are organized #314. I'm going to close this in favour of #314
