### ISSUE TITLE
Documentation: Documentation does not include example of downloading document to data folder

### ISSUE THREAD

**Issue by haltingstate** [n0-computer/iroh#2502]
1. I set data folder with env

2. I added the document

3. Document shows up in list

4. The data folder is absolutely empty

----

The tutorial or example MUST include example of downloading or fully syncing the data in a document.

Should data be downloaded automatically? Should the data folders be empty?

What command do you run to actually download the document file contents or sync them?

**Comment by dignifiedquire** [comment]
> * I set data folder with env
> *

can you please describe which commands you exactly ran?

**Comment by divagant-martian** [comment]
We added a section to clarify documents storage. Iroh handles its own storage. You can import and export data out of it. This is described in https://iroh.computer/docs/layers/documents#storage and in https://iroh.computer/docs/api#document-commands with (`doc export` and `doc import`). For blobs there are similar commands (`blob export` and `blob add`)
