### ISSUE TITLE
iroh-relay: error is not useful when metrics port is already bound

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2507]
I had port 9090 already used on the server.
Because of this `iroh-relay` failed to start with error:
```
ERROR iroh_net::relay::iroh_relay: Task failed err=Address already in use (os error 98)
```

This error does not tell which port it fails to use and does not tell anything about metrics server.
Probably some anyhow context should be added here:
https://github.com/n0-computer/iroh/blob/f84c06eb87ed8b93b1bce71c8502732db7faeedb/iroh-metrics/src/metrics.rs#L54

I solved the problem by setting `metrics_bind_addr = "127.0.0.1:9092"`, but the error was not very helpful, I only figured out it is metrics by trial and error, trying to disable metrics/http/https/stun one by one.

**Comment by Arqu** [comment]
I'll add this to my incoming PR redoing some of the metrics bits.
