### ISSUE TITLE
iroh-cli: allow `--switch` outside of `iroh console`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [n0-computer/iroh#2535]
Currently, `--switch` flags don't work outside of the Iroh CLI console.

I want to suggest setting env variables for `IROH_AUTHOR` and `IROH_DOC` when a command with `--switch` is ran in the terminal.

Would the Iroh team be interested in a PR implementing this?

**Comment by flub** [comment]
https://github.com/n0-computer/iroh/blob/main/iroh-cli/src/config.rs#L25-L26

**Comment by flub** [comment]
Admittedly this is not documented AFAIK, this is being changed in https://github.com/n0-computer/iroh.computer/pull/166

**Comment by Frando** [comment]
I don't think it is possible to make a process set environment variables in the surrounding shell?

**Comment by KAAtheWiseGit** [comment]
Oh, right, I was working with Nushell and completely forgot it wasn't possible to set environmental variables in standalone commands.

I totally agree with not storing per-process data, it's too opaque.  Will close the issue, as I don't see a good way to implement switching either.
