### ISSUE TITLE
Allow customizing the `quinn::TransportConfig` in `iroh::node::Builder`

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#2592]
The `iroh::node::Builder` sets the `max_concurrent_uni_streams` to 0 (i.e. none) and `max_concurrent_bidi_streams` to 10 (i.e. barely any).

Furthermore it does not allow customising these values.

- It should not set default values other than the Quinn defaults probably.
- It should allow for a custom `TransportConfig` to be used.

**Comment by matheus23** [comment]
#2593 fixes the first point, but does not yet allow for a custom `TransportConfig`. Editing the title.

**Comment by divagant-martian** [comment]
We have https://github.com/n0-computer/iroh/blob/1d3f3fa8125761df509b94621eb173b91ed42904/iroh-net/src/endpoint.rs#L214-L225 which has been around for awhile. You updated it's docs in #2334 and I thought it was added in that PR due to re-ordering but it was added in #1133, more than a year ago.

Is there something else missing?

**Comment by matheus23** [comment]
Oh, I missed that. In that case we can probably close this, right?

**Comment by flub** [comment]
> We have
> 
> https://github.com/n0-computer/iroh/blob/1d3f3fa8125761df509b94621eb173b91ed42904/iroh-net/src/endpoint.rs#L214-L225

This is in iroh-net.  The issue is about the `iroh::node::Builder` which I think is distinct from using iroh-net on it's own.

I'm not really sure about what should be in the `iroh::node::Node`, but I gather it's a larger system that build on iroh-net but still allows you to drop down to iroh-net and write your own additional protocols.

**Comment by divagant-martian** [comment]
that makes sense, thanks!
