### ISSUE TITLE
flaky test: iroh-cli::cli cli_rpc_lock_restart (macos)

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2644]
https://github.com/n0-computer/iroh/actions/runs/10451887810/job/28939192142?pr=2643
https://github.com/n0-computer/iroh/actions/runs/10456841664/job/28955119602

**Comment by matheus23** [comment]
Logs for the first run of those two: [logs_27326248344.zip](https://github.com/user-attachments/files/16670586/logs_27326248344.zip)
Logs for the second run of those two: [logs_27339927937.zip](https://github.com/user-attachments/files/16670611/logs_27339927937.zip)

**Comment by dignifiedquire** [comment]
Closing, as we have removed `iroh-cli`
