### ISSUE TITLE
console/cli is missing listing the contents of a collection

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh#2658]
the `blobs::Client` has `pub async fn get_collection(&self, hash: Hash) -> Result<Collection>` for which there is no matching counterpart in the cli/console.

The `Collection` type has a lot of manipulation methods we probably do not want to map. However, a `blobs collection <hash>` which lists the blobs (by calling `pub fn iter(&self) -> impl Iterator<Item = &(String, Hash)>`) I think is both useful enough, and close enough to the rust api to be a good match to this top level client function

**Comment by divagant-martian** [comment]
@dignifiedquire @b5 do you guys think we should add this api to the cli? @palozano is already familiar with the cli code so this could be easy for him to do

**Comment by dignifiedquire** [comment]
sounds good to me 👍

**Comment by dignifiedquire** [comment]
Closing, as we have removed `iroh-cli`
