### ISSUE TITLE
NYM support for iroh-net

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#2687]
There are various upcoming and existing private transport mechanisms that would be nice to plug in to iroh.

Notable examples are probably [NYM](https://nymtech.net/) and [Veilid](https://veilid.com/) and [dark.fi](https://dark.fi/)

We probably do not want to directly depend on these projects for various reasons, but it would be really great if we could publish an iroh-examples example how to integrate with them.

Just like we have a "choose your own level of reliance on p2p" approach with the node discovery, with the default option DNS but full p2p discovery easily pluggable, we should default to direct transports but have a way to easily plug in more private transports.

Edit: of course if this is flexible enough it would also allow plugging in tor...

This https://github.com/n0-computer/iroh/issues/2228 would be a prerequisite for NYM support.

**Comment by flub** [comment]
we'll keep the #2228 issue and this can follow on if there's demand at that point
