### ISSUE TITLE
iroh get command

### ISSUE THREAD

**Issue by faassen** [n0-computer/iroh#269]
## Discussion proposal

`iroh-ctl get <ipfs-path> [<path>]`

- `ipfs-path` can be a true IPFS path, or a CID
- `path` is a filesystem path and is optional. If it’s not supplied, path is set to the `CID`.

Download file or directory from IPFS into `path`. If `path` already exists and is a file then it’s overwritten with the new downloaded file. If `path` already exists and is a directory, the command fails with an error. If `path` already exists, is a file and the downloaded data is a directory, that’s an error

### Differences with Kubo:

- `ipfs get` has an `--output` flag, instead we have a second optional `path` argument.
- `ipfs get` downloads into `--output` if that output path already exists and is a directory. We consider that an error. The motivation is that it’s while it mirrors the behavior of Unix `cp`, we can’t fully mirror `cp` because we don’t always have the source file name or directory, and it risks creating an accidental nested directory structure when you repeatedly download.
- `ipfs get` silently overwrites the directory if no `--output` was given. Instead of silently overwriting, we choose to present the user with an error so that the behavior of the omitted `path` is identical to when you supply one.
- We don’t support compression of downloaded content; you can do that with a separate tool.

## Test cases

- [x] get with CID -> ok
- [x] get with something that looks like a CID but isn't -> error
- [x] get with IPFS path that points to a CID -> ok
- [x] get with IPFS path that doesn't point to a CID ->  error
- [x] get wrapped file
- [x] get unwrapped file
- [ ] get unwrapped file, overwrites previous
- [x] get directory without explicit path
- [x] get directory with explicit path
- [x] get directory without explicit path, previous file/directory already there -> error
- [x] get directory with explicit path, previous file/directory already there -> error
- [ ] get a file with an ipfs path: `iroh get cid/a/b` where `b` is a file
- [ ] get a directory with an ipfs path `iroh get cid/a/b` where `b` is a directory
- [ ] fail to get a file/directory with an ipfs path `iroh get cid/a/b` where b doesn't exist

## Questions

- [ ] get with CID that doesn't exist -> not sure how to test this; I tried a made up CID with Kubo and it's just hanging looking for it. Can we determine a CID doesn't exist?

**Comment by b5** [comment]
Looks great to me. I'd like to advocate for one flag that will help users see just how terrible network fetching is:

```
--force-fetch  ignore local cache & fetch all data from the network
```

Often new users to IPFS will be confused by the wild swings in fetching time, and then can't reproduce their problem once they actually manage to resolve the content once (b/c cache is permanent). Adding this flag makes that conversation easier. Also, iroh developer friendliness.

**Comment by b5** [comment]
Full help text, updated on [this branch](https://github.com/n0-computer/iroh/tree/b5/cli_docs_spike/iroh/src):

```
iroh-get
Fetch IPFS content and write it to disk

USAGE:
    iroh get [OPTIONS] <ipfs-path> [output]

ARGS:
    <ipfs-path>    CID or CID/with/path/qualifier to get
    <output>       filesystem path to write to. Default: $CID

OPTIONS:
        --force-fetch    ignore local cache & fetch all content from the network
    -h, --help           Print help information


Download file or directory specified by <ipfs-path> from IPFS into [path]. If
path already exists and is a file then it's overwritten with the new downloaded
file. If path already exists and is a directory, the command fails with an
error. If path already exists, is a file and the downloaded data is a directory,
that's an error.

By default, the output will be written to './<ipfs-path>'.

If <ipfs-path> is already present in the iroh store, no network call will
be made.
```

**Comment by faassen** [comment]
I'm going to write some test cases down here:

* get with CID -> ok
* get with something that looks like a CID but isn't -> expect error
* get with IPFS path that points to a CID -> ok
* get with IPFS path that doesn't point to a CID -> expect error
* get with CID that doesn't exist -> not sure how to test this; I tried a made up CID with Kubo and it's just hanging looking for it. Can we determine a CID doesn't exist?

**Comment by faassen** [comment]
Here are some tests that test file system effects. The CLI tests can't handle those at present, as this happens within the API implementation:

* get file without explicit path
* get file without explicit path, overwrites previous
* get file with explicit path
* get file with explicit path, overwrites previous
* get directory without explicit path
* get directory without explicit path, previous file/directory already there -> error
* get directory with explicit path, previous file/directory already there -> error

The directory overwrite tests that error out can be tested in the current CLI, as it has all the information to do the check ahead of time. 

Any other tests require a refactoring: the API should *not* write files but instead deliver a stream of files which can then be mocked, and then the CLI actually writes the files itself. The code that actually writes the files too should *also* be accessible in the API, because that's a common use case for the API. The code to get the stream and write the files already lives in the API, so it should be possible to rewrite it.

**Comment by faassen** [comment]
@b5 regarding `--force-fetch`, I don't know how to control this yet so I'm leaving that out for now.

**Comment by b5** [comment]
> regarding --force-fetch, I don't know how to control this yet so I'm leaving that out for now.

Absolutely. Feel free to punt on any flags that seem even remotely complex for now. We can break them out into separate issues later, and either they make the release, or they don't.

**Comment by faassen** [comment]
It turns out that getting unwrapped files overwriting an existing file without erroring out (like any other scenario) is harder to implement than I anticipating, and it makes me question whether it's worthwhile and whether we shouldn't simply fail in that case too. What do you think @b5?

The reason it's harder to implement is because we get a stream and we don't know in advance whether it contains just a single file or a bunch files and directories. Only in the form case when the only element is a file, should we overwrite. But knowing that requires consuming the stream. So it turns out it's easier to either always overwrite or never. I choose never overwrite as always overwrite is more dangerous and there are some tricky issues (do we remove files and directories that don't exist in what we're downloading?).

**Comment by b5** [comment]
> It turns out that getting unwrapped files overwriting an existing file without erroring out (like any other scenario) is harder to implement than I anticipating

Yep, let's totally punt & just error out.

**Comment by faassen** [comment]
Clap derive by default produces this help text:

```
Usage: iroh get <IPFS_PATH> [OUTPUT]

Arguments:
  <IPFS_PATH>  CID or CID/with/path/qualifier to get
  [OUTPUT]     filesystem path to write to. Default: $CID

Options:
  -h, --help     Print help information
  -V, --version  Print version information
```

One difference here is that in our spec we have `ipfs-path` as opposed to `IPFS_PATH`. I'm looking for a way to control how clap derive generates this but no luck yet.
