### ISSUE TITLE
Return chunk with available length even if requested larger.

### ISSUE THREAD

**Issue by islamaliev** [n0-computer/iroh#2738]
When calling `iroh_client.blobs().read_at_to_bytes` after [this fix](https://github.com/n0-computer/iroh/issues/2728) it checks if chunk at the given `offset` exists with at least given `len`. It's a bit inconvenient when you know how many chunks you have, but don't know the size of the last one.
It would be better if the given `len` parameter was considered as "give me this or whatever is remaining".
Users can check on their side the length of returned `Bytes`.

**Comment by dignifiedquire** [comment]
You can already do this I believe, by just passing `None` as length parameter, and it should return you the rest of the data

**Comment by islamaliev** [comment]
For my case I deal with chunks of certain size (1024 bytes). But the blog is not 1024-aligned. So I want to be able to request any chunk of size 1024, but if it happens to be the last one that it doesn't error out.
