### ISSUE TITLE
Document behaviour when a subscriber for Discovery::subscribe is lagging

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#2791]
You can subscribe to Discovery::subscribe multiple times. Document the expectations about what happens is one of these subscriptions is lagging.

Maybe also change the implementation to properly deal with lag.

**Comment by divagant-martian** [comment]
Closed by #2794

**Comment by divagant-martian** [comment]
Closed by https://github.com/n0-computer/iroh/pull/2794
