### ISSUE TITLE
ParseTicket functionality?

### ISSUE THREAD

**Issue by cblgh** [n0-computer/iroh#2803]
o/

when reasoning through functionality provided by Iroh's SDKs, i noticed that while you can create e.g. blob tickets with `blobs.share()`, there currently seems to be no way to parse a ticket string received out-of-band into e.g. a BlobTicket representation. for example, here's how `ticket.iroh.computer` currently parses ticket information: 

https://github.com/n0-computer/ticket.iroh.computer/blob/main/src/ticket/ticket.ts

that seems like a lot of boilerplate (e.g. implementing Postcard {de,}serializing) to require each SDK-using project to write, at least given the otherwise turnkey nature of the SDKs.

am i missing something obvious or is this a potential hole that Iroh's core could fill? for example with functionality like below, which could then be exported into the SDKs for others to use.

```
parseTicket(string) -> { ticket, type: BlobTicket | NodeTicket | DocTicket }
```

**Comment by flub** [comment]
* `BlobTicket` impls `FromStr` so `let blob: BlobTicket = "the_ticket".parse()?;` should work
  * The `Display` impl is the counterpart of this as is customary in rust.
* `BlobTicket` impls `Ticket` so `let blob = BlobTicket.deserialize("the_ticket")?; should work.
  * There are a few more useful methods on the `Ticket` trait.

**Comment by cblgh** [comment]
@flub cheers! just so that i'm understanding this correctly, would the equivalent method in e.g. the Kotlin SDK be to simply call `BlobTicket("the ticket")`? basing this on [iroh_ffi.kt#L5716](https://github.com/n0-computer/iroh-ffi/blob/5eeec2f424c989b9b302c416b277d1e6f4736dc2/kotlin/iroh/iroh_ffi.kt#L7792-L7800)

**Comment by flub** [comment]
Sorry, I'm not sure how ffi or kotlin works... maybe @ramfox or @dignifiedquire can help here.  The link you give explicitly says it's only for tests, so I doubt it will work as you suggest.

**Comment by cblgh** [comment]
>  The link you give explicitly says it's only for tests, so I doubt it will work as you suggest.

i think the test only constructor is:
```kt
    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }
```

while 

```kt

    constructor(`str`: kotlin.String) :
        this(
            uniffiRustCallWithError(IrohException) { _status ->
                UniffiLib.INSTANCE.uniffi_iroh_ffi_fn_constructor_blobticket_new(
                    FfiConverterString.lower(`str`),
                    _status,
                )
            },
        )
```

seems to be functional from what little i can grok; the `[.....]fn_blobticket_new` call seems like it is performing useful work. but yes, a word from the ffi sages would be fantastic :]
