### ISSUE TITLE
Remove secret_key from iroh-relay.toml?

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2845]
I am adding iroh-relay deployment to chatmail: https://github.com/deltachat/chatmail/pull/434

It looks fine, but iroh-relay needs write access to the config file to overwrite it with a new version that has a secret_key. If secret_key can be generated from scratch anyway, why store it in the config and not generate it one the application start?

**Comment by dignifiedquire** [comment]
> why store it in the config and not generate it one the application start?

because otherwise the identity of the relay server would change everytime you restart it

**Comment by dignifiedquire** [comment]
> Now the key changes every time I redeploy the relay and it does not seem to break anything.

Sure that's your choice, but the goal of this is to not have that by default

**Comment by dignifiedquire** [comment]
I think nothing, started looking at the code and it turns out the secret key is dead code 🤣

**Comment by dignifiedquire** [comment]
Okay, it's not entirely dead code, but we can likely still drop it, need to do some more investigation

**Comment by dignifiedquire** [comment]
Fix will be in the next release
