### ISSUE TITLE
update all crates.io dependencies

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2883]
Need to do a review of all existing dependencies and update them where possible & appropriate.

**Comment by dignifiedquire** [comment]
@Arqu I am assuming your dependency cleaning does this, right?

**Comment by Arqu** [comment]
Yes, I'm slowly crawling through the mess trying to eliminate unused ones, reduce duplicates and just overall bump and clean up everything.

**Comment by Arqu** [comment]
ref https://github.com/n0-computer/iroh/pull/2932
