### ISSUE TITLE
iroh-router requires tokio 1.41

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2887]
Is this on purpose?
https://github.com/n0-computer/iroh/blob/50661022258e607775af6e6b83c4c25fc57ed088/iroh-router/Cargo.toml#L19

Other crates just depend on tokio version 1. I noticed because deltachat-core-rust still depends on tokio 1.38:
https://github.com/deltachat/deltachat-core-rust/blob/dface33699b7a8dc0eda2c87a2a72d789d80b038/Cargo.toml#L190-L195

Will update tokio anyway, but this too specific dependency in iroh-router looks strange.

**Comment by Arqu** [comment]
Done in #2932
