### ISSUE TITLE
Unmaintained proc-macro-error dependency

### ISSUE THREAD

**Issue by link2xt** [n0-computer/iroh#2889]
cargo-deny is unhappy because `genawaiter` (https://rustsec.org/advisories/RUSTSEC-2024-0370)  introduced unmaintained dependency:
```
proc-macro-error v0.4.12
└── genawaiter-proc-macro v0.99.1 (proc-macro)
    └── genawaiter v0.99.1
        └── iroh-net v0.28.1
```

This dependency did not exist in iroh-net 0.26.

Seems to be introduced in 9facd5a333b545c7b036e6f7ce13a150e6aca492

**Comment by dignifiedquire** [comment]
there is no way to fix this unfortunately, we have to ignore it

https://github.com/n0-computer/iroh/blob/main/deny.toml#L35
