### ISSUE TITLE
refactor bitswap to preserve connectivity with kubo nodes running go-bitswap

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#292]
Based on our testing, there is practical drift between bitswap the spec and go-bitswap. When running on the public IPFS network, Kubo nodes prune connections that don't follow the contours of _go-bitswap_, which is killing iroh's capacity to meaningfully exchange blocks on the public IPFS network.

The best solution we've been able to come up with is a line-by-line port of go-bitswap, which @dignifiedquire is taking on [here](https://github.com/n0-computer/iroh/tree/bitswap2). This issue tracks landing an initial port of go-bitswap into iroh.

**Comment by ec1oud** [comment]
I see if I add a file to iroh, kubo on the same machine cannot find that cid.  I guess this is why?

This seems critical for the release then?
