### ISSUE TITLE
Add support for "Linux aarch64" to quickstart.sh

### ISSUE THREAD

**Issue by owocean** [n0-computer/iroh#302]
Was trying to install this lovely software on my raspberry pi 3b, but the quickstart script was unable to launch iroh-store. I tried running it manually and found out it was running a binary for the wrong architecture.   
`$ uname -sm` returns `Linux aarch64` which isn't in the switch statement, causing it to default to amd64. Pretty simple fix, but I couldn't find the script in this repository so I couldn't make a pullreq

**Comment by Arqu** [comment]
I should get to this over the next few weeks.

**Comment by b5** [comment]
Thanks for filing @owocean! We're heads-down trying to get an initial release of iroh out the door in ~2 weeks. We'll definitely get this fixed, but it'll have to wait until after the release, as the script is part of our ops infra.

In the meantime, are you able to build `iroh-store` for your arch from source? We'd hate to see you totally blocked on this :)

**Comment by owocean** [comment]
yeah i was able to build it :) thanks for all your hard work! 

I noticed that you've planned to delete `iroh-ctl` and replace it with `iroh-one`. Should I build that instead? Supposed to have everything bundled together?

**Comment by b5** [comment]
You shouldn't need to, and you'll always be able to run either of `iroh one` and `iroh-{gateway,p2p,store}`.

After talking it through, we're planning to effectively rename `iroh-ctil` to just `iroh`. Full rationale: https://github.com/n0-computer/iroh/issues/274#issuecomment-1272029165

**Comment by Arqu** [comment]
Updated the setup script. Will eventually make it public too.
Thanks for the report!
