### ISSUE TITLE
`iroh-ctl p2p peer-id` does not exist on x86_64 build

### ISSUE THREAD

**Issue by owocean** [n0-computer/iroh#303]
Running `iroh-ctl p2p peer-id` on aarch64 returns the ID of my node. Running the same command on x86_64 does not. It doesn't even show up in the help menu. Both `iroh-ctl-p2p` versions are on `0.1.0`

**Comment by Arqu** [comment]
I assume you used some of the setup scripts with prebuilt binaries?

If that's so, the mac binaries are a bit out of date. They should sync back up next week when I do the CI portion of it.

**Comment by owocean** [comment]
ah I should have mentioned im on Linux for both machines. Fedora 36 for the x86_64 machine and Raspbian for the aarch64

**Comment by Arqu** [comment]
Oh, thanks for the input. I'll double check the script/CI to make sure it's not a technicality. Otherwise @faassen might know more than I do on this topic.

**Comment by faassen** [comment]
I don't yet know what's going on here; the CLI is still heavily in flux. I just removed the `peer-id` CLI in general as we're stripping down the CLI before we build it up again.

**Comment by Arqu** [comment]
Binaries should be up to date and in sync now.
