### ISSUE TITLE
Allow addition of arbitrary meta-data to discovery via key-value TXT pairs like mDNS

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [n0-computer/iroh#3037]
Allow the addition of meta-data to discovery via an arbitrary number of key-value TXT pairs like mDNS allows.
Then in the "client" (discoveree) then be able to get the values via key, or iterate through them.

Reference implementations for mDNS:
- https://docs.rs/mdns-sd/latest/mdns_sd/ (called "properties) (https://docs.rs/mdns-sd/latest/mdns_sd/struct.ServiceInfo.html)
- https://docs.rs/edge-mdns/latest/edge_mdns/host/struct.Service.html (called "text_kvs")

**Comment by andrewdavidmackenzie** [comment]
DUPLICATE

**Comment by matheus23** [comment]
Duplicate of #3002, specifically
