### ISSUE TITLE
cli booleans avoid negatives

### ISSUE THREAD

**Issue by faassen** [n0-computer/iroh#310]
b5 wrote on #270 

> Instead of --no-wrap I'd prefer --wrap, which defaults to true. 
> IMHO using negation in boolean flag labels is confusing:
> --wrap=false is clearer than --no-wrap

I agree and would like to make it work this way, but Clap doesn't do this out of the box, so I've created a separate issue to figure this out.

What works is this (where the flag defaults to true):

```rust
/// Track metrics
#[clap(long, action = clap::ArgAction::Set, default_value_t=true)]
metrics: bool
```

Note that this does *not* support `--metrics` by itself, only with explicit `=true` and `=false`. I think that's acceptable for flags that default to `true`.

Documentation generated by Clap seems reasonable:

```
     --metrics <METRICS>  Track metrics [default: true] [possible values: true, false]
```

For flags that default to `false` we can use Clap's normal flag mechanism:

```rust
/// Verbose mode
#[clap(long, short = 'v')]
verbose: bool,
```

Documentation is like this:

```
 --verbose            Verbose mode
```

Note that this is a true Clap flag: it's only used to enable something, and you can't use an explicit `true` or `false`.

I wanted to highlight this difference, though I think it's acceptable. If we want to stick with true Clap flags for the "flag is turned on by default" use case, we  *have* to take the `--no-` flags route instead.

## Relevant Clap issues & PRs

The general explicit flag story:

https://github.com/clap-rs/clap/issues/1649

Automatic support for `--no` flags. Isn't implemented.

https://github.com/clap-rs/clap/issues/815

This misdirected me for a bit but has to do with environment variable parsing, so it not related:

https://github.com/clap-rs/clap/pull/2664

**Comment by b5** [comment]
hmmm, now that I think about it, I'm not a massive fan of mixing "true clap flags" and "boolean clap flags". I'd prefer only "true clap flags", and you're saying the only way to do that is to go the `--no` route?

**Comment by faassen** [comment]
You either have a boolean option, ehich can default to true, and they always need a value, and have no single letter flag (as value is required)

Or clap flag which takes no value, defaults to false, and can have a single letter version.

**Comment by faassen** [comment]
I've gone for explicit `--no-wrap` as opposed to `--wrap=false`, with no single letter shortcut, because:

* you're not a massive fan of mixing

* true clap flags are easier to express with Clap

* `--wrap=true` would never be used anyway, so we really only need one flag `--no-wrap`

* It doesn't matter there's no shortcut because we didn't have one for `--wrap=false` either.

**Comment by b5** [comment]
At this point I think we've learned that using `--no-wrap` is more consistent with what clap wants to do under the hood, and while it might be a small UX hit, the lack of bugs caused by going against the grain of the library we're built on should be factored in as well. `--no-wrap` it is, and negation-worded flags should be allowed in the CLI, just avoided if possible.
