### ISSUE TITLE
CLI & Rust API crate organization

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#314]
@dignifiedquire @faassen & I have come to consensus on how to organize crates at the top level of the Iroh project:

- `iroh` will be the CLI crate.
- `iroh-api` will contain the rust API to iroh.
- `iroh` will import `iroh-api`, `clap`, and that's about it. All types needed to interact with iroh must be exported by `iroh-api`

This should clear up confusion that's arisen on a few issues:
- #224
- #267
- #281
- #296
- #313 
- #314  
- #316

Let's mark this as closed once the rough crate organization matches this decision.

**Comment by faassen** [comment]
I'll note that this PR already goes in the direction of making `iroh-ctl` only depend on the API:

https://github.com/n0-computer/iroh/pull/316

While I'm writing I realize I can also depend on Api for cid and a few other things, will update the PR.

**Comment by faassen** [comment]
With #321 this is now done
