### ISSUE TITLE
Write database consistency tests

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#318]
RocksDB is a very low level key value store. Since it does not enforce complex invariants like a relational DB, we need to be sure we do this correctly.

Write a property based test that does operations on the database and checks invariants. Such a test can also serve as good and up to date documentation about what invariants there are in the first place.

Operations on the DB should be done using the public interface, then an internal consistency check (yet to be written) should be called after a sufficiently large number of operations.

**Comment by b5** [comment]
@rklaehn, do you think this is closable?
