### ISSUE TITLE
dir template bad link

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#362]
<img width="573" alt="Screenshot 2022-10-18 at 18 08 50" src="https://user-images.githubusercontent.com/1760977/196484807-c8243ca5-98c9-4e98-82ab-398c8051c7bd.png">

Clicking on the index of ... link goes to a broken url.

**Comment by dignifiedquire** [comment]
lol, all pieces (if there are multiple) don't work

**Comment by b5** [comment]
problem is here:
https://github.com/n0-computer/iroh/blob/bd68e487ed0d0e07806f36eea4f4d8b5edcdef85/iroh-gateway/src/handlers.rs#L690

first slash needs to go away
