### ISSUE TITLE
responses from racing gateways should error out immediately, warn user they should consider removing the gateway

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#400]
We should do this & demo this. Users need to know front & center if a gateway ever provides an invalid response. on the HTTP gateway, this should be a rendered HTML template with advice that says "you should consider removing X from the list of gateways you fetch content" and provide a link to instructions for editing their config

**Comment by fabricedesre** [comment]
You mean an invalid 200 response? You can get transient 5XX with some html content ("OpenResty error" or similar) from eg. dweb.link when it's overloaded, but it's not a reason to fully ban it.

**Comment by b5** [comment]
Yeah, I started playing with this, and there are just too many situations where the hash won't match for this to be a tenable solution. Closing as not-doing
