### ISSUE TITLE
How is the progress?

### ISSUE THREAD

**Issue by slavuwu** [n0-computer/iroh#429]
Hey 👋.

This isn't really an issue, but I wasn't sure where else to put this, as this seems to be the only platform for communication. I just wanted to know how the progress is going, and whether the end-of-october release target for iroh (and documentation) is still more or less valid? 

:)

**Comment by b5** [comment]
👋 @slavuwu! Thanks for asking ☺️. We are still planning on an October release, in the next day or so in fact. I’ll close this issue once we’ve cut the release to keep you in the loop.

As for a discussion platform, I’m thinking we may use the discussion feature here on GitHub. I’ll be spending time bootstrapping discussion over there once we have a release up, so feel free to keep the conversation going over there

**Comment by slavuwu** [comment]
@b5 Thanks for the reply. Glad everything is going as planned. I'm very excited for the release! 😁

**Comment by b5** [comment]
Hey @slavuwu! We cut the release! here's a video of us pushing the release button on stage: https://youtu.be/HRYREdsLt5k?t=133 installation instructions are available over at https://iroh.computer/install
