### ISSUE TITLE
docker mvp

### ISSUE THREAD

**Issue by gotjoshua** [n0-computer/iroh#439]
I'd like to add a /docker/ folder with Dockerfile and docker-compose examples

I see in the docs that its mentioned, but don't see any issues.

Is anyone working on this?

If not, any advice and/or encouragement for me?

**Comment by gotjoshua** [comment]
Started on this

https://github.com/n0-computer/iroh/compare/main...onezoomin:iroh:main

it works if i bind the port and access directly via http
http://iroh.1zm.in:9050/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?filename=test.jpg

and if i access via traefik reverse proxy on https 
https://iroh.1zm.in/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?filename=test.jpg

cheers

**Comment by b5** [comment]
Amazing! Thank you @gotjoshua! We'd welcome a PR that introduces dockerfiles, and can wire builds up to CI

**Comment by gotjoshua** [comment]
So far, no ci, but i can ask @tennox if he's up for that part. 

I'll split the work into separate issues/PRs

This one for the MVP (just using the quick start instructions in a simple docker setup)

One for CI (likely to use gitlab for this)

One for docker production details, to split the services in docker compose and use a non root user

Maybe one for live hacking, that uses the development instructions, but not sure about that one. Could be better to make the repo gitpod ready... Tbd.

**Comment by gotjoshua** [comment]
@b5 questions for you about the setup.sh

Are you building and posting manually to https://vorc.iroh.computer/bin/ ?
Do you have versions also there?

I am using that fetch and run strategy for the MVP, but version pinned reliably built binaries will be needed/desirable for publishing images to container registries...
