### ISSUE TITLE
raw block response fails hash verification

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#456]
When running as a racing gateway iroh fails the the block hash verification for raw. 
`bafybeifffvqarrkavsdg664bluuci3ojmmda6st73icfjgzqbb7ffhlkwi`

**Comment by Arqu** [comment]
@b5 think I got to this. To confirm, can you possibly recall or share the *exact* `http_resolvers` address you passed in?

**Comment by lidel** [comment]
Unable to reproduce, gateway returns exactly the same bytes as getting raw block:

```console
$ ipfs block get bafybeifffvqarrkavsdg664bluuci3ojmmda6st73icfjgzqbb7ffhlkwi > expected
$ curl "http://127.0.0.1:8080/ipfs/bafybeifffvqarrkavsdg664bluuci3ojmmda6st73icfjgzqbb7ffhlkwi?format=raw" > local_curl
$ curl "https://ipfs.io/ipfs/bafybeifffvqarrkavsdg664bluuci3ojmmda6st73icfjgzqbb7ffhlkwi?format=raw" > ipfs.io_curl

$ diff -s expected local_curl
Files expected and local_curl are identical
$ diff -s expected ipfs.io_curl
Files expected and ipfs.io_curl are identical
```

@Arqu  I suspect you are comparing `dag-pb[Data].Data` field with the entire `dag-pb` block? You may want to look at https://github.com/ipfs/specs/pull/331 which explains internals of dag-pb blocks.
