### ISSUE TITLE
iroh API methods should not write or read to disk

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#458]
An API call currently calls `save_get_stream` which writes to disk:

https://github.com/n0-computer/iroh/blob/bd68e487ed0d0e07806f36eea4f4d8b5edcdef85/iroh-api/src/api_ext.rs#L13-L33

This shouldn't happen. Instead we should surface a helper method that makes it easy to write to disk, but the result should be streamed back as an API response that the user has more options to deal with.

Our API reads & writes to disk in many contexts. We should audit & remove these for _all_ of the iroh API

**Comment by ramfox** [comment]
for `add` process:
- re-export `unixfs_builder::DirectoryBuilder`, `unixfs_builder::FileBuilder`, `unixfs_builder::SymlinkBuilder`
- add `encode_to_store` method that takes a `Store`
`FileBuilder::new().path(path).build.encode_to_store(api)`
- needs an example
