### ISSUE TITLE
Moving away from GRPC

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#459]
We're having challenges with gRPC. @Arqu has framed our problem well:

gRPC is just not suited for our usecase. We have 3 types of usage:
- actual simple rpc endpoints
- small file transfers
- large file transfers/streams
Usually you tune for 1 of the two (there are adaptive windows and buffers etc but you still bias towards one end of the spectrum and it takes a lot to finetune it)
Then there's tonic, the actual implementation is not really at fault here, again it's our use cases and architecture for the most part. The "issue" we have with tonic specifically is that we need not just multiplexing over a single tcp connection but establishing multiple connections as a pool and using those (and that is a bit of a pain). Balanced_lists seem to work only with N different endpoints but not the same endpoint N times.
Finally we have tokio itself in the mix (which is admittedly a good generic async runtime) that we struggle with, mainly because we're asking it for a lot and have a pretty complex constellation of runtimes all while tokio being very sensitive on blocking calls (db, tcp etc) and being very easy to break the scheduling.
It's the main reason thread/runtime per core works so well (but that implementation is a bit ugly and for now is mostly linux only).

We are liking the look of [tarpc](https://github.com/google/tarpc), and have some early experiments:
https://github.com/n0-computer/iroh/pull/371

One major challenge we have is doing 1 request with many responses. We have a few examples we're working on, but so far the numbers are much better & we'll likely make the switch in our next release (currently v0.1.1).

cc @fabricedesre

**Comment by dignifiedquire** [comment]
We will likely not use tarpc, but potentially the new quic-rpc. @rklaehn is currently working on this. Ref #544

**Comment by dignifiedquire** [comment]
Closed by #580
