### ISSUE TITLE
refactor: move `unixfs` out of the `iroh-resolver` package

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#460]
We need to separate out the `unixfs` definition, `unixfs_builder`,  and `hamt` work from the rest of the `iroh-resolver` code.

This is a bit hairy as there is some cross-contamination of dependencies (`iroh-resolver::resolver` depends on some `iroh-resolver::unixfs` bits, and vice versa)

**Comment by fabricedesre** [comment]
That would be great, especially if that is reusable for native ipfs:// and ipns:// protocol handlers in browsers.
