### ISSUE TITLE
Docker images for each service

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#473]
We should be providing docker images for each cloud service. Doing rust + containers the right way should lead to super small production images in a multi-stage build with a much more full-featured build image.

Not having these is blocking contributions like #440.

- [x] decide on a multi-stage build / prod image that'll work for each service, start with the `store` service as an example
- [x] build out each service image
- [x] make sure the `iroh` CLI can be configured to talk to those images
- [x] do a one-off for `iroh-one` that puts everything in one image

**Comment by gotjoshua** [comment]
Thanks for thinking this through @b5  !

I think adding a check box for making these images not root user configurable is also an important addition

I like the idea that someone from the team takes this on.

**Comment by b5** [comment]
> I like the idea that someone from the team takes this on.

Roger that. I'll assign to myself as a start 😄 .

>  I think adding a check box for making these images not root user configurable is also an important addition

Just to confirm what you mean by this, I'm assuming you mean any iroh service binaries within production images should only have execute permissions for a non-root user, correct? I'd make an `iroh` user and `iroh` group that can execute. Sound good?

**Comment by b5** [comment]
update on this, we now have a working docker-compose example on `main`: https://github.com/n0-computer/iroh/blob/main/docker/docker-compose.yaml

PR that landed the work: https://github.com/n0-computer/iroh/pull/501

@gotjoshua, I'd love it if you could take a look at the dockerfiles, and ideally give that docker-compose setup a try. It's working will for me locally, but would be great to confirm. I'd also like to get your input on the prod image user. It doesn't have all the flexibility of `uid`/`gid` build options, but does follow idiomatic patterns for running as `nonroot` on distroless.

I'm marking this as closed, please feel free to open new issues as we work on our docker story

**Comment by Winterhuman** [comment]
@b5 Just in case, does the docker-compose file make sure not to expose any API to the public? (it's hard to tell if this is an issue for grpc or not) This was a previous issue with Kubo's docker-compose file and caused it's API to be publicly accessible: https://github.com/ipfs/kubo/pull/8773

Kubo's current docker-compose file: https://github.com/ipfs/kubo/blob/master/docker-compose.yaml

**Comment by b5** [comment]
oh this is a very good idea. We don't currently do this, and should. I'll open an issue. Thanks @Winterhuman!
