### ISSUE TITLE
Fix flakey `test_dht` function

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#518]
currently failing consistently on our M1 Mac CI runner:

https://github.com/n0-computer/iroh/blob/cd9fa2354e12cbeb6c4391007dd6170151108dfa/iroh-p2p/src/node.rs#L1448

**Comment by ramfox** [comment]
- even when we ensure the nodes are connected and have been added to kademlia, they don't seem to make it into any kbuckets, need to investigate how/when these get updated
