### ISSUE TITLE
Peers discovered using mDNS are not set as "connected"

### ISSUE THREAD

**Issue by fabricedesre** [n0-computer/iroh#526]
Peer discovery using mDNS seems to work fine and is fast, but the discovered peers are not added to the list of connected peers.

At https://github.com/n0-computer/iroh/blob/2f0f4f4fcef9fb7a3ec2d937e611de54016607b8/iroh-p2p/src/node.rs#L674 we get mdns discovery events that are not processed currently. But I have no idea what needs to be done to connect the new peers.

cc @ramfox / @dignifiedquire

**Comment by fabricedesre** [comment]
With this patch we get the correct count of connected peers, but still no bitswap traffic:

```diff
diff --git a/iroh-p2p/src/node.rs b/iroh-p2p/src/node.rs
index 66b6068e..a0de5be9 100644
--- a/iroh-p2p/src/node.rs
+++ b/iroh-p2p/src/node.rs
@@ -670,6 +670,18 @@ impl<KeyStorage: Storage> Node<KeyStorage> {
                     ));
                 }
             }
+            Event::Mdns(libp2p::mdns::MdnsEvent::Discovered(addrs)) => {
+                for (peer_id, _addr) in addrs {
+                    let dial_opts = DialOpts::peer_id(peer_id)
+                        .condition(libp2p::swarm::dial_opts::PeerCondition::Always)
+                        .build();
+                    if let Err(e) = Swarm::dial(&mut self.swarm, dial_opts) {
+                        error!("Failed to dial {:?}: {}", peer_id, e);
+                    }
+
+                    self.emit_network_event(NetworkEvent::PeerConnected(peer_id));
+                }
+            }
             _ => {
                 // TODO: check all important events are handled
             }
```

also I have no idea what I'm doing :rofl:

**Comment by dignifiedquire** [comment]
See my branch, the connected event shouldn't get sent there, as the dial is async, so we only know it got triggered, not that it succeeded.
