### ISSUE TITLE
running iroh p2p lookup gives `Protocols (0)` every time

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh#534]
currently running `lookup` on main is missing a bunch of data that should be there:

<img width="618" alt="Screen_Shot_2022-11-21_at_14 28 03" src="https://user-images.githubusercontent.com/1154390/203099590-2ca4ca7f-dd73-4412-b854-d1e601a038e0.png">

This is a regression. PR that fixes this should add a test

**Comment by ramfox** [comment]
Looks like we have never fully implemented lookup for the local case!

fixing this now

**Comment by Arqu** [comment]
We had it working before. I specifically drilled us on this when we started bitswap debugging as I noticed we never properly responded to `ipfs id` or when telneting the p2p port. It's highly probable we didn't wire it up again after dig did the line by line port. For reference I'd look up that specific commit, pretty sure it is a smaller isolated one where it got hooked up.
