### ISSUE TITLE
Implement HAMT directory writing

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#562]
It seems that you get the list of entries in the builder, and then just have to create the hamt.

This will of course fail when the list of files is too big to fit in mem, but a first impl would just implement a function that gets a list of entries and returns a set of blocks that make up the hamt, with the last being the root.

https://github.com/n0-computer/iroh/blob/5702c3e4666557e70993ebcf90b52cf1e04f0c0b/iroh-resolver/src/unixfs_builder.rs#L459

**Comment by dignifiedquire** [comment]
Fixed in #600
