### ISSUE TITLE
metrics: bitswap

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#58]
Record detailed metrics about bitswap.

Some  inspiration can be taken from https://github.com/ipfs-rust/libp2p-bitswap/blob/master/src/stats.rs

**Comment by Arqu** [comment]
Partially complete, keeping issue for another run at it.

**Comment by b5** [comment]
we should "repurpose" this issue to be about adding metrics to our go-bitswap translation

**Comment by Arqu** [comment]
done
