### ISSUE TITLE
Refine status monitoring

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#584]
It used to be based on tonic-health, which of course no longer makes sense. We need to do something basic ourselves.

Currently it is just hammering the version endpoint, but I guess that needs some refinement.

Basically the tonic health thing allows a service to announce itself that it is currently non-functional, that is the biggest difference.

https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by flub** [comment]
It seemed pretty rudimentary, so maybe simply calling the version RPC is sufficient to implement it as a start?

**Comment by rklaehn** [comment]
@ramfox this would be the issue to revive check and watch.

**Comment by ramfox** [comment]
@rklaehn sounds good!
