### ISSUE TITLE
iroh-lb

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#66]
We should start working on a load balancer for the gateway.
It's still early to have real use for it but it's much easier to evolve and grow with us.
Reasons to do it:
- we already have 2 gateways up, I'd love to have seamless handoff between the two
- puts us up on the stall to work on the "real stuff" from day 1
- should be easy enough to get started

Why not use something off the shelf
- I can se us getting into the weeds with this: I'd love to work on supporting % rollouts, feature flagging on the gateway level, failover mechanics, geo based balancing, rtt based balancing, contention based etc... Don't think anything of the self will give us enough flexibility

**Comment by b5** [comment]
I'm going to close this for now, priorities have shifted away
