### ISSUE TITLE
Ensure net simulations cover plain, lossy/laggy networks and NAT setups

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#730]
We should have some perf stats simulations across a range of network setups.

**Comment by dignifiedquire** [comment]
@Arqu what's the state on this?

**Comment by Arqu** [comment]
I basically have it all set up, waiting for x-hp to be merged for the NAT stuff to make sense.

**Comment by dignifiedquire** [comment]
Okay then I am going to close this and we can use #914 for tracking the hole punching related work.
