### ISSUE TITLE
Graceful shutdown of node

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh#736]
Provider should be able to be requested to be shut down.  At this point it should stop accepting new connections but continue any current transfer.  A timeout for continuing the existing transfer is not needed, if that takes to long a hard abort by the user is fine.

**Comment by flub** [comment]
moving milestone, this is not really relevant right now

**Comment by dignifiedquire** [comment]
@flub how much more work is left here in your opinion?

**Comment by flub** [comment]
I'm not sure how much all the current refactoring has changed things, so rebasing might be a bit tricky by now.  But what is needed:

- magicsocket should not be shut down when magicendpoint's close is called.  It should stay alive until the quinn endpoint driver is done with it (this endpoint driver runs in a spawned and detached tokio task) at which point it will drop the magicsocket.
- When dropped magicsocket should not stop, instead it should enter a draining state just like a socket from the kernel does.  When you send something to a real socket once it's accepted it won't be dropped.  We need to do the same.  So once magicsock is dropped it must refuse to accept any other sends, must refuse to receive anything or pass on anything received (that's easy, poll_recv is not going to be called anymore); but crucially it must still attempt to send all the things in the send buffers.
- Once drained, magicsocket can finally be deallocated.

In my old PR I have the first point done, not the rest.  This will probably need some changes now that there have been so much refactoring on the send and receive path.

I'm guessing this is like 3ish days work?

**Comment by flub** [comment]
There is also #2198, which is a duplicate of this I think.
