### ISSUE TITLE
Use lz4 compression

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#739]
When sending files that are not already somehow encoded, there would be a large gain 

There is a fully rust compression library called lz4_flex. https://crates.io/crates/lz4_flex

We could use this to reduce the amount of data that needs to be sent through en/decryption and through quic. Even for uncompressible data lz4 is very fast, so you probably would not even notice it WRT perf compared to the quic overhead.

The downside is the additional complexity. We should try this out only after having implemented/used larger bao block size. See n0-computer/iroh#741

Edit: zstd provides much better compression rates but is much more expensive. Also, there is no pure rust impl of zstd, unfortunately...

**Comment by dignifiedquire** [comment]
For reference, dropboxes post about how they use brotli: https://dropbox.tech/infrastructure/-broccoli--syncing-faster-by-syncing-less

**Comment by rklaehn** [comment]
I think we should not do this. It depends a lot on the data whether it is worth it, and for a lot of large data out there (movie files, archives etc.) it definitely is not worth it. It would also complicate the protocol for small blobs without providing much benefit.

I think we should leave this up to the user.

**Comment by dignifiedquire** [comment]
Yes, lets close it for now, we can always revisit if this becomes an issue.
