### ISSUE TITLE
Investigate radix trees as collections

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#807]
As discussed, I think it would be a nice compromise compared to a flat list. A bit more compact and powerful in terms of querying, but still a single hierarchy collection -> blob.

**Comment by rklaehn** [comment]
Here is a small experiment: https://github.com/rklaehn/radix-collection

E.g. load in the linux kernel, store relative paths:

count 84035
raw hash size 2689120
flat names: 3411397 total 6100517
tree names: 2704786 total 5393906

So the metadata of the entire linux kernel is just 6MB in the flat representation, and 5MB in the radix tree representation. Of which 2.6MB are just the unavoidable hashes. So the radix tree representation helps a bit with the file names, but not that much.

What is neat about the radix tree is that it allows fast querying of the data. E.g. 

```rust
    for (k, v) in tree.scan_prefix("sound/usb/") {
        println!("{} {:?}", std::str::from_utf8(k.as_ref()).unwrap(), v);
    }
```

lists all files below `sound/usb/` without having to do a full scan.

**Comment by dignifiedquire** [comment]
anything we want to do about this @rklaehn or can we close this for now?

**Comment by rklaehn** [comment]
> anything we want to do about this @rklaehn or can we close this for now?

I think we are basically doing something already by decoupling the concept of collections from the core.

In my opinion we should support 1 kind of collection out of the box: a sequence of links. Everything else should be up to the user.

**Comment by rklaehn** [comment]
I think we should just make sure that iroh-bytes is flexible enough and then have this as an example how to deal with extremely large collections.

So closing this and tracking further development in https://github.com/n0-computer/iroh/issues/1328
