### ISSUE TITLE
Fix install.sh

### ISSUE THREAD

**Issue by parajbs** [n0-computer/iroh#815]
hello @n0-computer,

Following this guide I wanted to install iroh:
https://iroh.computer/docs/install/

I was about to test iroh, but when I downloaded iroh "install.sh" with curl:
curl -fsSL https://sh.iroh.computer/install.sh
but there is an error message 403:
curl: (22) The requested URL returned error: 403

When I tried to access the link in the browser, I got an error message:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F4A6075KG66BJYES</RequestId>
<HostId>3b6gmlAyRY6uYgLzJZ8Rjdk2WLs65XnwgNLGjVYzCoC6GzvRj1Tn+lxbgSUhiTfdOSFxDU0eqkU=</HostId>
</Error>

What's up?
How can I install iroh in widows10 or docker debian12?

can you help?

**Comment by flub** [comment]
the iroh.computer site needs updating for the new iroh.  that'll follow as we continue developing it into a full replacement for the first iroh.

**Comment by dignifiedquire** [comment]
@b5 @Arqu is this fixed?

**Comment by Arqu** [comment]
It was. I have to take another pass now that a lot of stuff moved.

**Comment by Arqu** [comment]
This is taken care of for now, we moved to a new install script `https://sh.iroh.computer/setup_iroh.sh`
