### ISSUE TITLE
HELP! iroh.exe is detected as "Trojan:Script/Wacatac.H!ml" in windows10.

### ISSUE THREAD

**Issue by parajbs** [n0-computer/iroh#816]
hello @n0-computer,

Help!!!!

I am writing how I proceeded.
1. git clone https://github.com/n0-computer/iroh.git
2. cd iroh
3. corgo build --release
4. cp ./target/release/iroh.exe iroh.exe

Up to this point everything has worked.

Now I have two more windows10 cmd windows open

in the first cmd window:
1. d:/iroh/iroh.exe provide
Listening address: 127.0.0.1:4433
PeerID: ZnvAXUhlRnlRL2LFZ_hY-jM_vgLmpjWhUTlPbS6cmRw
Auth token: NJpCgxSFatJxs6sW39qRnKwQg8SyfuGtUAeMicRUOGU

In the second cmd window:
1. d:/iroh/iroh.exe add target/release/iroh.exe

Adding target/release/iroh.exe...
- target/release/iroh.exe: 6.33 MiB
Total: 6.33 MiB

Collection: bafkr4igswe4wl23qrq3elxmj2yzcaesgboqaqcjue337dkg5ibmqecbype

That still worked, but now with the get command the problem comes that iroh.exe is recognized by the windows10 virus scanner as a serious security problem = "Trojan:Script/Wacatac.H!ml" and is then automatically deleted.

what's going on That should not happen.
Please clarify or improve it so that it also survives virus scanners.
Otherwise iroh is an interesting project.

**Comment by flub** [comment]
I'm not sure why the virus scanner things this is a trojan, if you built from our source it isn't.  You'll need to investigate how your virus scanner makes this classification and configure it correctly.  This is compiling code from source and running it and not an installer we distribute, so nothing to do with us.

**Comment by parajbs** [comment]
Hello **@n0-computer,**

Yes, I "master" built iroh from source https://github.com/n0-computer/iroh.git as you can see in the description above.

**My virus scanner is that of Windows 10 Defender Antivirus "Windows Security", in the standard setting, as after a new installation (as not changed).**

when I build (compile) other apps and then run them, they work great without being recognized by the virus scanner. I just tried it and like above description just another app. Everything is ok.

now recompiled again, as described above.
I haven't changed anything in your code, just built it.
And like you said "This is compiling code from source and running it and not an installer", so just your code.
The virus scanner recognized iroh.exe again and automatically deleted it.

I just ran the process again on another computer, which has the same problem with the Windows anti-virus scanner.

Because the virus scanner scanner hits the file "iroh.exe" by default, and it's just your code.
Have you tested it yourself in windows10?

And to change the standard setting of the virus scanner so that "iroh.exe" is no longer recognized or is deleted, I think is a bad idea.

I also noticed that when I run the iroh get command, it also downloads the file, but this downloaded version of iroh_test.exe is also detected by the virus scanner and deleted.

Since the problem occurs on two comtupers and it's only their code, I'll say it's more the iroh code.
Even the downloaded iroh_test.exe is deleted by the virus scanner.
From my point of view it is certainly due to a problem in the code of "iroh".
But it is clear to me that it is not a Trojan, but that the virus scanner works is not good for your program.

I hope you get the problem fixed
if you have any questions, please contact me.

**Comment by parajbs** [comment]
This link and message was sent to me on the internet for help, but I think this help in the link should better be carried out by the developer of the software.

here is the link and message:

```
maybe this can help: https://www.microsoft.com/en-us/wdsi/filesubmission
[Submit a file for malware analysis - Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission)
Submit suspected malware or incorrectly detected files for analysis. Submitted files will be added to or removed from antimalware definitions based on the analysis results.
```

I hope it helps you and you get the problem fixed.
I keep my fingers crossed.
