### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#841]
ML devs like python. So let's give them iroh wrapped in a python call

Using something like https://github.com/PyO3/pyo3

**Comment by rklaehn** [comment]
This seems to be rather straightforward with pyo3. Did a small experiment.

Making an idiomatic binding would of course still be some work, and ideally require somebody familiar with python...

**Comment by flub** [comment]
> and ideally require somebody familiar with python...

hi

**Comment by dignifiedquire** [comment]
we now have preliminary python bindings here: https://github.com/n0-computer/iroh-ffi

**Comment by ramfox** [comment]
> we now have preliminary python bindings here: https://github.com/n0-computer/iroh-ffi

@rklaehn @dignifiedquire 

Can we close this issue in light of the ffi bindings?

**Comment by dignifiedquire** [comment]
Yes, closing as we now have python bindings. Specific requests for API & features should go into `iroh-ffi`
