### ISSUE TITLE
Go back to hex or base32 peerids

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#842]
I think the current way of using base64 for peerids is very unergonomic when using the command line. 

1. You can usually not just select the strings with a click, since due to the special chars they are not a single word
2. If you are extra unlucky you will get a peer id that starts with a `-`.

E.g. I got a peer id `-C7yIPRL4Eoy51QS6p6uMyxUsGMkgSWJUmh7gHbqALU` and found it really hard to pass this as an argument to e.g. get.

```
❯ ~/projects_git/iroh/target/release/iroh get --peer -C7yIPRL4Eoy51QS6p6uMyxUsGMkgSWJUmh7gHbqALU --auth-token stigZsDPpuDU-yBld8fAy9EwE0RjfKBy7Z4T3LNxxbM bafkr4iafyu5wgg4em5tz5bxyyxfiqypktgdd4t4ukzwztpbf2c4i5pzove 
error: unexpected argument '-C' found

  note: to pass '-C' as a value, use '-- -C'

Usage: iroh get [OPTIONS] --peer <PEER> --auth-token <AUTH_TOKEN> <HASH>

For more information, try '--help'.
```

🙄 

The concern of these strings being too big for the QR code should be addressed in a different way.

**Comment by flub** [comment]
Yes, this is a real problem and I couldn't figure out how to pass such a PeerId when I had this.  @Arqu also complained about this in the past.  Base32 is a bit smaller than hex, so maybe prefer that?

**Comment by Arqu** [comment]
how about those good ol Qm... or bafy... multihashes :P
Either way, while I've worked around it, it is very annoying to me personally. Just feels *not right* when you encounter those. Don't have a strong preference on what exact encoding to use but anything without special chars would be great.

**Comment by rklaehn** [comment]
I don't see what is wrong with hex. Everybody understands it, and it's not like 5 bits per char vs 4 bits per char is going to make a difference. I am not going to type those strings anyway...

**Comment by dignifiedquire** [comment]
We now use base32 in all CLI output
