### ISSUE TITLE
Make creating a directory the default when asking for a collection with more than 1 element.

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#843]
If you currently get a directory, you will just get the concatenation of all files.

This is not what you want if you want to replicate a large directory.

Found this confusing when trying out sharing a large data set.

**Comment by ramfox** [comment]
The default on the cli is that if you don't specify an `out`, the contents of the collection get pushed to stdout, if you specify an `out` path, the contents get saved in the out directory.

Is this what you are running into?

**Comment by rklaehn** [comment]
Yes. Nothing major, but I was playing around with ML datasets, and having a 300GB dataset being dumped on the CLI is definitely not what I was after.

The terminal was so irritated by the amount of data and all the weird chars that I had to close the tab. Not a good user experience.

**Comment by dignifiedquire** [comment]
I wonder if we should dumping to `stdout` not a default, but rather something specific with an option like `--to-stdout` or sth like this.

**Comment by dignifiedquire** [comment]
I have run into this a couple of times, I don't think the current behaviour is that great. 

@rklaehn @Arqu @b5 would love some thoughts on what a good UX should look like here

**Comment by Arqu** [comment]
My 2c:
Personally I think it should just have a sane default name and do `./default` if nothing else is specified. This usually leads to dumping whatever you're pulling into `./some_weird_hash` which is far from ideal (maybe named collections later can rectify this). And if you want to explicitly pipe to stdout, then you can flag for it. This will mostly not be a CLI based consumption tool afaik.

**Comment by rklaehn** [comment]
Can we just say that you have to provide an out arg when downloading a collection? You can still have the simple curl use case when downloading individual files, which is supported now.

So you can still do workflows involving individual files like the infamous `curl | sudo sh` stuff.

But I find that wanting all items of a collection concatenated is rare even for smaller data sets.

**Comment by dignifiedquire** [comment]
I think sth like `--stdout` or `--out <foo>` would work well (where you always have to choose one) instead of doing different things depending on the content

**Comment by rklaehn** [comment]
So the default behaviour of share when not providing an out dir is to just download it to the local store. Which I think is fine, because it does not try to output a giant amount of data to the console.

Maybe just discourage get in favour of share?
