### ISSUE TITLE
Organize commands

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#849]
Now that iroh has daemon mode and persistence (soon...), we have to have a very large list of commands.

E.g.

id
list (what is that good for anyway)
validate
repair
shutdown

It is going to get more. We need to go over these commands and structure them in a meaningful way so that advanced commands are not in your face and the console UX gets better.

**Comment by dignifiedquire** [comment]
There was some restructuring done of this. Another pass will likely come with `0.6.0` so closing this as done.
