### ISSUE TITLE
Provide some main.rs logic as a library

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#876]
Not sure what the best way is to do this, but a lot of the stuff in main is also valuable for users of iroh as a library.

E.g. the ability to create directory trees, all the progress logic including progress bars, ...

E.g. if somebody were to use iroh as a library from python, they would currently be unable to do it because the directory creation logic is in main. And they also might want to have progress bars and stuff.

So how do we do this? Feature flags?

**Comment by b5** [comment]
closing this as stale
