### ISSUE TITLE
Quic-rpc transport that does not use a port

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#899]
The port is annoying, especially when running multiple irohs on one machine, and in tests.

I think with https://crates.io/crates/interprocess we could have a platform independent way to do use a local socket. How it would work: you create a file in `.iroh`. On unix this is an unix domain socket. On windows, this is the *name* of a named pipe. Supposedly win11 even supports UDS, but we will have to support win10.

We just need a quic-rpc transport that uses interprocess. Does not have to be extremely fast, since we don't send the data over this channel anymore.

**Comment by rklaehn** [comment]
This is a draft PR to add UDS support to quic-rpc for this https://github.com/n0-computer/quic-rpc/pull/48

**Comment by dignifiedquire** [comment]
We tried this, but it was reverted, so closing as stale for now
