### ISSUE TITLE
IPNS support?

### ISSUE THREAD

**Issue by vegabook** [n0-computer/iroh#904]
My use case is live, streaming time series data which will be aggregated into chunks of various resolutions (minute, hour, day). 

In other words, every minute, a new file is created. It is added to the set of all previous minute files. The entire set has a single addressable name that does not change, even though the set is being added to constantly. 

Does iroh support IPNS in order to make this use case possible? If not, is there another way to support this use case using iroh? It is not clear to me from the documentation whether or not [collections](https://iroh.computer/design/content-addressing) can be appended to without changing the collection root CID. 

I further note the ability to seek into a blob. Perhaps this would allow for _continuously_ growing data, avoiding the need for minute/hour/day segmentation? I'm assuming this would violate the content-based addressing?

Posting as issue as I see no links to forums on docs or github.

**Comment by Winterhuman** [comment]
Based on https://github.com/n0-computer/iroh/discussions/707#discussioncomment-5070226, I don't think they're looking into an IPNS-like system for Iroh, at least not in the near term

**Comment by flub** [comment]
I wouldn't say we won't be going anything IPNS-like.  There is a need to be able to refer to a collection by name.  But we don't yet know what form this will take.
