### ISSUE TITLE
Implement Windows firewall rules

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh#911]
The `windows` crate has the required APIs likely. 

The actual rules we can orient ourselves on https://github.com/tailscale/tailscale/blob/main/wf/firewall.go

Ref
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/WindowsFirewall/index.html
- https://learn.microsoft.com/en-us/windows/win32/api/netfw/nn-netfw-inetfwopenports
- https://stackoverflow.com/questions/8488227/create-firewall-rule-to-open-port-per-application-programmatically-in-c-sharp
- https://github.com/microsoft/windows-rs/blob/a672f5f450b16c947840ab89fdc5ddd16d1fd0d0/crates/libs/windows/src/Windows/Win32/NetworkManagement/WindowsFirewall/impl.rs#L1471

**Comment by dignifiedquire** [comment]
Looking at the things that tailscale allows, we will need 

- [x] `permitTailscaleService(weightTailscaleTraffic)` (aka allow all traffic for iroh) 
- [ ] `permitTunInterface(weightTailscaleTraffic)`
- [x] `permitDNS(weightTailscaleTraffic)`
- [x] `permitLoopback(weightTailscaleTraffic)`
- [ ] `permitDHCPv4(weightKnownTraffic)`
- [ ] `permitDHCPv6(weightKnownTraffic)`
- [x] `permitNDP(weightKnownTraffic)`

**Comment by dignifiedquire** [comment]
Not needed, see https://github.com/n0-computer/iroh/pull/1213#issuecomment-1632347039
