### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by mxcl** [n0-computer/iroh#943]
I built it and then tried to grab a small sample hash:

```
$ iroh get QmRAQB6YaCyidP37UdDnjFY5vQuiBrcqdyoW1CuDgwxkD4
error: invalid value 'QmRAQB6YaCyidP37UdDnjFY5vQuiBrcqdyoW1CuDgwxkD4' for '<HASH>': Unknown base code: Q

For more information, try '--help'.
```

I cannot find any example usage in the docs so I'm not sure what is wrong with the hash.

**Comment by rklaehn** [comment]
It looks like you are looking for the fully kubo compatible version of iroh. That has been renamed as beetle, find it here: https://github.com/n0-computer/beetle

Sorry about the confusion.

**Comment by mxcl** [comment]
Closing.

I don't understand this project or the other. I was hoping for an example. I clicked through to the other project hoping that would help me understand more but all the docs there refer to `iroh` and not `beetle` so I'm just going to back slowly towards the door and maybe come back in a few months. Thanks.
