### ISSUE TITLE
iroh add from a separate process is slow-er in a tty env?

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#946]
Running `iroh add` (for eg the linux kernel) when you have a separate `iroh provide` process is very slow. Moving to a non tty env and not having fancy progress bars makes it blazing fast again.

**Comment by b5** [comment]
any rough sense of the definition of "slow" and "fast" here?

**Comment by Arqu** [comment]
Sorry yeah, fast=finishes in <15 sec or so. Slow = takes 3+ min.

**Comment by Arqu** [comment]
Just to add color here, think that @rklaehn cleaned up some of this already. It was mostly in the progress reporting.

**Comment by Arqu** [comment]
AFAIK this is no longer an issue.
