### ISSUE TITLE
Error with libc when installing `iroh` on Linux

### ISSUE THREAD

**Issue by davidgasquez** [n0-computer/iroh#947]
When running the [installation script](https://iroh.computer/docs/install/), I'm getting the following error.

```bash
$ curl -fsSL https://sh.iroh.computer/install.sh | sh
Fetching iroh from http://vorc.s3-website.us-east-2.amazonaws.com/iroh-linux-amd64-latest
######################################################################## 100.0%
Moved iroh to /usr/local/bin/iroh

iroh was installed successfully to /usr/local/bin/iroh
Run 'iroh --help' to get started

Stuck? Check out this discussion: https://github.com/n0-computer/iroh/discussion
root ➜ / $ iroh
iroh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by iroh)
iroh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by iroh)
iroh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by iroh)
```

Steps can be reproduced running the installation command inside an Ubuntu container: `docker run -it mcr.microsoft.com/devcontainers/base /bin/bash`

**Comment by rklaehn** [comment]
Thanks for the issue. I guess we should compile it with musl or something to get rid of the libc dependency...

**Comment by davidgasquez** [comment]
Any updates on this one? :sweat_smile: Excited to play with `iroh`!

**Comment by flub** [comment]
You can easily play by installing it from source, I just tried with the image you use and this works:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
export PATH=$HOME/.cargo/bin:$PATH
cargo install iroh
iroh --help
```

**Comment by davidgasquez** [comment]
Thanks @flub! That worked. Not sure why it didn't cross my mind. :sweat_smile:

**Comment by dignifiedquire** [comment]
Given the original issue was fixed, closing.
