### ISSUE TITLE
Refactor iroh to make collection parsing pluggable

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#949]
Rationale:

- there are differing opinions about what should be in a collection, e.g. deltachat does not need mime types, @fabricedesre wants them for capyloon
- making this pluggable would enable supporting non iroh collections like dag-cbor containing links
- making it pluggable would enable DAG use cases and also allow a migration path for ipfs projects that currently use dag-cbor
  - peergos champ
  - wnfs (public and private)
  - banyan (hail data in midwest US use case)

**Comment by dignifiedquire** [comment]
@rklaehn what's the state of this?
