### ISSUE TITLE
Make the get request errors more precise

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#962]
We now got a nice FSM for the get response, but the errors are still pretty coarse. We can make this more fine grained by having at each state an error enum that contains exactly the things that can go wrong at this point, and nothing more.

This should also try to surface the quinn errors out of io::Errors everywhere.

Maybe a bit too much effort, but we got so few APIs that we might as well polish them...

**Comment by ramfox** [comment]
@rklaehn was this closed by #1362?

**Comment by divagant-martian** [comment]
Closed by #1999 & #1362
