### ISSUE TITLE
Get rid of size prefixes in get request/response protocol

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#964]
There are two places where we use `write_lp`: 

- [x] the handshake and 
- [ ] the request.

The handshake is fixed size, so does not need a size prefix. The request is variable size, but it is also the last thing being sent, so the receiver could just read to the end.

**Comment by dignifiedquire** [comment]
> so the receiver could just read to the end.

I would like to avoid this, given buffer allocations and potential memory attacks, it also doesn't cost us much in this case.

**Comment by rklaehn** [comment]
How does a size prefix prevent you from memory attacks?

If you just allocate whatever is the size prefix, somebody can still send you u64::MAX as the size. And if you put a limit on it, you can also put a limit on the buffer that you read into from the stream.

**Comment by rklaehn** [comment]
With https://github.com/n0-computer/iroh/pull/1408 this is implemented.

We still have a size prefix in the response to a CustomGet, but I think that one makes sense to keep. Only question is whether it should be varint encoded.

**Comment by ramfox** [comment]
@rklaehn w/ #1408, are we okay to close?

**Comment by rklaehn** [comment]
CustomGets are gone, so this is done....
