### ISSUE TITLE
Clean up run_ticket vs run, run_connection etc.

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#967]
All the various get::run_xxx things basically dial in some way, then run run_connection.

I would argue that the default should be run_connection, which should be renamed to run. The assumption is that you usually already have a connection when you want to get something.

Then the various ways to dial could move to another module. Maybe even make the whole ticket stuff part of main or the porcelain feature flag, since it is just a convenient way to dial and not core.

WDYT @flub ?

**Comment by flub** [comment]
sounds reasonable.  it kind of grew like this by accident.  You can even make the various `dial_*` funcs pub and let the user combine those things, it's not that complicated for them.

**Comment by dignifiedquire** [comment]
@rklaehn is there anything left after your refactors?

**Comment by rklaehn** [comment]
There is always more to do, but I think it is sufficiently minimal that we can close this for now.
