### ISSUE TITLE
Tool to detect network state (public ips, relays, NAT traversal etc.)

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#979]
Write a tool similar to the old `dat doctor`.

It should have two main functions:

1. acquire and show basic information about your node
  - peer id etc.
  - information about available networks
  - reachable derp servers
  - public addresses

2. troubleshoot one particular connection
  - show a command that has to be entered on the remote peer
  - listen for incoming connections from said remote peer
  - find out and show info about all possible connections between the two nodes
  
![image](https://user-images.githubusercontent.com/248257/236790596-53eb85b3-0531-4f23-97d1-423d3e4a3872.png)

![image](https://user-images.githubusercontent.com/248257/236790684-f1caf0de-62f0-41a1-998d-78ca3af8ca24.png)

**Comment by dignifiedquire** [comment]
@rklaehn can this be closed, or did you plan for more here?
