### ISSUE TITLE
feat: PSK support

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#983]
In order to have secure authentication for connections, and allow creating things like private networks, we need some form of pre shared key encryption support.

Using https://datatracker.ietf.org/doc/html/rfc8773 we should be able to add pre shared key support on a network level. 

Before we can use this, we need support for this in rustls: https://github.com/rustls/rustls/issues/174

Looking at the comments in the linked rustls issue, we might be able to use an even more rustls native approach. This needs more design & review of RFCs and implementation.s

**Comment by rklaehn** [comment]
Hopefully we are still looking into using noise. I think coming up with some PSK scheme should be doable. We don't need to go to TLS for this...

**Comment by dignifiedquire** [comment]
The point is to avoid double encryption, which using TLS would allow us to do. If we do go to noise, it is very easy, as it has builtin PSK support..

**Comment by dignifiedquire** [comment]
Closing as stale
