### ISSUE TITLE
Implement peer discovery in LAN

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#990]
This would likely be done using MDNS. 

@fabricedesre mentioned he uses https://github.com/WilliamVenner/searchlight successfully for this.

**Comment by rklaehn** [comment]
This would probably be needed to get very principled local first applications such as https://github.com/Actyx/Actyx to adopt iroh.

Two devices in the same airgapped network should be able to find each other without a relay.

**Comment by dignifiedquire** [comment]
No this is not done, both PRs had some issues, and we do not have a good solution implemented yet.

**Comment by rklaehn** [comment]
@ramfox this can be closed, right?

**Comment by dignifiedquire** [comment]
yes
